### ISSUE TITLE
[Request] Powershell

### ISSUE THREAD

**Issue by ojosdegris** [adambard/learnxinyminutes-docs#1020]
Would be nice to have it here.

**Comment by aloisdg** [comment]
I second this

**Comment by Szelzz** [comment]
+1

**Comment by ioab** [comment]
Agreed.
@farleykreynolds has offered a tutorial on powershell: [PowerShell/en] #1750

**Comment by Laoujin** [comment]
Yeah, I was also going to use learnxinyminutes for PowerShell but alas it didn't exist :)

**Comment by aloisdg** [comment]
Nice!

**Comment by ryanmavilia** [comment]
@ojosdegris could you please close this issue now that Powershell has been added? Thanks!
