### ISSUE TITLE
C: negation and shift

### ISSUE THREAD

**Issue by jcmvbkbc** [adambard/learnxinyminutes-docs#1021]
> ~0x0F; // => 0xF0 (bitwise negation, "1's complement")

This looks like byte negation, but 0x0f is of type int. A typical result could be 0xfffffff0.

>// - shifting into the sign bit of a signed integer (int a = 1 << 32)

Should be (int a = 1 << 31), as 31'st bit is the sign bit of a 32-bit wide int.

**Comment by vendethiel** [comment]
Nice catch! Would you mind sending a pull request to fix it:)?
