### ISSUE TITLE
Issue with Go rendering

### ISSUE THREAD

**Issue by zchrykng** [adambard/learnxinyminutes-docs#1029]
For some reason Go is being shown in two rows rather than one. Have attached a screenshot.

![screenshot 2015-03-31 18 41 08](https://cloud.githubusercontent.com/assets/1266571/6930905/c45f46ac-d7d5-11e4-893b-3e05f2c96b6a.png)

Not sure what is causing this, but thought I would report it in case someone else can figure it out... hard to say without knowing how this are being rendered out, which I didn't see in the repo, though I might have just missed it.

**Comment by adambard** [comment]
Thanks for the heads up! The French go translation forgot to include their lang tag and gets rendered twice, should be fixed in a few minutes with the next auto-build.

**Comment by vendethiel** [comment]
Seems to be okay now

**Comment by adambard** [comment]
Seems fixed, thanks for the warning.

**Comment by zchrykng** [comment]
No problem, glad to help.
