### ISSUE TITLE
Perl6, infinite lists

### ISSUE THREAD

**Issue by brxfork** [adambard/learnxinyminutes-docs#1032]
Some remarks about this paragraph:  

    # You can use that in most places you'd expect, even assigning to an array  
    my @numbers = ^20;  
    @numbers[5..*] = 3, 9 ... * > 90; # The right hand side could be infinite as well.  
                                      # (but not both, as this would be an infinite loop)  
    say @numbers; #=> 3 9 15 21 27 [...] 81 87

1. There are missing data in comment `say @numbers`: **0 1 2 3 4** 3 9 15 21 27 33 39 45 51 57 63 69 75 81 87
2. Reader (me) could misunderstand that sequence stops at 87 because of `* > 90`. In fact, `* > 90` is useless, and the result will be identical with `@numbers[5..*] = 3, 9 ... *`. It's not obvious that this is because of `my @numbers = ^20` and `@numbers[5..*]`
3. It could be something like that:

.

    # You can use that in most places you'd expect, even assigning to an array  
    my @numbers = ^20;  
    my @seq =  3, 9 ... * > 95; # 3 9 15 21 27 [...] 81 87 93 99  
    @numbers[5..*] = 3, 9 ... * > 95; # The right hand side could be infinite as well.  
                                      # (but not both, as this would be an infinite loop)  
    say @numbers; #=> 0 1 2 3 4 3 9 15 21 27 [...] 81 87

**Comment by vendethiel** [comment]
I've been mulling over this for the past two weeks because it didn't seem to make sense to me.
I only just now realized that `@foo[5..*]` uses `postcircumfix:<[ ]>`'s `Callable` overload, which is why the list isn't Infinite. sigh...

**Comment by vendethiel** [comment]
@brxfork I changed it, please tell me what you think about it.

**Comment by brxfork** [comment]
@vendethiel Thanks a lot!
