### ISSUE TITLE
[All] Call for UI Translations!

### ISSUE THREAD

**Issue by adambard** [adambard/learnxinyminutes-docs#1053]
If you can translate a few UI sentences into whatever language, they will be used on doc pages for that language (as in the zh-cn articles live now).

https://github.com/adambard/learnxinyminutes-site/blob/master/data/i18n.yaml
- Make the language tag lower-case and use an underscore (_) instead of a hyphen (-)
- Fill out entries for the 6 template strings
- The `suggestions` template string should contain one formatting `%s` in the URL.
- The `contributor` template string should contain two `%s` and one `%d` formatting bits for the contributor, url, and count.

Alternately, you can just post the translation YAML below and I'll add it.

**Comment by jsseb** [comment]
Added a Spanish translation: https://github.com/adambard/learnxinyminutes-site/pull/6

Also I think the X and Y of the title and where templates are mixed on the Chinese translation.

**Comment by geoffliu** [comment]
@jsseb The Chinese translation actually says "Learn Y in X minutes," which is why the "where" line has "Y=". I couldn't find a natural wording in Chinese that can keep the X, Y order the same as English.

**Comment by aloisdg** [comment]
I added a small correction to the french version.

Also, you can consider to switch from "Pull Request" to "demande de tirage" as mentioned at [git-scm.com](http://git-scm.com/book/fr/v1/Git-distribu%C3%A9-Contribution-%C3%A0-un-projet). I am not sure about this one. I am french and we all use "Pull Request" as far as I know.

**Comment by Alwayswithme** [comment]
@geoffliu I think swap X and Y is OK, no need to worry about Y first appear, what do you think?

**Comment by geoffliu** [comment]
@Alwayswithme I don't think it's a big deal either way, it's always a trade off; translations are never perfect. If I had to choose though, I would rather keep the X-Y order in the title, and stick with "where Y="

**Comment by adambard** [comment]
I guess it comes down to which order sounds more natural in Chinese, which I'll have to defer to someone else about. As long as the meaning is correct it's totally fine either way.

**Comment by geoffliu** [comment]
I'm for keeping it as is, unless there's a compelling argument otherwise.

**Comment by TheDmitry** [comment]
Added a Russian translation: https://github.com/adambard/learnxinyminutes-site/pull/11

**Comment by Ribeiro** [comment]
Added Brazilian Portuguese translation - PR #14

**Comment by scheras** [comment]
Added Czech translation: https://github.com/adambard/learnxinyminutes-site/pull/20

**Comment by blacktoko** [comment]
Added Dutch translation: https://github.com/adambard/learnxinyminutes-site/pull/22

**Comment by JoaoFCosta** [comment]
@adambard 
Here is the Portuguese (PT-PT) Translation

pt_pt:
  title: Aprende X em Y minutos
  where: Onde X=
  getCode: "Download do código:"
  share: Partilha esta página
  suggestions: "Tens alguma sugestão? Uma correção, talvez? <a href=\"%s\">Abre um Issue</a> no repositório do Github, or faz um pull request tu mesmo!"
  contributor: "Originalmente contribuido por %s, e atualizado por <a href=\"%s\">%d contribuidor(es)</a>."
