### ISSUE TITLE
mention of parrot should also mention suspension

### ISSUE THREAD

**Issue by perlpilot** [adambard/learnxinyminutes-docs#1057]
Support for Rakudo on Parrot is currently suspended.   This deserves a mention at the top where the docs say that "Perl 6 runs on the Parrot VM, the JVM and the MoarVM."

Or possibly, omit the mention of Parrot there at all.

**Comment by levibostian** [comment]
Thank you for the issue @perlpilot. Do you mind making a PR for this issue please? Thanks again.

**Comment by perlpilot** [comment]
See https://github.com/adambard/learnxinyminutes-docs/pull/1062

**Comment by samcv** [comment]
@vendethiel This can be closed, the Perl 6 page doesn't reference Parrot anymore.

**Comment by vendethiel** [comment]
@samcv 👍
