### ISSUE TITLE
[python/en] correct usage of print

### ISSUE THREAD

**Issue by srirams6** [adambard/learnxinyminutes-docs#1058]
The entire doc uses `print("test")` instead of `print "test"`. Even though `print_function` is imported from `__future__`, this isn't the default print statement in python 2. It would confuse people that are new to the language. I propose to change all the print statements to the default python 2 print. 

If this is issue is in order, I shall send a PR.

**Comment by geoffliu** [comment]
+1

**Comment by levibostian** [comment]
:+1: I agree. Python 2 only though, agree?

**Comment by srirams6** [comment]
Yeah. Only for python2!

**Comment by srirams6** [comment]
Sent PR #1059
