### ISSUE TITLE
C# parallel example is misleading

### ISSUE THREAD

**Issue by kyberias** [adambard/learnxinyminutes-docs#1064]
The C# tutorial's parallelism-example is misleading. The example launches threads to wait for asynchronous requests to complete. This is not a good example of using multiple threads since they all basically sleep waiting for the requests to complete. This is perhaps a good place for an async example? A better example for parallelism would actually utilize the thread for e.g. processing subsets of some data.

**Comment by levibostian** [comment]
Thank you for the issue @kyberias. A pull request would be more then welcome with this issue as you have a pretty good idea on how to fix this. Thanks!

**Comment by chriszimmerman** [comment]
It appears the PR for this issue has been accepted and merged. I believe this issue can be closed.
