### ISSUE TITLE
[Haskell] Foldr example seems incorrect

### ISSUE THREAD

**Issue by TiddoLangerak** [adambard/learnxinyminutes-docs#1068]
From the tutorial:

```haskell
-- foldl is left-handed, foldr is right-
foldr (\x y -> 2*x + y) 4 [1,2,3] -- 16

-- This is now the same as
(2 * 3 + (2 * 2 + (2 * 1 + 4)))
```

However, according to the [Haskell wiki](https://wiki.haskell.org/Fold) `foldr` is defined as followed:

```haskell
-- if the list is empty, the result is the initial value z; else
-- apply f to the first element and the result of folding the rest
foldr f z []     = z 
foldr f z (x:xs) = f x (foldr f z xs) 
```

If I use that to derive to the resulting equation I get this:

```haskell
--I've extracted the lambda to a function for better readability
f :: Int -> Int -> Int
f x y = 2 * x + y

foldr f 4 [1, 2, 3]
=> (f 1 (foldr f 4 [2, 3]))
=> (f 1 (f 2 (foldr f 4 [3])))
=> (f 1 (f 2 (f 3 (foldr f 4 []))))
=> (f 1 (f 2 (f 3 4)))
=> (f 1 (f 2 (2 * 3 + 4)))
=> (f 1 (2 * 2 + (2 * 3 + 4)))
=> (2 * 1 + (2 * 2 + (2 * 3 + 4)))
```

For this particular equation the resulting value is still equal, but it doesn't work for the general case. E.g. if we'd had `f x y = 2 * y + x` then following the tutorial would result in:

```haskell
(2 * (2 * (2 * 4 + 1) + 2) + 3) -- 43
```

But according to the wiki we should get:
```haskell
(2 * (2 * (2 * 4 + 3) + 2) + 1) --49
```

`49` is also the result ghci gives when I try to run this there.

I'm still learning Haskell though, so perhaps someone more experienced could chime in here.

**Comment by levibostian** [comment]
I think you make a very good point here. I am not familiar with Haskell myself either but if you enter the commands in the tutorial and they give the wrong input like you are stating, then we should fix the examples.

**Comment by geoffliu** [comment]
@TiddoLangerak Your interpretation is correct, the doc is wrong. You're welcome to send a pull request, or I can do one later in the week.
