### ISSUE TITLE
CSS version inconsistency

### ISSUE THREAD

**Issue by g-liu** [adambard/learnxinyminutes-docs#1082]
At the top of the [Learn CSS](http://learnxinyminutes.com/docs/css/) page, it says

> Here we focus on CSS2.0
> which is not the most recent but the most widely supported and compatible version.

But the rest of the tutorial mentions CSS3 in almost a dozen places. This is somewhat contradictory to the statement above.

Should we scratch the above line from the file and include more CSS3 things, or should we make a separate CSS3 tutorial?

**Comment by levibostian** [comment]
My vote is to throw it all into the same one. But I see benefits to either so doesn't matter too much to me. Would be nice to prevent the CSS doc getting super long, but for me as a LXIYM user, I would rather open up the CSS doc and CTRL+F then type "background-image" for example and see both CSS2 and CSS3 in there for a one stop reference. That is why I say put in the same one.

**Comment by levibostian** [comment]
Nice catch by the way, thanks!

**Comment by duci9y** [comment]
I believe this issue can be now closed.
