### ISSUE TITLE
perl6 "0" is now True

### ISSUE THREAD

**Issue by stmuk** [adambard/learnxinyminutes-docs#1094]
on line 214 "# Only these values are Falsey: (), 0, "0", "", Nil, A type (like `Str` or `Int`),"

should be changed to remove "0" soon (maybe after the next star release?)

$ /opt/rakudo-star-2015.03/bin/perl6 -e 'say "0".so'
False

$ ~/.rakudobrew/bin/perl6 -e 'say "0".so'
True

**Comment by vendethiel** [comment]
I'll just do it now, thanks!
