### ISSUE TITLE
Spelling error in bash doc

### ISSUE THREAD

**Issue by liamzebedee** [adambard/learnxinyminutes-docs#1104]
http://learnxinyminutes.com/docs/bash/

`echo "Scripts arguments seperated in different variables: $1 $2..."`

`s/seperated/separated`

:)

**Comment by levibostian** [comment]
Thanks! Mind making a pull request for us?

**Comment by liamzebedee** [comment]
haha already there @levibostian  :smile: #1105

**Comment by geoffliu** [comment]
@levibostian In the future, let's leave issues open until they're fixed in code.
