### ISSUE TITLE
[Request] SASS and LESS

### ISSUE THREAD

**Issue by augbog** [adambard/learnxinyminutes-docs#1112]
The power of preprocessors is simply too strong to ignore right now and everyone I know who works in frontend uses it. While the syntax is very similar, there are some syntax specific things that make SASS and LESS very powerful. 

Feel free to close if you do not think it's relevant.

**Comment by geoffliu** [comment]
Totally agree; I've wanted to write a page for SASS for a while now, I'll get around to it some day. :)

**Comment by paierlep** [comment]
I'll start and write a few lines about less

**Comment by voidabhi** [comment]
+1

**Comment by LauraNK** [comment]
I'll happily get started on a Sass tutorial!

**Comment by Oire** [comment]
Fixed.

**Comment by augbog** [comment]
Thank you guys :) 👍
