### ISSUE TITLE
Link to Groovy documentation dead

### ISSUE THREAD

**Issue by ereinecke** [adambard/learnxinyminutes-docs#1126]
The link to Groovy documentation points to Codehaus, which has shut down.

**Comment by vendethiel** [comment]
Nice catch! Mind sending a pull request with an updated link? :)

**Comment by ereinecke** [comment]
I’m not sure I did this correctly - I tried to use fork and pull.  Sorry, this is my first pull request, not sure whether or not this will show up in your repository.

**Comment by levibostian** [comment]
You did it correctly and I just merged it in.

Thank you very much!

Closing this.
