### ISSUE TITLE
Error in Perl6 sequences

### ISSUE THREAD

**Issue by czipperz** [adambard/learnxinyminutes-docs#1127]
Context:

    # You can use that in most places you'd expect, even assigning to an array  
    my @numbers = ^20;  
    my @seq =  3, 9 ... * > 95; # 3 9 15 21 27 [...] 81 87 93 99
    @numbers[5..*] = 3, 9 ... *; # even though the sequence is infinite,
                                 # only the 15 needed values will be calculated.
    say @numbers; #=> 0 1 2 3 4 3 9 15 21 [...] 81 87
                  # (only 20 values)

Isn't `my @seq = 3, 9 ... * > 95;` going to generate `99 105 111 117 ...`?

**Comment by vendethiel** [comment]
No, because you told perl6 to stop once it's "> 95"
Isn't that explained a bit before? How to explain this better?

**Comment by czipperz** [comment]
You should say something about the star being modified. **It is actually correct**, but confusing. Say something about how the star is being modified, not the list

**Comment by vendethiel** [comment]
I'm not sure what you mean by "star being modified"?
