### ISSUE TITLE
[nim] sugar assert

### ISSUE THREAD

**Issue by roudnev** [adambard/learnxinyminutes-docs#1140]
Should not 
`assert(amount > 0 or amount < 9000, "Crazy Sugar")`
actually read 
`assert(amount > 0 and amount < 9000, "Crazy Sugar")`
?

**Comment by levibostian** [comment]
Could you create a pull request for this?

**Comment by samcv** [comment]
Looks like this was merged over a year ago but the issue wasn't closed. Closing now.
