### ISSUE TITLE
Ruby logical operators

### ISSUE THREAD

**Issue by weaksauce** [adambard/learnxinyminutes-docs#1144]
The logical operators ```&&``` and ```||``` are for Boolean logic while the operators ```and``` and ```or``` are for control flow. They have a completely different precedence and will group things wrong if you use the ```and``` and ```or``` syntax without parenthesis. 

for a deeper explanation here:

http://devblog.avdi.org/2010/08/02/using-and-and-or-in-ruby/

**Comment by geoffliu** [comment]
Totally my fault. I don't actually know Ruby, but thought "hey, that's simple enough." :)
