### ISSUE TITLE
Use next() built-in for Python 3

### ISSUE THREAD

**Issue by wbolster** [adambard/learnxinyminutes-docs#1148]
The Python 3 page should use `next(iterator)` instead of `iterator.__next__()`. The `next()` function is a built-in which under the hood will call `x.__next__()`, but the latter is considered an implementation detail of the iterator protocol, while the `next()` function provides a public interface to advance an iterator.  (Similar for `len(x)` versus `x.__len__()`, and so on.)

**Comment by vendethiel** [comment]
Nice catch! Would you mind sending a pull request our way fixing that :-)?
