### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by eccstartup** [adambard/learnxinyminutes-docs#1155]
In [this](https://github.com/adambard/learnxinyminutes-docs/blob/master/perl6.html.markdown)

```
## It can also have optional arguments:
sub with-optional($arg?) { # the "?" marks the argument optional
  say "I might return `(Any)` if I don't have an argument passed,
      or I'll return my argument";
  $arg;
}
with-optional; # returns Any
with-optional(); # returns Any
with-optional(1); # returns 1
```

**Comment by vendethiel** [comment]
What's surprising, the Any part?

**Comment by eccstartup** [comment]
Yes, because everything returns `Any` here.

I want to know how `say` is used here.

**Comment by vendethiel** [comment]
the last expression in a block is returned. By default, the argument's value will be "Any", like in this case:

```
my $a; # $a is Any
```

**Comment by eccstartup** [comment]
It is returned, but is it printed(`say`ed)?

**Comment by vendethiel** [comment]
no, it's not, that's why the comment says "returns" :)

**Comment by eccstartup** [comment]
Well, how to check the `returned` value then?

**Comment by vendethiel** [comment]
you can call .perl on a type object (which is what `Any` is, a type), then `say` that.

**Comment by eccstartup** [comment]
OK. This `say` is a little bit confusing. Now I know it.

`say "I might return `(Any)` if I don't have an argument passed, or I'll return my argument";`

I thought it was like `printf` in C, which replaced `$arg` into `(Any)`.

Thanks @vendethiel

**Comment by vendethiel** [comment]
@eccstartup what should I change to make it clearer?

**Comment by eccstartup** [comment]
Some phases like you explained to me:

`the last expression in a block is returned. By default, the argument's value will be "Any", like in this case:`

Avoid using `(Any)` here.

**Comment by eccstartup** [comment]
I think this would be better. :)
