### ISSUE TITLE
(Common Lisp) Why p is T?

### ISSUE THREAD

**Issue by arzeth** [adambard/learnxinyminutes-docs#1157]
There is a line
```lisp
(dog-p *rover*) ; => t  ;; ewww)
```
in
```lisp
(defstruct dog name breed age)
(defparameter *rover*
    (make-dog :name "rover"
              :breed "collie"
              :age 5))
*rover* ; => #S(DOG :NAME "rover" :BREED "collie" :AGE 5)

(dog-p *rover*) ; => t  ;; ewww)
(dog-name *rover*) ; => "rover"
```
There are ```name```, ```breed```, ```age```, but there is no ```p``` in DOG. Why it returns T?

**Comment by vendethiel** [comment]
"-p" means "predicate". it's used to check if `*rover*` is an instance of `dog` -- which it is, so it returns true

**Comment by arzeth** [comment]
Thank you for the quick response! Now I understand it.

**Comment by vendethiel** [comment]
a guess a comment to clarify it would be nice :)

**Comment by thePsguy** [comment]
Yes! I'm creating a pull request with the said comment.
