### ISSUE TITLE
[Haskell] Better examples for $ operator

### ISSUE THREAD

**Issue by mathonsunday** [adambard/learnxinyminutes-docs#1161]
I find it hard to understand the $ operator because all the examples given evaluate to false. It would be better to have an example that showed how the placement of the $ operator would change what an expression evaluated to.

**Comment by levibostian** [comment]
Thanks @mathonsunday! If you know how to fix this, go ahead and make a PR and we will get it merged in. If not, we will hopefully get someone who knows Haskell to get this done. Thanks again!

**Comment by vendethiel** [comment]
just changed the wording -- does that make it clearer?

**Comment by mathonsunday** [comment]
It looks good to me. Thanks!
