### ISSUE TITLE
{learn c in y minutes } Variable Length Array

### ISSUE THREAD

**Issue by xerosanyam** [adambard/learnxinyminutes-docs#1170]
Here,
printf("Enter the array size: "); // ask the user for an array size
  char buf[0x100];
  fgets(buf, sizeof buf, stdin);

We are already giving the size of array buf.
0x100 in decimal implies 256, so the array is declared to be of size 256, then why are we calling it VLA ?

**Comment by thePsguy** [comment]
Fixing it and submitting a pull request.
