### ISSUE TITLE
column after "try"

### ISSUE THREAD

**Issue by blaiseli** [adambard/learnxinyminutes-docs#1171]
It seems that `try:` is incorrect syntax ("extra token").
Columns may need to be removed.

**Comment by vendethiel** [comment]
Which tutorial are you talking about?

**Comment by blaiseli** [comment]
Sorry, its the "Learn Julia in Y minutes" tutorial:
<http://learnxinyminutes.com/docs/julia/>
Some of the "try" statements there have extra columns.

**Comment by vendethiel** [comment]
Nice catch! Would you mind sending a pull request to fix those? :)

**Comment by vendethiel** [comment]
fixed in #1172
