### ISSUE TITLE
[c#/en] Get file refers to non-english version

### ISSUE THREAD

**Issue by thiagovandieten** [adambard/learnxinyminutes-docs#1176]
The page about C# links the "Get the code" part to here: http://learnxinyminutes.com/docs/files/LearnCSharp.cs
Could we get that fixed? :smile:

**Comment by vendethiel** [comment]
looks like we'll need the same fix as #684 if you don't mind sending a pull request :D.

**Comment by thiagovandieten** [comment]
Should be fixed in this commit: https://github.com/adambard/learnxinyminutes-docs/pull/1178
