### ISSUE TITLE
Add elvis operator 

### ISSUE THREAD

**Issue by panell** [adambard/learnxinyminutes-docs#1181]
someware after terrary operator

displayName = user.name ? user.name : 'Anonymous'   
displayName = user.name ?: 'Anonymous'

**Comment by levibostian** [comment]
What language is this for? 

If you don't mind, could you make a pull request for this issue? That would help a bunch. Thanks!

**Comment by panell** [comment]
groovy, done

______________________________________
Pozdrawiam / Regards,* Igor Wojda*, mobile: (+48) 693-594-924, http://www.
<http://www.voyda.eu/>voyda.eu <http://www.voyda.eu/> <igor@voyda.eu>

**Comment by panell** [comment]
groovy, done

**Comment by Ribeiro** [comment]
I´ve already made a PR for this and it´s already merged. Please, close the issue!  =)
