### ISSUE TITLE
two racket link in home page

### ISSUE THREAD

**Issue by geekplux** [adambard/learnxinyminutes-docs#1184]
I see the racket link twice in home page, is this a minor mistake? :)

**Comment by levibostian** [comment]
Racket is just that awesome of a language it deserves to be there twice. Haha just kidding! 

I just checked out the site, pushed up a change to master branch and should be fixed now. (We have to wait for the website to generate a change to the site. After that we can see if it's fixed or not.)

Thanks!!

**Comment by levibostian** [comment]
Hey it's fixed! Thanks again @geekplux

**Comment by geekplux** [comment]
fixed so quickly! thank you very much.
