### ISSUE TITLE
elixir question: all values will evaluate to true?

### ISSUE THREAD

**Issue by juanpastas** [adambard/learnxinyminutes-docs#1195]
```elixir
# Elixir also provides `||`, `&&` and `!` which accept arguments of any type.
# All values except `false` and `nil` will evaluate to true.
1 || true  #=> 1
false && 1 #=> false
nil && 20  #=> nil
!true #=> false
```

`# All values except `false` and `nil` will evaluate to true.` is `# All values except `false` and `nil` will evaluate to true when negated.`?

**Comment by vendethiel** [comment]
No, it means that `0` in, say, a "if" will evaluate to true, like Ruby, but contrarily to C.
