### ISSUE TITLE
Objectic C: classMethod

### ISSUE THREAD

**Issue by Echarnus** [adambard/learnxinyminutes-docs#1196]
+ (NSString *)classMethod
{
    return [[self alloc] init];
}

Altough the above works, it doesn't seem that of a good programming practice to return MyClass instead of a string. 

Not that experienced with Objective C. So perhaps something like this is done regularly?

**Comment by levibostian** [comment]
If you have some explanation behind why it is bad practice, then we can add that as a comment by this method explaining why it is bad practice. But until then, lets just assume it is ok practice to do so. Thanks for bringing this up!

**Comment by Echarnus** [comment]
Because someone who's calling that method expects it to return a string instead of MyClass and certainly doesn't expect this kind of behaviour. In some languages (I don't dare to say most as I don't know them all) this isn't even possible. 

In my opinion, a programmer should be able to know what he'll be receiving according to the definition of the method. Because a programmer can impossible figure out the logic of every method he's calling. Otherwise, using APIs will be fun when methods start returning other types than they mentioned (excluding the use of polymorphism of course). 

Then again, as I said before, not that experienced with Objective C as I'm mostly working with .Net.

**Comment by adambard** [comment]
Yeah man, th

**Comment by levibostian** [comment]
:+1: I get what you mean now @Echarnus. Sorry, I misunderstood. I was thinking you were talking about the implementation of ` [[self alloc] init]` from Apple instead of the code in the file. 

Thanks!
