### ISSUE TITLE
XML file (translation to pt-br) is not available on the site

### ISSUE THREAD

**Issue by miguelarauj1o** [adambard/learnxinyminutes-docs#1200]
Hey, #913 was merged into master, but I can't find the translated file in [website] (http://learnxinyminutes.com). Check out:

![screen shot 2015-08-14 at 11 06 50 am](https://cloud.githubusercontent.com/assets/7546651/9275662/0a749bf6-4275-11e5-8efc-7e456aa5de92.png)
 
The file exists in the [pt-br folder](https://github.com/adambard/learnxinyminutes-docs/tree/master/pt-br)

**Comment by adambard** [comment]
Whoops, sorry. Usually means something's up with the header and it's not getting indexed, I'll go fix it.

**Comment by adambard** [comment]
There was a tab character in the header! Blasphemy! Looks fixed now.
