### ISSUE TITLE
[c] Don't promote learncthehardway.com

### ISSUE THREAD

**Issue by modwizcode** [adambard/learnxinyminutes-docs#1207]
While I'm not an expert on C itself and cannot comment on the coding taught by learncthehardway.com. I can say that I've read a few critical articles with valid points, such as the author's constant fight against K&R, which could or could not be out of date, but the site gets oddly personal about it.

I don't think the statement about K&R C being a reference and being ancient should be in the tutorial page for C or the link to learncthehardway.com. I think that The links can be provided as alternate resources, but should be marked with a warning that they have not been verified for correctness.

I don't need to like K&R's book on C to say that learnxinyminutes isn't the right place to promote a book with some serious critiques against it's teachings.

**Comment by adambard** [comment]
I can see how this could get personal, but for what it's worth, my opinion is that K&R are not deities, and therefore there ought be no penalty for blasphemy against them. There's room for dissenting opinions to be presented, and I think both links ought to have a place.

That said, if you'd like to submit a PR rewording the blurb about K&R, feel free. Just keep in mind that, concerns of tone aside, it *is* an unusually old book for a programming language manual, it doesn't *necessarily* contain modern best practices, and I don't think it's unreasonable to mention as much.

**Comment by modwizcode** [comment]
No problem with having both. And I agree K&R c is pretty old for a programming book. I wish there was something I'd cite as a great proven modern c text but it seems like many have moved on.

**Comment by vendethiel** [comment]
Would be interested to get some arguments on this. Closing in the meantime.
