### ISSUE TITLE
Tcl guide throws errors

### ISSUE THREAD

**Issue by asfarley** [adambard/learnxinyminutes-docs#1211]
Line 116 throws errors if the guide is followed directly:
set greeting "Hello $people::person1::name"
can't read "people::person1::name": no such variable

Suggest swapping line 110 for this:
        variable name Neo

This is sort of touched on at line 136, but it's frustrating as a new user to encounter errors in tutorials without an immediate explanation.

**Comment by levibostian** [comment]
Could you please make a pull request with these changes so we can get them in and fixed? Thanks!

**Comment by asfarley** [comment]
Fixed.
