### ISSUE TITLE
Err in c++

### ISSUE THREAD

**Issue by xerosanyam** [adambard/learnxinyminutes-docs#1215]
```c++
#include<iostream>
namespace first{
	namespace nested{
		void foo(){
			std::cout<<"In first::nested::foo()"<<std::endl;
		}
	}
}
namespace Second{
	void foo(){
		std::cout<<"In second::foo()"<<std::endl;
	}
}
void foo(){
	std::cout<<"In ::foo()"<<std::endl;
}
int main(){
	using namespace Second;
	foo();
	return 0;
}
```

This gives following err

error: call of overloaded ‘foo()’ is ambiguous

**Comment by levibostian** [comment]
Do you know how to fix this issue? If you do, could you please make a pull request and we can get it into master?

**Comment by geoffliu** [comment]
https://github.com/adambard/learnxinyminutes-docs/commit/97b97408eab97fbe322df4266cda9ab2ed21fceb

@xerosanyam good catch! Fixed.
