### ISSUE TITLE
Err In C++

### ISSUE THREAD

**Issue by xerosanyam** [adambard/learnxinyminutes-docs#1216]
This code doesn't work as intended

using namespace std;

string foo = "I am foo";
string bar = "I am bar";

string& fooRef = foo; // This creates a reference to foo.
fooRef += ". Hi!"; // Modifies foo through the reference
cout << fooRef; // Prints "I am foo. Hi!"

// Doesn't reassign "fooRef". This is the same as "foo = bar", and
//   foo == "I am bar"
// after this line.
fooRef = bar;

**Comment by levibostian** [comment]
Do you know how to fix this issue? If you do, could you please make a pull request and we can get it into master?

Thanks by the way!

**Comment by geoffliu** [comment]
@xerosanyam Maybe I haven't had enough coffee yet, I don't see what's wrong with this piece of code. Could you elaborate?

**Comment by thePsguy** [comment]
// Doesn't reassign "fooRef". This is the same as "foo = bar", and
// foo == "I am bar"
// after this line.
cout << &fooRef << endl;  //CHECKING ADDRESS OF fooRef
fooRef = bar;
cout << &fooRef << endl;  //CHECKING ADDRESS OF fooRef, again
cout << fooRef;


OUTPUT:
I am foo. Hi!
0xbfdb6e18
0xbfdb6e18
I am bar

As you can see, the address remains the same in the output, so the code does work as expected.
I am creating a pull request to clarify with the addresses like this.
