### ISSUE TITLE
Perl 6: Results do not match for section on whatever star

### ISSUE THREAD

**Issue by hyperpape** [adambard/learnxinyminutes-docs#1235]
The document reads: 

    \#You can use that in most places you'd expect, even assigning to an array  
    my @numbers = ^20;  
    my @seq =  3, 9 ... * > 95; # 3 9 15 21 27 [...] 81 87 93 99
    @numbers[5..*] = 3, 9 ... *; # even though the sequence is infinite,
                             # only the 15 needed values will be calculated.
    say @numbers; #=> 0 1 2 3 4 3 9 15 21 [...] 81 87
                  # (only 20 values)

Running Rakudo * 2015.06 on Windows 7, I see different results

    > my @numbers = ^20
    0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
    > my @numbers[5..*] = 3, 9 ... *;

    > @numbers[5..*] = 3, 9 ... *;

     > say @numbers
     0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

**Comment by levibostian** [comment]
@vendethiel any idea on this one?

**Comment by vendethiel** [comment]
Yes, sorry. I've had it open on my phone, but I forgot to come back to it.

**Comment by vendethiel** [comment]
So, the answer is, the Great List Refactor went through, but you don't have it in your release. This month's release should "fix" that.
