### ISSUE TITLE
[ruby/en] Typo

### ISSUE THREAD

**Issue by tleb** [adambard/learnxinyminutes-docs#1237]
> Ruby implementations may have their own release version numbers, but they always target a specific version of MRI for **compatability**.

-> compatibility

**Comment by vendethiel** [comment]
Nice catch! Would you mind sending us a pull request to fix it :-)?

**Comment by tleb** [comment]
Will do on Saturday then. :)

**Comment by vendethiel** [comment]
Thanks! :+1:
