### ISSUE TITLE
[fsharp/fr] for French F#

### ISSUE THREAD

**Issue by aloisdg** [adambard/learnxinyminutes-docs#1245]
Hello,

I just began to translate the F# document.
You can follow my version on my [repo](https://github.com/aloisdg/learnxinyminutes-docs/blob/fsharp-fr/fr-fr/fsharp-fr.html.markdown).

Any help is welcome.

**Comment by vendethiel** [comment]
I'll just close this issue, PR whenever you feel it's ready to be reviewed :).

**Comment by aloisdg** [comment]
Sure. No problem.
