### ISSUE TITLE
[javascript] Possible mistake

### ISSUE THREAD

**Issue by nobitagit** [adambard/learnxinyminutes-docs#1248]
The following statement (line 475) appears to be a mistake. 

```js
if (0){
    // This code won't execute, because 0 is falsy.
}
if (Number(0)){
    // This code *will* execute, because Number(0) is truthy.
}
```

Neither block of code is actually executed (see [a test case here](https://repl.it/BKsz/1)) because `Number(0) == false`.

I can open a PR if you agree on removing this. Cheers.

**Comment by adambard** [comment]
I'd probably just take the `Number` example out, since who uses `Number`?

**Comment by portgasd666** [comment]
Shouldn't this be closed if it has been dealt with ?

**Comment by adambard** [comment]
For sure, thanks
