### ISSUE TITLE
Spanish version of the Julia tutorial not updated.

### ISSUE THREAD

**Issue by Ismael-VC** [adambard/learnxinyminutes-docs#1254]
@adambard I updated the Spanish version of the Julia tutorial since 14 Aug. The pull request was merged more than a month ago, only recently did I realized that the web site hasn't updated to my version, I don't know what else has to be done in order for the web site to reflect this change, please tell me if I did something wrong or if I still have to do something else, thanks!.

This is the PR:

* https://github.com/adambard/learnxinyminutes-docs/pull/1201

**Comment by levibostian** [comment]
Hmmm...sounds like the website generator is broken? @adambard, I am guessing this requires one of your magic quick fixes to get it working again?

**Comment by adambard** [comment]
Ah yes, looks like the `julia` syntax highlighting was the culprit as usual; rouge doesn't support it. I changed it back to ruby.

**Comment by Ismael-VC** [comment]
@levibostian @adambard thank you very much to both of you!
