### ISSUE TITLE
[Python]

### ISSUE THREAD

**Issue by rulanfuse** [adambard/learnxinyminutes-docs#1255]
In the section on **kwargs, the comment says:
```
# You can define functions that take a variable number of
# keyword args, as well, which will be interpreted as a map if you do not use **
```

But Python doesn't have maps. It would probably be better to write "dictionary" or "dict".

**Comment by levibostian** [comment]
I agree, it would be better to use a dictionary. Map makes me think of functional programming clojure like maps and I don't think that is what it is about. 

Mind making a pull request, please? For the Python 2 and 3 files both?

**Comment by adambard** [comment]
I fixed up Python 2, Python 3 doesn't seem to mention anything about maps in that spot at all, which is fine by me. Thanks!
