### ISSUE TITLE
Double listing swift

### ISSUE THREAD

**Issue by ian-bertolacci** [adambard/learnxinyminutes-docs#1256]
Swift appears to be listed twice on the main page.
The first link goes to the Turkish language version, the second to the English version.

The swift-tr.html.markdown file seems to be in the correct place (under tr-tr/)
It is however missing the ```lang: tr-tr``` found in the other tr-tr/ files.
Is that the issue?

**Comment by levibostian** [comment]
Yes that is an issue, fixed now. Thank you!!!
