### ISSUE TITLE
some LearnX.txt files are in incorrect language.

### ISSUE THREAD

**Issue by dougaitken** [adambard/learnxinyminutes-docs#1258]
e.g. when viewing git in English, the [txt](http://learnxinyminutes.com/docs/files/LearnGit.txt) file is in Portuguese.

(edited)

**Comment by levibostian** [comment]
That sounds like an issue with the site generator @adambard? I dont see anything wrong with the English git file.

**Comment by dougaitken** [comment]
True true, the file itself is fine, but must be how the english page is generated

**Comment by retbrown** [comment]
This seems to have been fixed as the text file is now in english

**Comment by dougaitken** [comment]
:+1:
