### ISSUE TITLE
Python irregularities on the site

### ISSUE THREAD

**Issue by katamaritaco** [adambard/learnxinyminutes-docs#1262]
![pythonge](https://cloud.githubusercontent.com/assets/1427530/10201978/59805194-6774-11e5-9af0-8056076cade9.png)
On the learnxinyminutes.com site, there are three entries for python: Python, Python3, and Python3. The first Python3 defaults to Czech, and contains ru-ru   zh-cn   tr-tr   es-es. There is no English entry. The second Python3 entry is the English entry, and doesn't contain other localizations. The English entry should be combined with the Czech entry, so there are only Python and Python3 entries.

I've placed an example below on what it looks like.

This is what the list looks like. I can post a photo later if it is still unclear.
python	tr-tr   fr-fr   ru-ru   de-de   zh-cn   es-es   pl-pl   pt-br   ko-kr   ro-ro  
python3	ru-ru   zh-cn   tr-tr   es-es  
python3

**Comment by katamaritaco** [comment]
![python](https://cloud.githubusercontent.com/assets/1427530/10201938/2a7eecfc-6774-11e5-9cd3-e2e034c07ff7.png)

**Comment by LiterallyElvis** [comment]
I have also observed this issue.

**Comment by levibostian** [comment]
Thank you. The Czech Python3 did not have the `lang:` header set which then resorted in it being considered an English file. 

Fixed in master, should be live on site soon after the site generator runs again. Thanks!
