### ISSUE TITLE
[Request] Elm

### ISSUE THREAD

**Issue by sotojuan** [adambard/learnxinyminutes-docs#1275]
Not so much a request because I want to help as well, but it would be cool to have one of these for [Elm](http://elm-lang.org).

**Comment by sotojuan** [comment]
Looks like there's already one [PR](https://github.com/adambard/learnxinyminutes-docs/pull/1164) for Elm actually. Anyone know what the status of it is?

**Comment by vendethiel** [comment]
No, but you can ping the author there :-).
