### ISSUE TITLE
Double XML in list

### ISSUE THREAD

**Issue by masterT** [adambard/learnxinyminutes-docs#1289]
**XML** appears two time in the list on the [website](http://learnxinyminutes.com/).

![proof](https://cloud.githubusercontent.com/assets/2584158/10248254/4c9e0632-68ec-11e5-8608-d76a6409b660.png)

Is it normal?

**Comment by thePsguy** [comment]
https://github.com/adambard/learnxinyminutes-site/
This is the repo for the site, but apparently it hasn't been updated in a long time. So, the current site is not exactly on github.

**Comment by masterT** [comment]
I just saw you opened an Issue on the website repo :+1: !

**Comment by thePsguy** [comment]
@masterT But that repo seems depreciated. Could you guide me as to where I could fix this issue, if at all I can?

**Comment by masterT** [comment]
I don't know, I was just looking around when I saw there were two XML link. 😐

**Comment by thePsguy** [comment]
Okay. I can fix it. Let's just wait for a repo manager/contributer to help with this..

**Comment by thePsguy** [comment]
@vendethiel could you please look into this? Is the website open source?
