### ISSUE TITLE
csharp - The expression for the ternary operator is not very clear

### ISSUE THREAD

**Issue by guntbert** [adambard/learnxinyminutes-docs#1333]
currently it reads

    string isTrue = (true) ? "True" : "False";

The `(true)` is not really clear, a simple comparing expression explains it better.

When I submit a Pull Request, should  I do that for every affected language (fr, de, cn, tr, es) separately or all in one go?

**Comment by thePsguy** [comment]
The Readme.md suggests separate pull requests for fixes in separate languages.

**Comment by guntbert** [comment]
@thePsguy Good, I'll make just the one for English now, and after approval/discussion the others follow.

- Does that sound sensible to you? 
- It should be possible to have the commit in a feature-branch but still create the pull-request towards master, right?
- Would it be useful to have this issue mentioned in the PR?

<sub>I am asking because this is my first Contribution on GitHub</sub>

**Comment by thePsguy** [comment]
-It is sensible, yes.
-Yes you can create changes in your branch and create pull requests.
-I myself am only 3 pull requests old, what is PR?

**Comment by guntbert** [comment]
Pull Request :-)

**Comment by thePsguy** [comment]
@guntbert, my bad! :D
If you mention the issue # in the description of the pull request, it gets mentioned here automatically! So it is useful in tracking issues.
