### ISSUE TITLE
[Perl 6] Feedback from a a person new to Perl 6

### ISSUE THREAD

**Issue by zoffixznet** [adambard/learnxinyminutes-docs#1390]
Hey,

Just some of my feedback for what I found confusing on the tutorial; I'm totally new to Perl 6:
### Content and Terms
- Currently [this](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1252) and [this](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1245) emit warnings about whitespace insignificance. Need to [quote](http://irclog.perlgeek.de/perl6/2015-10-09#i_11351195)
- [Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L377) is confusing, because first you create an "infinite" array, and then proceed to talk about using closure and length. What's the length of an infinite array? I tried running the code and it just sat there. The closure examples likely need something like `my @array = 1..20;` before them.
- [This](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L780) whole note should probably just be removed: It has virtually no value, even for Perl 5 programmers (me being one of them); it's superfluous in the context of a "quick Perl 6 tut"; and the tutorial doesn't actually explain what keyword `package` does, so mentioning at all is confusing.
- [Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L769), it's confusing by what is meant by `using packages directly`. Should it be worded `using "package" keyword directly`?
- [Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L875) it's not clear at all what `assert pre/post- condition` is. Maybe add an example? Or remove some phasers from the tut
- **fixed by #1434** ~~[This](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L659) makes me feel the implementation is broken or that I shouldn't be using inheritance. The line should either be removed or it should be briefly explained what exactly is the issue with inheritance.~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1247) `abc` => `ABC` for extra clarity~~
- **fixed by #1434** ~~Output [here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1225) should be `ae`~~
- **fixed by #1434** ~~[This](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1112) actually dies now with `Unable to deduce arithmetic or geometric sequence`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L176) `splat`?? No idea what that is. ~~I think it's `@` or `*@`. Check and add explanation.~~ ~~It's the `*` (from Ruby's term for an operator like that). Need to clarify in the docs~~
- **fixed by #1434** ~~I'd suggest removing `ENTER` from this line [here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L899), since `ENTER` phaser there is superfluous and the example confuses about the purpose of the `ENTER` phaser; makes you question what difference it provides there as opposed to plain `$db.start-transaction;`~~
- **fixed by #1434** ~~[This](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L873), [this](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L875), [this](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L876), [this](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1290), [this](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1292) (and one below it) lines are too long and get cut off~~
- **fixed by #1434** ~~Is `executed` the right term to use [here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L832)? Would `initialized` be clearer?~~
- **fixed by #1434** ~~[This](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L799) entire paragraph should be rewritten. It starts with `our...`, then mentions `my` even though it was just mentioned a few lines prior, then it mentions some `previous part`, which made me go `huh? wat?`~~
- **fixed by #1434** ~~[This](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L776) does not seem to be the case any longer. I get `Semicolon form of 'module' without 'unit' is illegal.  You probably want to use 'unit module'`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L78) ~~I've no idea what the `autoquoted => "key"` bit does. How does the auto-quotation mechanism work?~~ ~~I've just now realized that `autoquoted` is a name of a key and not a processing instruction. What confused me is that when I dumped the hash with `say %hash.perl;`, I got `{:autoquoted("key"), "some other" => "value"}`, which made me think `:autoquoted` was something special. The key `autoquoted` should be renamed to something more generic and easily recognizable; e.g `foo => "bar"`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/master/perl6.html.markdown#L99), that line should probably be moved all the way to [here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L166). In its current place it doesn't make much sense. Also, [here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L165), I'd change `capture` to `store in a variable`.~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L110) it's unclear what `Any` is. It's explained a few lines below, [here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L128), and I think some confusion can be avoided by moving explanation to earlier in the text.~~
- **fixed by #1434** ~~[This bit](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L383) is really confusing. I logged in to IRC to ask the channel, and then recalled Larry's talk about "magic" in list generation. It's not obvious how the values are generated in that sequence. It should be explained in the comments or use more obvious pattern, like `my @seq =  0, 5, 10 ...^ * > 100;`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L611) there seems to be 
  some confusion in the comments with `$*a` vs. `$*foo`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L620) the sentences about `$.` and `$!` seem broken and are confusing.~~
- **fixed by #1434** ~~[This](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L618) entire section seems to use term "fields" for class's attribute. Perl 6 [devs call](http://irclog.perlgeek.de/perl6/2015-10-08#i_11342695) them attributes and so do some other languages. It would be nice to have consistency in nomenclature.~~
### Typos
- **fixed by #1393** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/master/perl6.html.markdown#L135) `paramater` => `parameter`~~ 
- **fixed by #1393** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L200) `want is a copy` => `want a copy`~~
- **fixed by #1393** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L237) `languages` => `languages'`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L528) `examinate` => `examine`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L624) Opening `(` is not needed~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L754) `try` => `tried`~~
- **fixed by #1434** ~~[here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L766) `denomitor` => `denominator`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L860) `those that can have` => `those that can, have`~~
- **fixed by #1434** ~~Remove word `instead` [here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L865)~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L894): `trick` => `tricks`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1023) `not` => `no`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1057) `return` => `returns`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1055) `functions` => `function`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1092) `runs the an array with all these` => `returns an array with all of these`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1331) `argument` => `arguments`~~
- **fixed by #1434** ~~[Here](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L1349) `perl 6` => `perl6`~~

**Comment by vendethiel** [comment]
I have a hard time believing you're new to it... But thanks ;-).

**Comment by Ribeiro** [comment]
@vendethiel Me too !  =D

**Comment by zoffixznet** [comment]
@vendethiel @Ribeiro lol, I wonder what it is about me that makes that suspicious? :) I've been meaning to learn Perl 6 for a while, but never had the time. Learning now though.

As for the PR: I actually found more stuff (I'm midway through the tutorial right now). I'll keep adding what I find to the list above and when I'm done with the tutorial I'll make a PR for anything that I can fix :)

**Comment by vendethiel** [comment]
I've seen you on IRC pretty often

**Comment by Ribeiro** [comment]
@zoffixznet Please, keep up the good work since Perl seems like hieroglyphs to me  =D

**Comment by zoffixznet** [comment]
I'm finished. The few items that I werent able to answer in my PR (#1434) are the non-crossed out items at the top :)

**Comment by BenGoldberg1** [comment]
You're first item, a comment [about a possible misfeature](https://github.com/adambard/learnxinyminutes-docs/blame/5c677e8071291520297ef3d5d8374c6d11285744/perl6.html.markdown#L659) is because many peope believe that **multiple** inheritance is a bad thing, and that simply **having it in the langauge** is a bad thing.  There is of course nothing wrong with perl6's implementation of inheritance, nor in it's implementation of multiple inheritance.

**Comment by zoffixznet** [comment]
Thanks! I've updated the PR (removed the `misfeature` comment, since it's not really fitting for the context of a short, quickie tut).

**Comment by vendethiel** [comment]
ae9762fd13dc75113a8d64091181477510825819

----

> Here is confusing, because first you create an "infinite" array, and then proceed to talk about using closure and length. What's the length of an infinite array? I tried running the code and it just sat there. The closure examples likely need something like my @array = 1..20; before them.

This was added at some point:
```
# Note: if you try to do either of those with an infinite array,
#       you'll trigger an infinite loop (your program won't finish)
```

> This whole note should probably just be removed: It has virtually no value, even for Perl 5 programmers (me being one of them); it's superfluous in the context of a "quick Perl 6 tut"; and the tutorial doesn't actually explain what keyword package does, so mentioning at all is confusing.

Those were removed at a previous time

> Here, it's confusing by what is meant by using packages directly. Should it be worded using "package" keyword directly?

That was reworded at some point, but I changed it again.

> Here it's not clear at all what assert pre/post- condition is. Maybe add an example? Or remove some phasers from the tut

I added a (hopefully better) explanation.

----

@zoffixznet If you agree those are fixed, we can close this :-).

**Comment by zoffixznet** [comment]
Thanks!
