### ISSUE TITLE
[vimscript/en] Vimscript

### ISSUE THREAD

**Issue by Slava** [adambard/learnxinyminutes-docs#140]
Hello there,

Vimscript is not easy but from what I've heard it's pretty good dynamically typed language. 

I don't think a lot of people can invest time in learning vimscript [the hard way](http://learnvimscriptthehardway.stevelosh.com/), most people will not ever write any plugins. But it might be helpful on daily basis to know some basics of vimscript. Something enough to read vimscript code and fix small bugs, send pull requests, support comunity, etc.

**Comment by neoascetic** [comment]
:+1:

**Comment by golergka** [comment]
:+1:

**Comment by rstacruz** [comment]
https://github.com/rstacruz/cheatsheets/blob/gh-pages/vimscript.md might be a good place to start, it's not exactly fully-noob-friendly at the moment though.

**Comment by prertik** [comment]
Anybody want to work on this? Do people on this thread want to send a pull request?

**Comment by caminsha** [comment]
Hello

As I don't really know vimscript I want to get some insight. For me it would make sense (and help me) to translate the english version to german during the learn process.

Is the English version more or less complete so it could be translated? Or should I wait with the translation?

**Comment by mribeirodantas** [comment]
I'll close this issue as currently there is a vimscript document.
