### ISSUE TITLE
[bash/de] The translation is out of date

### ISSUE THREAD

**Issue by guntbert** [adambard/learnxinyminutes-docs#1452]
bash.html.markdown contains sections that are missing in the German version
- a lot about variables
- conditional execution
- redirection
- loops
- functions
- help
- man
- info

**Comment by guntbert** [comment]
Pull request is on the way - will be Work in Progress for a few days

**Comment by guntbert** [comment]
What is needed to get this on its way? I *think* my work should be done.

**Comment by vendethiel** [comment]
Seems fine from here. thanks

=> #1703 1453
