### ISSUE TITLE
Formatting issue with Haml docs

### ISSUE THREAD

**Issue by jritch** [adambard/learnxinyminutes-docs#1468]
[Screenshot of problem](https://cloud.githubusercontent.com/assets/2490406/10415405/727ea592-6fad-11e5-88d3-cdeaee3e4147.png)

There are two entries in the main index for the Haml docs - one points to the French language Haml doc, and the other to the English language version.

The French language doc is the one that has a link to the Spanish doc under translations.

**Comment by amrue** [comment]
This issue seems to have been resolved. Can we close this issue?
