### ISSUE TITLE
[julia] Respect coding standard

### ISSUE THREAD

**Issue by a-maze-d** [adambard/learnxinyminutes-docs#1483]
The tutorial is great, but the presented coding standard/guidelines are not reapected. Shouldn't camelCase be used for functions?

**Comment by vendethiel** [comment]
Sorry, which tutorial?

**Comment by a-maze-d** [comment]
The one for Julia, sorry. That one states that underscores are allowed, but
it's nor recommended and camelCase should be used

**Comment by JoaoGFarias** [comment]
@a-maze-d, you can mark this isse with the tag [Julia]; so people familiar with the language and article be more aware of this problem.

**Comment by a-maze-d** [comment]
Unfortunately I don't seem to be able to add a label to my post :-( So I modify the title to make it clearer :-)

**Comment by JoaoGFarias** [comment]
Change the title was what I meant :) I should have been more specific rsrs

**Comment by divayprakash** [comment]
Closed in #3256.
