### ISSUE TITLE
Request for RegEx

### ISSUE THREAD

**Issue by sanspace** [adambard/learnxinyminutes-docs#1561]
I'd like to add material on RegEx. However, I'm confused about how to represent it.

Almost all major languages support it. In which language, the material should be? Any suggestions?

**Comment by vendethiel** [comment]
Maybe you shouldn't show a specific language's implem, and only describe PCRE?

**Comment by ssd532** [comment]
I have created a PR for a brief PCRE reference (#1735). Please check. This is my first attempt to add a document. If it is acceptable, I will start improving it.

**Comment by sanspace** [comment]
PCRE does the job. Closing it.
