### ISSUE TITLE
Clarification needed on the style guide

### ISSUE THREAD

**Issue by duci9y** [adambard/learnxinyminutes-docs#1624]
The style guide says that lines in code blocks shouldn't exceed 80 characters in width. Does that mean the Markdown source should be at most 80 characters in width or that the lines in code blocks be at most 80 characters in width? Or both?

**Comment by adambard** [comment]
The lines in code blocks; all the markdown text is rendered as HTML and reflows automatically.

**Comment by divayprakash** [comment]
This should be added to the contribution guide.

**Comment by divayprakash** [comment]
Contribution guide is clear on the issue. Closing this accordingly.
