### ISSUE TITLE
Dont understand comments for Python site

### ISSUE THREAD

**Issue by kk21** [adambard/learnxinyminutes-docs#1948]
For http://learnxinyminutes.com/docs/python/,

I do not understand the following comments:
# You can define functions that take a variable number of
# positional args, which will be interpreted as a tuple if you do not use the *

# You can define functions that take a variable number of
# keyword args, as well, which will be interpreted as a dict if you do not use **

I am confused by "if you do not use the * / **". I think it makes sense if that portion is removed?

**Comment by adambard** [comment]
Yeah, those could probably be fine without. If you have time, you can submit a PR fixing that!

**Comment by aayushranaut** [comment]
@adambard Submitted PR.

**Comment by adambard** [comment]
Thanks for that, but there seems to be a conflict. Can you merge your PR with whatever is there now?

**Comment by adambard** [comment]
Also that's probably my fault for leaving it open, hit me up with @adambard when you do that so I can get right to it.

**Comment by aayushranaut** [comment]
Submitted PR https://github.com/adambard/learnxinyminutes-docs/pull/1963 @adambard
