### ISSUE TITLE
[markdown/en] 'Get The Code' links to French version.

### ISSUE THREAD

**Issue by ian-bertolacci** [adambard/learnxinyminutes-docs#2003]
This may be happening in other places, but the 'Get The Code' link in the English version of the tutorial goes to the French version.

**Comment by ian-bertolacci** [comment]
I should not that it does not happen in any of the other language versions of the Markdown tutorial. 
Only the english version.

**Comment by Gnomino** [comment]
This issue was fixed by 8b041236b5e378ae5fe0c9ccfd2a2bb6d08412a4

**Comment by ian-bertolacci** [comment]
Yep!!
