### ISSUE TITLE
[Request] 'Skills' section

### ISSUE THREAD

**Issue by ian-bertolacci** [adambard/learnxinyminutes-docs#2044]
I noticed the new "Statistical computing with Python" tutorial, but thought its placement under 'Languages' was an odd decision.

I think a better idea would be to place this under a 'Skills' or 'Techniques' section (there's probably a better name for this idea) that would be separate from the current 'Languages', 'Tools', etc. sections.

Its very possible that we might have a 'Frameworks' section as well. If someone was interested in the LLVM framework, I don't think that would go under tools, or languages.

Some thoughts.

**Comment by mribeirodantas** [comment]
It's been moved to **Tools** some time ago. I'll close this issue.
