### ISSUE TITLE
Ukrainian folder is messed up

### ISSUE THREAD

**Issue by Oire** [adambard/learnxinyminutes-docs#2045]
this is my big fault because I was absent for a long time, and now we are in big trouble.  
We have two Ukrainian folders (`uk-ua` and `ua-ua`) the former being correct. And we have files in both of them, and, more than that, some of them are the same.  
and, even worse, I will need to merge #1969 when it is ready.  
@adambard and other founders, SOS! I need help :(

**Comment by adambard** [comment]
Alright, everything is in uk-ua now. Not such big trouble :)
