### ISSUE TITLE
[PowerShell] Markdown not parsed correctly

### ISSUE THREAD

**Issue by abhineet97** [adambard/learnxinyminutes-docs#2048]
![screenshot 1](https://cloud.githubusercontent.com/assets/11965776/11571387/0c885900-9a22-11e5-9678-b992b9500e38.png)
The page on PowerShell on the [website] [1] appears broken when compared to the page on [Github] [2].
This is probably a Markdown parsing error. 

[1]: <http://learnxinyminutes.com/docs/powershell/>
[2]: <https://github.com/adambard/learnxinyminutes-docs/blob/master/powershell.html.markdown>

**Comment by adambard** [comment]
Fixed, thanks!
