### ISSUE TITLE
In clojure, list construction is not a synonym of quote

### ISSUE THREAD

**Issue by phs** [adambard/learnxinyminutes-docs#2061]
On https://learnxinyminutes.com/docs/clojure/:

```
; Also, (list 1 2 3) is the same as '(1 2 3)
```

This isn't generally true, and so is misleading.  (Quoting suppresses evaluation, the list constructor does not.)

**Comment by vendethiel** [comment]
I don't think the generally is meant to be read there... So if you have a better phrasing, it'd be nice to open a pull request, so that no one trips over it :)

**Comment by adambard** [comment]
Quoting is discussed earlier on, so it should be clear what is meant.
