### ISSUE TITLE
Two 'Markdown' articles appear on site

### ISSUE THREAD

**Issue by JoaoGFarias** [adambard/learnxinyminutes-docs#2070]
In [the site](https://learnxinyminutes.com/), one can find two links to Markdown articles; the first one leads you to a translation in CS-CZ

![two_mark](https://cloud.githubusercontent.com/assets/1585655/11915695/e3f09456-a699-11e5-98f7-080958bd6eae.jpg)

![two](https://cloud.githubusercontent.com/assets/1585655/11915696/e778a366-a699-11e5-9744-860b5bdf4eee.jpg)

**Comment by ian-bertolacci** [comment]
I see this happen from time to time.
Is because the language is not tagged on the english version?
Or is it something else?

**Comment by adambard** [comment]
Usually it means that someone forgot to tag a translation with the language and it ended up at the top level (thanks to our anglocentric implicit ordering)
