### ISSUE TITLE
[Perl6] Typo in "MAIN subroutime" header.

### ISSUE THREAD

**Issue by kentfredric** [adambard/learnxinyminutes-docs#2075]
Line 1333 should use the word "subrouti**n**e" not "subrouti**m**e"

> ```mkdn
### Extra: the MAIN subroutime
# The `MAIN` subroutine is called when you run a Perl 6 file directly.
```

**Comment by vendethiel** [comment]
Nice catch! Would you mind sending a PR with the fix :-)?
