### ISSUE TITLE
learnxinyminutes.com does not parse all text properly

### ISSUE THREAD

**Issue by JacobCWard** [adambard/learnxinyminutes-docs#2091]
The learnxinyminutes website does not seem to be rendering all of the markdown properly. Specifically toward the bottom of the entry for [markdown](https://learnxinyminutes.com/docs/markdown/). The page does, however, [render properly](https://github.com/adambard/learnxinyminutes-docs/blob/master/markdown.html.markdown) when parsed by GitHub

**Comment by ian-bertolacci** [comment]
First thought might be that the sites markdown parser cannot handle code blocks immediately after other text. Looking at the errors on the site, they all (seem) to be when there is a code block immediately after (with no extra line) a test line.
For example, line 299 has this issue, and is a code block immediately after a line, where as 307 does not have this issues and is a code block separated from the previous text by an extra line.
Odd issue though...

**Comment by adambard** [comment]
There are some differences between our markdown parser and github's, I guess. I've just fixed up the doc, should be live in a few.

**Comment by ian-bertolacci** [comment]
Looks like that worked.
