### ISSUE TITLE
vector::empty()

### ISSUE THREAD

**Issue by AndrejPetelin** [adambard/learnxinyminutes-docs#2122]
At the bottom of the C++ section:

```
// Following line sets size of v to 0, but destructors don't get called
// and resources aren't released!
v.empty();
v.push_back(Foo());  // New value is copied into the first Foo we inserted
```

In fact, v.empty(); doesn't set size of v to 0, it's a function that queries the vector whether it's empty, it returns a bool of true when it is and false when not. Did you, by any chance, mean
`v.clear();
`
?

**Comment by vendethiel** [comment]
Indeed! Didn't catch it :). Would you mind sending a pull request to fix it?

**Comment by AndrejPetelin** [comment]
Sure :)
