### ISSUE TITLE
[C++] "clear a container" issues

### ISSUE THREAD

**Issue by Kaosumaru** [adambard/learnxinyminutes-docs#2130]
This code & comments https://github.com/adambard/learnxinyminutes-docs/commit/a230d76307ecbc0f53c4b359cdb90628720f915e are very misleading. Author mixed up few things.

1. "empty" was called instead of "clear" (but that's already fixed)
2. "Following line sets size of v to 0, but destructors don't get called," that's untrue. Instead "Following line sets size of v to 0, but capacity of vector should remain unchanged". Destructors are called, but vector will retain allocated memory.
3. "v.swap(vector<Foo>());" would reduce capacity to 0, but it isn't valid - it shouldn't compile according to C++ standard. And since C++ 11, calling "v.shrink_to_fit();" is much better choice.

After this changes, code would be correct. But is it needed? Specifics of std::vector implementation and non-common usage seem bit out of place in introduction to language.

**Comment by geoffliu** [comment]
Agreed. Out of curiosity though, why doesn't `v.swap(vector())` compile? I've see that piece of code in a number of places.

**Comment by Kaosumaru** [comment]
Hi, it shouldn't compile because vector is a temporary object (a rvalue),
and according to standard, rvalues can only be bound to const lvalue
references or rvalue references. (AFAIK Visual Studio behaves differently,
it's sort of bug/weird feature, probably to be backward compatible with old
versions). And argument to swap must be a non-const lvalue reference.

It's same as:

const int& a = 1; //OK, const lvalue reference
int &&b = 2; //OK, rvalue reference
int& c = 3; //not OK, non-const lvalue reference

You can check it on clang or gcc here https://goo.gl/H5w9ne .

**Comment by vendethiel** [comment]
No, it makes perfect sense. Author probably "assumed" there was a rvalue reference and lvalue overloads.

**Comment by Kaosumaru** [comment]
Since `v.swap(vector<T>());` actually compiles on VS, it's easy to make that kind of mistake.

**Comment by geoffliu** [comment]
Ha, "author" being me. Totally my bad, I'll get that part cleaned up. The code I had in mind was a utility function I sometimes use that declared a vector and swapped with input arg. Got a bit sloppy when writing it up.
