### ISSUE TITLE
[c++/fr] Translation

### ISSUE THREAD

**Issue by Nairolf21** [adambard/learnxinyminutes-docs#2131]
Hi, 

I'm going to translate the c++ section, in French. 
Any suggestions ?

**Comment by vendethiel** [comment]
"Bonne chance".

Actually, there are some stuff that needs a fix right now in the C++ tutorial, so I'd recommend to hold off for now

**Comment by Nairolf21** [comment]
Ok, maybe I can help you if you need it. Do you talk about this issue : https://github.com/adambard/learnxinyminutes-docs/issues/2130 ?

**Comment by vendethiel** [comment]
Yes!

**Comment by aloisdg** [comment]
@Nairolf21 Feel free to ping me if you want a review of your translation. "Bon courage!"

**Comment by Nairwolf** [comment]
Hi, it's me @Nairolf21, I just changed my username. 

I haven't watch this tutorial recently, but I should be able to find some time in the next days to do that.

**Comment by Nairwolf** [comment]
Badly, I will not have time to do that, so, the tasks is free now. If someone wants to do it, he can !

**Comment by aloisdg** [comment]
@vendethiel It would be nice to add a `up-for-grabs` label to the [label-list](https://github.com/adambard/learnxinyminutes-docs/labels/).

**Comment by vendethiel** [comment]
@adambard should we add such labels? (assigned / unassigned)

**Comment by aloisdg** [comment]
I think [`up-for-grabs`](http://up-for-grabs.net/#/) is more explicit.

**Comment by adambard** [comment]
Why not both?
