### ISSUE TITLE
[1..]

### ISSUE THREAD

**Issue by Ingo60** [adambard/learnxinyminutes-docs#2132]
[1..] is not the list of natural numbers, since 0 is missing. You probably mean positive numbers.

**Comment by vendethiel** [comment]
Sorry, which language is that? Knowing you work on Frege, probably Haskell?

**Comment by Ingo60** [comment]
Sorry, missed that out. Yes, yo're right.

2016-02-13 3:53 GMT+01:00 ven <notifications@github.com>:

**Comment by geoffliu** [comment]
The definition of natural numbers may differ depending on the author. Some include 0,others don't. I never really mind which definition to use since the two sets are isomorphic.

**Comment by adambard** [comment]
I would merge a PR changing it to "whole numbers" if anyone could be bothered, but @geoffliu seems to be on the nose with that. Besides, nobody is going to expect [1..10] to contain 0 -- there are surely way more dire errors scattered about the site. Thanks for the feedback (and your work on Frege) though!
