### ISSUE TITLE
[swift/en] Explain `if let` structure

### ISSUE THREAD

**Issue by gprasant** [adambard/learnxinyminutes-docs#2145]
The document for swift says 
```
if let someOptionalStringConstant = someOptionalString {
    // has `Some` value, non-nil
    if !someOptionalStringConstant.hasPrefix("ok") {
        // does not have the prefix
    }
}
```

Without explaining what `if let` does. Add comments about what the `if let` structure does

**Comment by adambard** [comment]
I don't know that it's a separate structure, it's just a `let` inside an `if`. Analogous to something like this in C:

```c
int myInt;
if((myInt = someFunctionReturningInt()) == 0){
  // myInt is 0
}
```

**Comment by gprasant** [comment]
I didn't know that the RHS was being unwrapped till I dug into it. This would be helpful in comments 
```
// If let is a special structure in Swift that allows you to check if an Optional holds a value, and in case it does – do something with the unwrapped value
```

Courtesy : http://www.touch-code-magazine.com/swift-optionals-use-let/

**Comment by gprasant** [comment]
I can submit a  PR for this . Should be quick and easy.

**Comment by vendethiel** [comment]
Please do :) !

**Comment by adambard** [comment]
Done!
