### ISSUE TITLE
[markdown/en] Get the code file is in Czech for the English page.

### ISSUE THREAD

**Issue by ryanmavilia** [adambard/learnxinyminutes-docs#2146]
This may have been said already and I couldn't find the issue, but on this [page](https://learnxinyminutes.com/docs/markdown/) if you go to "Get the code: [markdown.md](https://learnxinyminutes.com/docs/files/markdown.md)" it links to a file which I believe is in Czech even though it is the English page.

**Comment by adambard** [comment]
Yup, Czech. Should be fixed in the next auto-rebuild, thanks!
