### ISSUE TITLE
[asymptotic-notation/pt-br] Brazilian Portuguese shows up as a separate article

### ISSUE THREAD

**Issue by devinmcginty** [adambard/learnxinyminutes-docs#2182]
The Asymptotic Notation tutorial currently shows up on the main page twice: once for the English page and another for the Brazilian Portuguese page. The pt-br page should display as a translation.

**Comment by geoffliu** [comment]
Hmm @adambard any ideas? I'm reading middleman code, it seems like this should be working.

**Comment by adambard** [comment]
Hmm, looks like my auto-rebuilding cron job hasn't been doing its... job. I just ran it manually, seems to be fixed!

**Comment by vendethiel** [comment]
Nice :)
