### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by divayprakash** [adambard/learnxinyminutes-docs#2185]
I noticed this file `r.html.markdown~` in the repository. Normally, such files are not added to a commit because they are ignored in accordance with a `.gitignore` file. I'm willing to work on adding such a file, just need the green flag.
@vendethiel @adambard

**Comment by vendethiel** [comment]
LGTM :).

**Comment by divayprakash** [comment]
Ok so I'll make a PR sometime today

**Comment by geoffliu** [comment]
Wait why are we adding a `.gitignore`? It is the developers' responsibility to not check in any byproducts from their development process. Usually this is done with a global config. We cannot not possibly list all the files future contributors might want excluded.

**Comment by geoffliu** [comment]
https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by divayprakash** [comment]
@geoffliu 
> It is the developers' responsibility to not check in any byproducts from their development process. >We cannot not possibly list all the files future contributors might want excluded

You're absolutely right about that, however I think this can only help as it'll filter out unnecessary files created by text editors like `r.html.markdown~`.

**Comment by divayprakash** [comment]
@geoffliu 
Check this one out, I've configured `.gitignore` such that all files except
```mardown
.markdown
.md
.erb
.csv
```
willl be ignored. This is in accordance with the file types present in the repository.

**Comment by geoffliu** [comment]
@vendethiel What do you think? Personally, I've made more mistakes by not including files than including extra files. The latter is easy to notice and easier to fix. I really think we're over-reacting to a one-time mistake.

**Comment by vendethiel** [comment]
Such a gitignore will *not* work. Some tutorials use their language's extension, and we want to keep that open. Adding a few entries (`*~` and probably `#*#`) that we **know** we don't want is the way to go.

**Comment by divayprakash** [comment]
@vendethiel How about now?

**Comment by divayprakash** [comment]
@vendethiel  How about now?

**Comment by divayprakash** [comment]
Closed in #2190
