### ISSUE TITLE
"size" variable defined twice on 'C' page

### ISSUE THREAD

**Issue by ryebr3ad** [adambard/learnxinyminutes-docs#2205]
The variable named 'size' is defined twice -- once as the type 'size_of' and once as the type 'int'.  If copied directly, this causes a conflict.

**Comment by vendethiel** [comment]
Nice catch! Would you mind sending us a pull request to fix this?

**Comment by ryebr3ad** [comment]
I can.  I'll submit a pull request this evening.

**Comment by vendethiel** [comment]
nice :+1:

**Comment by vendethiel** [comment]
#2206
