### ISSUE TITLE
[CommonLisp/zh] Maybe we can add ANSI Common Lisp

### ISSUE THREAD

**Issue by alisvlouis** [adambard/learnxinyminutes-docs#2210]
_ANSI Common Lisp_(ACL) is also a book. _Practical Common Lisp_'s Chinese translation is not so good, so I suggest Chinese readers reading ACL(available on http://acl.readthedocs.org/en/latest/, both zh-CN and zh-TW).

**Comment by adambard** [comment]
Sure, do you mind making a Pull request for that?

**Comment by geoffliu** [comment]
Fixed in #2211
