### ISSUE TITLE
Function example R language in zh-cn version

### ISSUE THREAD

**Issue by Yxshang** [adambard/learnxinyminutes-docs#2218]
In the zh-cn version of R language, it gives a function example
jiggle <- function(x) {
    x + rnorm(x, sd=.1) #add in a bit of (controlled) noise
    return(x)
}

But in fact, the function should be defined as:
{
   x = x + rnorm(1, sd=.1) #update x with one random number
   return(x)
}

**Comment by vendethiel** [comment]
good catch! would you mind sending us a pull request to fix it?

**Comment by Yxshang** [comment]
Yes of course. 
I'm still learning github and i think i can do this in the late May. Is that ok?

**Comment by vendethiel** [comment]
No rush :-).

**Comment by vendethiel** [comment]
You can also edit via the web interface, if that's easier for you.
