### ISSUE TITLE
Deploy current version

### ISSUE THREAD

**Issue by robinpokorny** [adambard/learnxinyminutes-docs#2231]
There were some updates recently and they are not deployed on the live site.

I could find if there is an automated way to trigger deploying the site.

**Comment by robochat** [comment]
When was the site last updated?

**Comment by vendethiel** [comment]
Probably a metadata error. I don't have the error log though... Maybe @adambard can help?

**Comment by robochat** [comment]
It looks to me like the site hasn't been updated since the end of May.

**Comment by ian-bertolacci** [comment]
I think this is still in effect. There exists a [fortran95 markdown](https://github.com/adambard/learnxinyminutes-docs/blob/master/fortran95.html.markdown) that should be on the site that is not.

IIRC The site updates are not automatic?

**Comment by vendethiel** [comment]
> IIRC The site updates are not automatic?

they are. unless some md is borked.

**Comment by ian-bertolacci** [comment]
Ok. I might be misremembering someone saying "Ya I have to push these by hand every now and again". Maybe that Markdown is borked, I havent taken a look.

**Comment by robochat** [comment]
Is @adambard the only one who can fix this?

**Comment by adambard** [comment]
The problem was a typical one -- rouge has no fortran support so it was choking on that when requested (it's a middleman thing). I just removed highlighting and it worked ok. There was also a duplicate dutch markdown translation that was causing build errors for some reason which I removed.

Thanks for the heads up!
