### ISSUE TITLE
[r/en] read.csv does not work for the url

### ISSUE THREAD

**Issue by phsamuel** [adambard/learnxinyminutes-docs#2236]
I got error running 

pets <- read.csv("http://learnxinyminutes.com/docs/pets.csv")

and the error message is 

Error in file(file, "rt"): cannot open the connection

I am running R 3.2.5 on Ubuntu 14.04

However, 

library(curl)
pets <- read.csv(curl("http://learnxinyminutes.com/docs/pets.csv"))

is fine

**Comment by aloisdg** [comment]
Also, you may use

```R
require(RCurl)
pets <- read.csv(textConnection(getURL("http://learnxinyminutes.com/docs/pets.csv")))
```
source [1](https://cran.r-project.org/doc/manuals/R-data.html#index-read_002ecsv) [2](https://en.wikibooks.org/wiki/R_Programming/Importing_and_exporting_data#Google_Spread_Sheets)

Well, can you submit a PR?
