### ISSUE TITLE
Hello , there are few mistakes in 'learn livescript in y minutes'

### ISSUE THREAD

**Issue by a20185** [adambard/learnxinyminutes-docs#2239]
Hello , there are few mistakes in 'learn livescript in y minutes'
in the current version , there are some aliases like 
`'abc-def-x'`
where x stands for a number.
in livescript it's a *_forbidden usage *_ of such variables,
please fix it in case it may confuse the possible new learners , thanks a lot!

**Comment by vendethiel** [comment]
could you please send a pull request to fix it? Would be really appreciated, thanks :)
