### ISSUE TITLE
80 character margin recommended, but 70 character margin displayed

### ISSUE THREAD

**Issue by sshine** [adambard/learnxinyminutes-docs#2241]
The guide suggests staying within an 80 character marging, but at some point later, the margin in the stylesheet was restricted down to 70 characters. This causes lines to wrap in unintended ways, e.g. as seen on [ocaml](https://learnxinyminutes.com/docs/ocaml/) or [standard ml](https://learnxinyminutes.com/docs/standard-ml/). I don't know if 70 is universal, or if it differs based on whatever monospace font is being used.

Either the guide should be updated to recommend another lower number than 80, or the stylesheet should be adjusted to avoid line wrapping at less than 80 characters.

**Comment by NPrescott** [comment]
[Issue with the site repository](https://github.com/adambard/learnxinyminutes-site/issues/31) (which contains the stylesheets)

**Comment by sshine** [comment]
Since the issue was raised in the appropriate tracker, I'm closing it here.
