### ISSUE TITLE
Incrementing/Decrementing Operator Bug in C#

### ISSUE THREAD

**Issue by pyskell** [adambard/learnxinyminutes-docs#2248]
Sorry, don't have a dev environment setup so don't have anything to push but the current i++/--i approach doesn't print out what it says it does.

Should preferably be something like:

            int i = 1;
            Console.WriteLine("\n->Inc/Dec-rementation");
            Console.WriteLine(i++); //i = 1. Get i then increment.
            Console.WriteLine(i);   //i = 2. Incremented i.
            Console.WriteLine(++i); //i = 3. Increment i then get.
            Console.WriteLine(i--); //i = 3. Get i then decrement.
            Console.WriteLine(i);   //i = 2. Decremented i.
            Console.WriteLine(--i); //i = 1. Decrement i then get.

**Comment by adambard** [comment]
I think ef486c21197c30d39399f695bb5414b50ef6c4ac addresses this acceptably.
