### ISSUE TITLE
Git pull --rebase description

### ISSUE THREAD

**Issue by danijar** [adambard/learnxinyminutes-docs#2258]
The `git pull --rebase` description reads like this. However, it actually performs `git fetch <remote> <branch>, git rebase <remote>/<branch>` instead.

```
# Merge in changes from remote branch and rebase
# branch commits onto your local repo, like: "git pull <remote> <branch>, git 
# rebase <branch>"
```

**Comment by vendethiel** [comment]
Good catch! Would you mind selling a Pull Request to fix  this?

**Comment by danijar** [comment]
Sure, I can do it later.

**Comment by danijar** [comment]
I can do a pull request for the English version. Would we have to do this for every language?

**Comment by vendethiel** [comment]
no, the other versions can be updated later by their translator.
