### ISSUE TITLE
Nix link is a 404

### ISSUE THREAD

**Issue by chris-martin** [adambard/learnxinyminutes-docs#2259]
The nix link https://learnxinyminutes.com/docs/nix/ is a 404. As I just submitted this new page (#2168), I assume this is my fault, but I don't know what I did wrong :frowning:

**Comment by adambard** [comment]
Forgot to take out the `nix` highlighting; if the site generator doesn't have a lexer for a given language, it crashes out generating that page, and [the version of] rouge [that we use] doesn't have a lexer for nix.

**Comment by chris-martin** [comment]
Ah, thanks.

Related rouge issues:
* https://github.com/jneen/rouge/issues/345
* https://github.com/jneen/rouge/issues/406
