### ISSUE TITLE
[perl6/en] triple pound signs meta note is confusing

### ISSUE THREAD

**Issue by DanBealeCocks** [adambard/learnxinyminutes-docs#2271]
> Meta-note : the triple pound signs are here to denote headlines, double paragraphs, and single notes.

Please consider re-wording this to something like:

Meta-note: the triple pound signs (###) are here to denote headlines. Double pound signs (##) denote paragraphs. Single pound signs (#) denote notes.

**Comment by vendethiel** [comment]
Basically, showing what "triple pounds" mean?
That seems fine by me. Would you mind sending a PR with that addition?

**Comment by Oire** [comment]
Closed via #2877.
