### ISSUE TITLE
Elm improvements

### ISSUE THREAD

**Issue by Mouvedia** [adambard/learnxinyminutes-docs#2279]
- https://github.com/adambard/learnxinyminutes-docs/commit/4aca8f16dfec1a9341648b0ff1724ada01cdc2b0#commitcomment-17837123
- https://github.com/adambard/learnxinyminutes-docs/commit/4aca8f16dfec1a9341648b0ff1724ada01cdc2b0#commitcomment-17837162
- https://github.com/adambard/learnxinyminutes-docs/commit/d75d8e133a5d7d2e23c7afc1ea16ec68db61cff7#commitcomment-17837175
- add an example for destructuring records

**Comment by divayprakash** [comment]
Has already been fixed.
