### ISSUE TITLE
[svn/en] Adding Subversion Tutorial

### ISSUE THREAD

**Issue by wboka** [adambard/learnxinyminutes-docs#2280]
I'm going to add a subversion tutorial to supplement the current version control systems.

**Comment by aloisdg** [comment]
Can you add a link to your work please?

**Comment by wboka** [comment]
@aloisdg Here's what I have so far. [Link to the file in my repo](https://github.com/wboka/learnxinyminutes-docs/blob/master/svn.html.markdown). I'm looking to have a good working session this weekend to wrap up a pull request to the main repo.

**Comment by vendethiel** [comment]
Closing, feel free to PR whenever.

**Comment by srinidhibs** [comment]
May I know what happened to this issue? Looks like the `svn.html.markdown` file is no longer available in the fork of @wboka.

**Comment by wboka** [comment]
Honestly with the popularity of Git, I stoppped working on it almost immediately. Feel free to start a page if you want.
