### ISSUE TITLE
[C] Incorrect information regarding size of char type in c

### ISSUE THREAD

**Issue by FFrankNewman** [adambard/learnxinyminutes-docs#2287]
Line 69 of the C tutorial states:
```
// chars are guaranteed to be 1 byte
char x_char = 0;
char y_char = 'y'; // Char literals are quoted with ''
```

This is false.  Please see section 6.2.5, Types, of the ISO C11 standard.  No guarantees are made about the exact size of char, only the following:

> An object declared as type char is large enough to store any member of the basic execution character set. If a member of the basic execution character set is stored in a char object, its value is guaranteed to be nonnegative. If any other character is stored in a char object, the resulting value is implementation-defined but shall be within the range of values that can be represented in that type.

**Comment by vendethiel** [comment]
Here is the legalese you're looking for:

§6.5.3.4: (which describes `sizeof`)

> When applied to an operand that has type char, unsigned char, or signed char, (or a qualified version thereof) the result is 1.
 > ...
> operator yields the size (in bytes) of its operand
