### ISSUE TITLE
What's the "real way" to access the elements of a tuple?

### ISSUE THREAD

**Issue by willnwhite** [adambard/learnxinyminutes-docs#2295]
> -- Access the elements of a pair with the first and second functions.
> -- (This is a shortcut; we'll come to the "real way" in a bit.)
> fst ("elm", 42) -- "elm"
> snd ("elm", 42) -- 42

**Comment by vendethiel** [comment]
It's a bit below:

```
-- You can pattern match in function definitions when there's only one case.
-- This function takes one tuple rather than two arguments.
```

But I'm gonna go ahead and add a note about that :).
