### ISSUE TITLE
Romanian translation for bf and haskell missing

### ISSUE THREAD

**Issue by petru-dimitriu** [adambard/learnxinyminutes-docs#2299]
Hi. I wrote a translation to Romanian for brainf*ck and haskell some time ago but I haven't ever seen them live. I also wrote a translation for latex which did get uploaded. I was wondering if I did something wrong with the former two that prevented them from getting uploaded.

**Comment by vendethiel** [comment]
It might be in the list or PRs in the backlog still. We had around 200+ PRs 2 weeks, and we got that down to <100, but there are a few left to be processed. I'll try to find the PRs when I get on my computer (or feel free to ping me there). It might also be merged but with incorrect metadata. Sorry for the delay :).

**Comment by vendethiel** [comment]
Not sure why haskell-ro isn't showing up... @adambard ?

The bf metadata was wrong, I should've fixed it.

**Comment by petru-dimitriu** [comment]
I was suspecting something must be wrong with the metadata!

**Comment by samcv** [comment]
This issue should be closed I think.

These two both show up now:
https://learnxinyminutes.com/docs/ro-ro/bf-ro/

https://learnxinyminutes.com/docs/ro-ro/haskell-ro/
