### ISSUE TITLE
[Red] reformat the comments so the sentences don't have weird linebreaks

### ISSUE THREAD

**Issue by JobLeonard** [adambard/learnxinyminutes-docs#2303]
I guess the document was written with a standard 80-char limit, but the website uses a smaller width it seems:

![image](https://cloud.githubusercontent.com/assets/259840/16707609/2a666250-45d5-11e6-9441-d040603aae32.png)

Willing to do this myself if everyone else is ok with changing it - it's just a matter of choosing a smaller max-character limit and reformatting the comments to fit.

**Comment by vendethiel** [comment]
Mmh, we need to fix this globally ...

**Comment by JobLeonard** [comment]
Ah, is the issue the website itself you mean?

**Comment by vendethiel** [comment]
I'm afraid we'll see it popping it everywhere ... @adambard could that be the case or is it an isolated case?

**Comment by JobLeonard** [comment]
Hmm... could it be that my computer uses a slightly wider fallback font? I'm running Linux. I just checked Python, R and Go and they all have this issue on my laptop too:

![image](https://cloud.githubusercontent.com/assets/259840/16726200/50dcff20-475b-11e6-95b1-5ddb160cdbd8.png)

![image](https://cloud.githubusercontent.com/assets/259840/16726239/7f91947a-475b-11e6-9e8a-efb8c61145f1.png)

![image](https://cloud.githubusercontent.com/assets/259840/16726251/8c309f82-475b-11e6-8aa6-d1616dec8f88.png)

**Comment by samcv** [comment]
I have seen this in the [perl6] doc I have been working on.  If I generate the site locally then the width shows fine in both Firefox and Chrome.  On learnxinyminutes.com though the text is larger and the lines don't fit properly...  @adambard ?

**Comment by robochat** [comment]
#2552

**Comment by samcv** [comment]
Should be fixed by #2552.  Thanks! Reopen if there's still issues.
