### ISSUE TITLE
Update Swift page for v3.0

### ISSUE THREAD

**Issue by GreaseMonk** [adambard/learnxinyminutes-docs#2306]
integers are no longer  i--, should be i -= 1
some are already updated, but there still are a couple of old pieces.

**Comment by vendethiel** [comment]
You're right, good catch. Would you mind sending a PR to fix those? :-)

**Comment by JustBlah** [comment]
@vendethiel this one could be closed.

**Comment by vendethiel** [comment]
Nice catch!
