### ISSUE TITLE
[Objective/C-en] Last commit seems to have a typo

### ISSUE THREAD

**Issue by giria** [adambard/learnxinyminutes-docs#2308]
Last commit (commit 1311f4dbb29085167248e8a746b27a5e1bee7459) seems to have a typo on line 23:
`+#pragma mark Navigation Functions // New tag o@"Third number = %@", thirdNumber); // prin jump bar named 'Navigation `

Obviously should be:
`+#pragma mark Navigation Functions //print jump bar named 'Navigation Functions'`
without the middle gibberish.

**Comment by vendethiel** [comment]
Whoops, my bad...
