### ISSUE TITLE
[zfs/en] Un-ordered lists not rendering properly

### ISSUE THREAD

**Issue by colemannugent** [adambard/learnxinyminutes-docs#2313]
It looks like all the lists in this article are not being converted to HTML on the website. They render as if they were not markdown. Now the funny thing is that if you look at the markdown files here on GitHub they render correctly. I'm not sure what's going on here, but it seems to be some difference in the way the site renders markdown to HTML.

For example parts of the article render as:

`Actions: * Create * List * Rename * Delete * Get/Set properties`

which should render as:

Actions: 
- Create 
- List
- Rename
- Delete
- Get/Set properties

~Coleman

**Comment by vendethiel** [comment]
We don't use github's markdown flavour

**Comment by colemannugent** [comment]
GitHub style Markdown un-ordered lists seem to work just fine when they are at the end of articles such as `sass.html.markdown` and `python3.html.markdown`. Specifically what markdown flavor are you using? I can't seem to find that info in any part of `CONTRIBUTING.markdown`.
~Coleman

**Comment by vendethiel** [comment]
[Redcarpet](https://github.com/adambard/learnxinyminutes-site/blob/master/config.rb#L4)

(actually, a modified version IIRC)

**Comment by colemannugent** [comment]
I thought GitHub used Redcarpet as well? Just about every different flavor of markdown that I've seen accepts `*, +, -` for denoting lists. Anyway, I'm still curious as to what the correct syntax would be for this article, as I could fix it and submit a PR. This really is a great summary of ZFS, but it could use a bit of readability improvements.
~Coleman

**Comment by Oire** [comment]
Closed via #2876.
