### ISSUE TITLE
incorrect set synthax

### ISSUE THREAD

**Issue by wdecoster** [adambard/learnxinyminutes-docs#2319]
Concerning "learning Julia in Y minutes".

Thanks for the interesting introduction to Julia. While following along, I noticed an error with:
`setdiff(Set(1,2,3,4),Set(2,3,5)) # => Set{Int64}(1,4)`
I assume this should be: `setdiff(Set([1,2,3,4]),Set([2,3,5]))`

Cheers!

**Comment by wdecoster** [comment]
In addition, the synthax for creating a dictionary is apparantly deprecated, should use Dict("dog"=>"mammal","cat"=>"mammal","mouse"=>"mammal") instead of ["dog"=>"mammal","cat"=>"mammal","mouse"=>"mammal"]

**Comment by vendethiel** [comment]
Julia certainly changes fast... PR welcomed :)!
