### ISSUE TITLE
[Proposal] Scrum section?

### ISSUE THREAD

**Issue by JoaoGFarias** [adambard/learnxinyminutes-docs#2326]
Given the release of the updated [Scrum Guide](http://www.scrumguides.org/scrum-guide.html) last month, after three years, - and the [87% of people using believe improves work life quality](https://www.scrumalliance.org/landing-pages/2015-state-of-scrum-report-download) - I think it would be nice to have a section about Scrum.

I know development methodologies are a bit off-topic, but given the Scrum Guide is quite comprehensive, yet concise, the topic can become a page, with links for more detailed information. 

What are your thoughts?

**Comment by samcv** [comment]
I think this would be a great idea. Would you be interested in writing one? 🌠

**Comment by JoaoGFarias** [comment]
Sure thing @samcv.
As soon as I have a scratch, I will send a PR (with WIP notice) to get feedback.
