### ISSUE TITLE
Renew SSL Certificate before Feb 9th

### ISSUE THREAD

**Issue by IvanFon** [adambard/learnxinyminutes-docs#2329]
It appears that the website certificate expired. I get a warning about it every time I visit the website.

**Comment by geoffliu** [comment]
Hmm I don't see any warning. Is your system clock correct?

**Comment by SirSharpest** [comment]
Can you give some browser information, and can you try viewing in another
browser with no addons.

Also some more information on what the error says exactly

**Comment by samcv** [comment]
Older ticket but I just checked and the site's cert is currently valid... although it expires in about 24 hours.
@adambard can you make sure it gets reissued?

**Comment by daleathan** [comment]
![2016-11-12 08_21_58-insecure connection](https://cloud.githubusercontent.com/assets/1161914/20230667/307b1f48-a8b1-11e6-8069-867d4147d89e.png)

**Comment by samcv** [comment]
Sent an email to Adam, hopefully this can be fixed soon.

**Comment by adambard** [comment]
Fixed for now, see y'all in 90 days!

**Comment by divayprakash** [comment]
Closing as this has been fixed.
