### ISSUE TITLE
[Julia/en] Deprecated syntax with Dictionary example

### ISSUE THREAD

**Issue by kapilspawar** [adambard/learnxinyminutes-docs#2330]
julia> filled_dict = ["one"=> 1, "two"=> 2, "three"=> 3]

**WARNING: deprecated syntax "[a=>b, ...]".
Use "Dict(a=>b, ...)" instead.**
Dict{ASCIIString,Int64} with 3 entries:
  "two"   => 2
  "one"   => 1
  "three" => 3

Fix:
julia> **filled_dict = [Dict("one"=> 1), Dict("two"=> 2), Dict("three"=> 3)]**
3-element Array{Dict{ASCIIString,Int64},1}:
 Dict("one"=>1)
 Dict("two"=>2)
 Dict("three"=>3)

**Comment by vendethiel** [comment]
Nice catch. Could you send a Pull Request to fix this? :-)

**Comment by rawlik** [comment]
It is already fixed in the current version.
