### ISSUE TITLE
[c] Possible undefined behaviour with realloc call

### ISSUE THREAD

**Issue by rye761** [adambard/learnxinyminutes-docs#2331]
``` c
int size = 10;
int *my_arr = malloc(sizeof(int) * size);
// Add an element to the array
my_arr = realloc(my_arr, ++size);
my_arr[10] = 5;
```
In this case, realloc is actually decreasing the size of the allocated memory instead of increasing it.
Consider that this code:
```c
#include <stdio.h>

int main(int argc, char const *argv[]) {

  int size = 10;
  printf("%ld, %d\n", sizeof(int) * size, ++size);

  return 0;
}
```
results in `44, 11`.

Therefore setting `my_arr[10] = 5` is undefined behavior.

**Comment by vendethiel** [comment]
Huh, yeah. Missing a sizeof(int)* for sure... Would you mind sending a pull request to fix it? ;)

**Comment by rye761** [comment]
Sure, I will send one later today.

**Comment by vendethiel** [comment]
Thanks!
