### ISSUE TITLE
[Java/en] Code snippet that makes no sense

### ISSUE THREAD

**Issue by prestonpeterson** [adambard/learnxinyminutes-docs#2345]
https://github.com/adambard/learnxinyminutes-docs/blame/master/java.html.markdown#L569

This method does nothing. I believe it should be corrected to ` this.gear = 0;`
Should I submit a pull request?

**Comment by vendethiel** [comment]
yes, please! Thanks.

**Comment by prestonpeterson** [comment]
Ok, just submitted it!

**Comment by aloisdg** [comment]
@vendethiel your "fix" didnt work. You will have to close manually.

**Comment by vendethiel** [comment]
what?

**Comment by vendethiel** [comment]
@aloisdg thanks!

**Comment by aloisdg** [comment]
@vendethiel you are welcome :)
