### ISSUE TITLE
HTML french in root directory ?

### ISSUE THREAD

**Issue by aviaryan** [adambard/learnxinyminutes-docs#2348]
I see HTML-fr.html.markdown in root directory of repo and believe there has been a mistake. Shouldn't it be in fr-fr directory ? 
Also there is no `html` tutorial in the root directory (english).

**Comment by aloisdg** [comment]
This is indeed a problem. It shouldnt be there. cc @vendethiel

**Comment by vendethiel** [comment]
why do we have two...

**Comment by vendethiel** [comment]
425d1de  .
