### ISSUE TITLE
Live and Interactive code with KLIPSE

### ISSUE THREAD

**Issue by viebel** [adambard/learnxinyminutes-docs#2359]
It would be great to have live and interactive code snippets  in `learnxinyminutes`.

For that purpose, we could integrate [KLIPSE](https://github.com/viebel/klipse) in `learnxinyminutes-docs`.

KLIPSE is a simple client-side code evaluator pluggable on any web page for clojure, ruby, javascript, python.

Instructions for embedding KLIPSE on a web page are [here](https://github.com/viebel/klipse).

What do you think?

**Comment by vendethiel** [comment]
It's usually fair to say you're the author of whatever you're promoting...

**Comment by viebel** [comment]
No problem. Sorry for that.

**Comment by divayprakash** [comment]
Closing as this project has a much wider variety of languages and tools than supported by KLIPSE.
