### ISSUE TITLE
[bash/en] Link to book which is not released/ available.

### ISSUE THREAD

**Issue by ivirshup** [adambard/learnxinyminutes-docs#2372]
The bash tutorial has this at the top:

```
Another recommened link: [The Command Line Crash Course](http://cli.learncodethehardway.org/book/)
```

Which points to a resource that is not actually available. Screenshot:

![image](https://cloud.githubusercontent.com/assets/8238804/18578514/c8df1898-7c33-11e6-895e-6b2f832391a8.png)

**Comment by vendethiel** [comment]
Oh; whoops. Well... Nice watch. Would you mind making a PR to remove it?

**Comment by vendethiel** [comment]
Nice catch*

**Comment by ivirshup** [comment]
Sure!
