### ISSUE TITLE
Website Logtalk link gives 404 error

### ISSUE THREAD

**Issue by pmoura** [adambard/learnxinyminutes-docs#2380]
A Logtalk tutorial was recently merged (#2374). But the website Logtalk link gives a 404 error. GitHub renders the Markdown file perfectly. Maybe an issue when doing the conversion with Middleman?

**Comment by pmoura** [comment]
@adambard found that Middleman was crashing on Logtalk syntax coloring and fixed it for now in #13205b6. Trying to find the causes of the crash.

**Comment by vendethiel** [comment]
Because we don't have such an highlighter. Forgot to make sure, my bad

**Comment by pmoura** [comment]
No worries. Maybe I can contribute the highlighter. It would also work for Prolog. Any hints on where to look appreciated.

**Comment by vendethiel** [comment]
https://github.com/jneen/rouge, then ask @adambard to pull

**Comment by pmoura** [comment]
I will do it. In fact, there's a Logtalk highlighter contribution there waiting for a long time but it uses fully hand-optimized regular expressions and the Rouge maintainer doesn't like that and I never got around of undoing those optimizations.

**Comment by adambard** [comment]
That would be awesome. In the meantime, I think this issue is fixed, yes?

**Comment by pmoura** [comment]
Indeed. Thanks. I'm waiting for Rouge maintainers to check the changes they required and that I committed earlier today (https://github.com/jneen/rouge/pull/311).

**Comment by adambard** [comment]
Awesome, hit me by email (*@adambard.com) when that's ready, I'm not
exactly on the ball re: this issue tracker these days (sorry!)

**Comment by vendethiel** [comment]
Sorry for the dropping the ball on this one. I usually check before merging...

**Comment by adambard** [comment]
No problem, just a little 404 :) Middleman is gracious enough to just fail that file and keep going, so  it's really not a big deal. I break tiny parts of the site pretty much every time I touch it.

**Comment by pmoura** [comment]
I should have checked Middleman docs carefully for the lexer availability. Sorry for that. I saw the tutorial rendering nicely on GitHub and completely forgot that's not how the website files are generated.

**Comment by adambard** [comment]
TBH it's pretty annoying and unexpected that middleman crashes instead of just skipping the highlighting phase. It seems like it would be so easy to fail more gracefully.

**Comment by pmoura** [comment]
Agree. I would also expect that it defaulted to no highlighting and just use a PRE or CODE tag for the code snippet.
