### ISSUE TITLE
Why not use "lein new compojure myapp" to create template

### ISSUE THREAD

**Issue by devssh** [adambard/learnxinyminutes-docs#2407]
It has a slightly different project schema. Why is that?
I'm new to clojure.
See this video, last few minutes demo, the number of steps to make a project were much more efficient
https://www.youtube.com/watch?v=_LghX4oDWcY

**Comment by vendethiel** [comment]
PR welcome :)

**Comment by divayprakash** [comment]
@devssh Could you specify where exactly in the document you'd require this change?

**Comment by devssh** [comment]
I think it has changed too much since then, there's no info on how to setup webapp in clojure now?
