### ISSUE TITLE
[Broken link] PyQT link is 404

### ISSUE THREAD

**Issue by daleathan** [adambard/learnxinyminutes-docs#2417]
Link on front page for PyQT goes to:
https://learnxinyminutes.com/docs/pyqt/

which shows 404 not found

should probably go to 
https://github.com/adambard/learnxinyminutes-docs/blob/master/pyqt.html.markdown

**Comment by daleathan** [comment]
Front page still leads to broken link, when does the main page html get regenerated?

**Comment by vendethiel** [comment]
dunno really :(
