### ISSUE TITLE
[git/en] The link for LearnGit.txt

### ISSUE THREAD

**Issue by TanKris** [adambard/learnxinyminutes-docs#2463]
The link on the website for LearnGit.txt shows a portugese translation by default. Do kindly change it to English and/or provide an option for the portugese translation of it. I am attaching the translated version. Thank you.
https://learnxinyminutes.com/docs/files/LearnGit.txt ("Get the code" link on the git page - https://learnxinyminutes.com/docs/git/)

[LearnGit translated to English.txt](https://github.com/adambard/learnxinyminutes-docs/files/531669/LearnGit.translated.to.English.txt)

**Comment by vendethiel** [comment]
Let's see after 0c6b3e73374064d3e2c5a149608c4213ca2068d8.
