### ISSUE TITLE
[general][proposal] Use Transifex for translations?

### ISSUE THREAD

**Issue by linterpreteur** [adambard/learnxinyminutes-docs#2490]
[Transifex](https://www.transifex.com/) is a service aimed at making translating works easier. Many projects including [Lantern](https://www.transifex.com/otf/), [Disqus](https://www.transifex.com/disqus/), [Semantic UI](https://www.transifex.com/semantic-org/), and [Shattered Pixel Dungeon](https://www.transifex.com/shattered-pixel/) are utilizing Transifex for L10n of their services.

One primary benefit you would obtain by migrating to Transifex is that you can keep track of newly added strings added to the source language files. Under current system using GitHub, even if there are changes made to the original files, in this case English ones, the only way to track changes would be to review source files line by line. It leads to the situation that many translated docs are outdated while English ones are updated a lot.

Transifex offers signing in with GitHub account, and I think it is pretty efficient to use, project manager or translators side.

**Comment by vendethiel** [comment]
It's not really feasible. Tutorials are not pieces of strings you can translate here-and-on. They're a whole file at once, so the service doesn't really apply.

**Comment by linterpreteur** [comment]
Ok, thanks for your comment.
