### ISSUE TITLE
PowerShell code doesn't have highlighting

### ISSUE THREAD

**Issue by vors** [adambard/learnxinyminutes-docs#2498]
I noticed that on https://learnxinyminutes.com/docs/powershell/ there is no syntax highlighting. What do you use for the highlighting? Highlight.js has PowerShell support. Textmate grammar is also available https://github.com/SublimeText/PowerShell

**Comment by vendethiel** [comment]
We use https://github.com/adambard/rouge

And it does seem like it has a https://github.com/adambard/rouge/blob/master/lib/rouge/lexers/powershell.rb powershell grammar.
