### ISSUE TITLE
Some pages are not generating because a problem with middleman-syntax/extension.rb

### ISSUE THREAD

**Issue by samcv** [adambard/learnxinyminutes-docs#2513]
This line (Line 40) in `~/.gem/ruby/2.3.0/gems/middleman-syntax-1.2.1/lib/middleman-syntax/extension.rb`

`lexer = Rouge::Lexer.find_fancy(language, code) || Rouge::Lexers::Text`

Needs to change to be this:
`lexer = Rouge::Lexer.find_fancy(language, code) || Rouge::Lexers::PlainText `

Doing that the pages generate properly.  Some of them are showing up right now but that may not mean they're actually generating properly.

Here is a list.  Haven't checked all of them on the website proper, but none of the following build on my computer without that change:
build/docs/objective-c/index.html
build/docs/ru-ru/objective-c-ru/index.html
build/docs/id-id/pyqt-id/index.html
build/docs/id-id/coffeescript-id/index.html
build/docs/pyqt/index.html
build/docs/rst/index.html (DOES'NT SHOW UP)
/docs/sk-sk/elixir/index.html
build/docs/tr-tr/objective-c-tr/index.html
build/docs/kotlin/index.html
build/docs/vi-vn/objective-c-vi/index.html
build/docs/fa-ir/css-fa/index.html (DOESN't SHOW UP)
build/docs/fr-fr/objective-c-fr/index.html (SHOWS)

**Comment by vendethiel** [comment]
Shouldn't this be raised on the -site repo? @adambard

**Comment by samcv** [comment]
Hmm maybe.  Though the file I needed to change isn't in either of the repositories (~/.gem/ruby/2.3.0/gems/middleman-syntax-1.2.1/lib/middleman-syntax/extension.rb)
I found this issue on their tracker:
https://github.com/middleman/middleman-syntax/issues/45

I will try and see if making the suggested change there fixes it in a bit.

**Comment by samcv** [comment]
I don't really know ruby, I tried to fix it through changing the site's config.rb but just encountered the same issues (or tried updating some of the gems to later version than in the gemfile).  Patching that line in middleman-syntax works though.  The site is locked to older versions of a lot of things, and updating middleman made the clementine extension not work since it's now an old extension method and isn't supported anymore on the latest middleman.  @adambard your thoughts?

**Comment by samcv** [comment]
@vendethiel Opened this on adambard/learnxinyminutes-site#36
