### ISSUE TITLE
I want check for data on source for a minute or 55 seconds

### ISSUE THREAD

**Issue by kmaelane** [adambard/learnxinyminutes-docs#2555]
I want check for data on source for a minute or 55 seconds. My problem is I don't know the timeout intervals for this IOHandler Routine (function TIdIOHandler.CheckForDataOnSource(ATimeout: Integer = 0): Boolean;).

Here is my code below
  
socClient.Socket.RecvBufferSize := 1024;
socClient.Socket.CheckForDataOnSource(**1000**);

**Comment by vendethiel** [comment]
Please use StackOverflow for programming-related questions.
