### ISSUE TITLE
[yaml/en] Not necessary to quote '1' to be interpreted as a number.

### ISSUE THREAD

**Issue by tomjakubowski** [adambard/learnxinyminutes-docs#2558]
Near the top of the [YAML page](https://learnxinyminutes.com/docs/yaml/):

```
# If you want to use number 1 as a value, you have to enclose it in quotes, 
# otherwise, YAML parser will assume that it is a boolean value of true.
scientific_notation: 1e+12
```

However, the YAML 1.2 spec doesn't suggest this interpretation at all: http://www.yaml.org/spec/1.2/spec.html#id2803629

The YAML online parser (which uses pyyaml), [interprets `1` as an integer](https://yaml-online-parser.appspot.com/?yaml=1&type=canonical_yaml):

```

---

---
!!int "1"
```

As far as I can tell, it's not possible to create a boolean from a numeric literal [even with an explicit tag](https://yaml-online-parser.appspot.com/?yaml=!!bool+1&type=canonical_yaml):

```
!!bool 1
# produces error with pyyaml
```

**Comment by vendethiel** [comment]
Thanks - nice catch! Woul you mind sending a pull request to fix it? :)
