### ISSUE TITLE
[RUS/HTML] HTML Russian translation is appearing as a new section in the main page

### ISSUE THREAD

**Issue by JoaoGFarias** [adambard/learnxinyminutes-docs#2573]
The russian translation for HTML is appearing in the site's main page as a different section.

![learn x in y minutes scenic programming language tours - mozilla firefox](https://cloud.githubusercontent.com/assets/1585655/20348193/0b1807c2-abe3-11e6-880c-d3fd707a9773.jpg)

**Comment by samcv** [comment]
Thanks for reporting this!
