### ISSUE TITLE
Fix spelling error in new issue text requets > requests

### ISSUE THREAD

**Issue by uxcq** [adambard/learnxinyminutes-docs#2574]
> Make sure the issue title is prepended with '[language/lang-code]' if the language is
> already on the site.
> If it's a request for a new language, use: '[Request] [language/lang-code]'
> 
> Issues are always welcome. If you are able and willing, we welcome any pull **requets**
> as this is a community powered project.
> 
> 

_requets_ should be **requests**

**Comment by samcv** [comment]
Thanks!
