### ISSUE TITLE
[language/common-lisp] UNBOUND-VARIABLE

### ISSUE THREAD

**Issue by phoe** [adambard/learnxinyminutes-docs#2577]
```
;; Accessing a previously unbound variable is an
;; undefined behavior (but possible). Don't do it.
```

http://www.lispworks.com/documentation/HyperSpec/Body/e_unbo_1.htm
AFAIK, attempting to read an unbound variable results in `UNBOUND-VARIABLE` error being signaled. So it's defined.

Can anyone confirm this?

**Comment by vendethiel** [comment]
You're right, [it doesn't seem to be UB](https://www.hexstreamsoft.com/articles/notes-tips-standard-common-lisp-symbols/themes/unspecified-behavior/). Would you mind sending a Pull Request to correct this? :)

**Comment by phoe** [comment]
Yes, I'll do a PR soon.
