### ISSUE TITLE
[language/common-lisp] Default MAKE-ARRAY value

### ISSUE THREAD

**Issue by phoe** [adambard/learnxinyminutes-docs#2578]
```
(aref (make-array (list 2 2 2)) 1 1 1)
; => 0
```

This value is implementation-defined: 0 on SBCL, but NIL on SBCL.

**Comment by vendethiel** [comment]
Even worse, it seems:

>  If initial-element is not supplied, the consequences of later reading an uninitialized element of new-array are undefined unless either initial-contents is supplied or displaced-to is non-nil.

(PS: you probably want one of those "SBCL" to be "CCL" or some other)

**Comment by phoe** [comment]
Yes, undefined by the standard - that's why implementations are almost always defining this behaviour, because if you call `(make-array 1000)` in REPL, what do you get in return? A printed representation of that array. What does it consist of? Instances of later reading of uninitialized elements of new-array. Woo, `CL-USER> (make-array 1000)` in REPL is undefined behaviour!

Uh, right. NIL on ECL, 0 on SBCL and CCL.
