### ISSUE TITLE
the [1..5] example no longer works in 0.18

### ISSUE THREAD

**Issue by gr33ntea** [adambard/learnxinyminutes-docs#2583]
-- The second example can also be written with two dots.
[1..5]
Yes this code no longer works in version 0.18. I believe you can do the following to achieve similar effects 
List.range 1 5

**Comment by samcv** [comment]
@gr33ntea did you read the text you just submitted? You are supposed to actually tell us which language and programming language this is referring to. Please update your post with the correct details. Thanks.

**Comment by samcv** [comment]
@gr33ntea What programming language is this referring to? Even a link to the page would be more useful. Thank you for adding more description about the problem with it, but I still don't know what page the issue is on.

**Comment by gr33ntea** [comment]
Sorry I didn't know you had more than one programming language you worked
on. I simply clicked the link at the bottom of one of your aticles. I
believed the article was called learn x in y and x = elm. The programming
language is Elm.

**Comment by gr33ntea** [comment]
Oh here's the link if you need it: https://learnxinyminutes.com/docs/elm/

**Comment by gr33ntea** [comment]
There's only 1page? Can't you ctrl + f what I wrote as the title after going to the link given?
