### ISSUE TITLE
 [1.. 5] does not work in 0.18

### ISSUE THREAD

**Issue by anilkris** [adambard/learnxinyminutes-docs#2584]
Hi,

I liked your beginner tutorial on elm.  A small correction, I have observed.

From version 0.18,  the List need to be given as below
List.range 1 5

Please correct this, so that it would be relevant for the latest version.

Thanks,

**Comment by vendethiel** [comment]
Thanks, nice catch! Would you mind sending a pull request to fix this? :-)

**Comment by anilkris** [comment]
Hi,  

I have created a pull request, with the correction.  Please, let me know,  if that was ok, or if  I missed any steps in the process.

Regards,
