### ISSUE TITLE
[language/lang-code] Broken link under references

### ISSUE THREAD

**Issue by josh-perry** [adambard/learnxinyminutes-docs#2589]
>I created a more indepth Visual Basic tutorial for those who would like to learn more.

[vbbootcamp.co.uk](http://vbbootcamp.co.uk) doesn't seem to exist anymore.

**Comment by vendethiel** [comment]
> [language/lang-code] Broken link under references 

Did nothing seem off to you when you posted the issue? :|

I can guess it's VB / english thanks to the link, but please read the issue title before submitting.

The commit introducing that was one of @adambard's (back in 2013): 4ecd73fc9cd766557e10fc2fa0c3351c373ff1a0 – so I actually have no idea what's it's from.

Anyway, it's removed, thanks.

**Comment by josh-perry** [comment]
Oh, my bad, sorry. I thought I'd changed that.

**Comment by vendethiel** [comment]
No worries! It still had more than enough context since you quoted the text :). Thanks!
