### ISSUE TITLE
[JavaScript] Small comment mistake in french

### ISSUE THREAD

**Issue by JulienFONTANA** [adambard/learnxinyminutes-docs#2593]
This line in incorrect in french (maybe in other languages too):
someVar *= 10; // de même, someVar = someVar * 100;
It should be:
someVar *= 10; // de même, someVar = someVar * **10**;

**Comment by vendethiel** [comment]
Nice catch, thanks! Would you mind sending a pull request to fix it? :)

**Comment by aloisdg** [comment]
@JulienFONTANA Nice! Could you submit a quick [PR](https://help.github.com/articles/about-pull-requests/) now? 👍
