### ISSUE TITLE
[language/nim] Multiline comments

### ISSUE THREAD

**Issue by cchase88** [adambard/learnxinyminutes-docs#2603]
As of 0.13, Nim supports multi-line comments using the #[ ... ]# syntax. Ex:

```nim
#[ This is a multi-line comment.

This is part of the comment.

And this.

#]
```

**Comment by vendethiel** [comment]
Thanks for the heads up! Are you interested in submitting a PR to add this?

**Comment by cchase88** [comment]
Hi Adam, I am interested in submitting pull requests.

Thanks,
Chris

**Comment by sidgupta234** [comment]
What is the status on this one?
