### ISSUE TITLE
[Smalltalk] Missing explanation of the language semantics etc

### ISSUE THREAD

**Issue by timrowledge** [adambard/learnxinyminutes-docs#2622]
The Smalltalk page is a pretty good listing of the basic language syntax and some examples of usage but
a) the title really ought to be X=Smalltalk, not X=smalltalk
b) some explanation that everything is an object and that all one can do is send messages and get back the return values would be helpful near the very beginning.
c) wrt Blocks section -Squeak *does* allow block local vars and certainly allows more than three block arguments. I'm not at all sure why the claim about long term storage and non-local returns is there.
d) Method calls: - that really ought to be refer to Message sends. We don't call methods.
e) in the Ready For More section I'd urge removing the links to smalltalk.org as it has become very irrelevant. Squeak.org and pharo.org would be more appropriate, all in all.

**Comment by Oire** [comment]
@timrowledge, could you please send us a pull request with the changes you mentioned? Thank you!

**Comment by timrowledge** [comment]
I've attempted to provide some updates and hopefully issued a pull request correctly There is more to do later; the original version was basically just an uncredited copy of http://www.angelfire.com/tx4/cus/notes/smalltalk.html which was a bit unfortunate.

**Comment by Oire** [comment]
@timrowledge, sorry, I don't see a pull request. Could you please reference it by number or re-submit it? Thanks!

**Comment by timrowledge** [comment]
Sorry about the PR confusion; I'm not a git user on any sort of regular basis.
I will attempt to make further improvements soon.

**Comment by divayprakash** [comment]
Ok! I'm merging the PR for now to enable you to work on the file. Thank you for the contribution!

**Comment by divayprakash** [comment]
These are still left to fix -

> c) wrt Blocks section -Squeak does allow block local vars and certainly allows more than three block arguments. I'm not at all sure why the claim about long term storage and non-local returns is there.
d) Method calls: - that really ought to be refer to Message sends. We don't call methods.

**Comment by divayprakash** [comment]
Closing this issue. The points left are now present as issue #3384.
