### ISSUE TITLE
Small slip in example?

### ISSUE THREAD

**Issue by mfricke1947** [adambard/learnxinyminutes-docs#2642]
```java
contract SimpleBank { // CapWords
    // Declare state variables outside function, persist through life of contract

    // dictionary that maps addresses to balances
    // always be careful about overflow attacks with numbers
    mapping (address => uint) private balances;

    // "private" means that other contracts can't directly query balances
    // but data is still viewable to other parties on blockchain

    address public owner;
    // 'public' makes externally readable (not writeable) by users or contracts

    // Events - publicize actions to external listeners
    event LogDepositMade(address accountAddress, uint amount);

    // Constructor, can receive one or many variables here; only one allowed
    function AcmeBank() {
        // msg provides details about the
```
-----------------------

Shouldn't the constructor have the same name as the contract?

**Comment by vendethiel** [comment]
which language is that?

**Comment by mfricke1947** [comment]
Sorry, this is from the Solidity notes

**Comment by vendethiel** [comment]
@miguelmota @nemild ?

**Comment by vendethiel** [comment]
@mfricke1947 BTW, I edited your comment to add triple backticks around the code block.

**Comment by nemild** [comment]
@vendethiel  Yes, they should be the same. That was a mistake I made. @mfricke1947 thanks for pointing out.

There have been a ton of changes in Solidity, so this doc also needs a reworking at some point.

**Comment by mfricke1947** [comment]
No worries. I’m happy to help (even in this ever-so-minor way).

All the best,

Yours,

Martin


On Jan 31, 2017, at 7:45 PM, Nemil Dalal <notifications@github.com<mailto:notifications@github.com>> wrote:


@vendethiel<https://github.com/vendethiel> Yes, they should be the same. That was a mistake I made. @mfricke1947<https://github.com/mfricke1947> thanks for pointing out.

There have been a ton of changes in Solidity, so this doc also needs a reworking at some point.

**Comment by vendethiel** [comment]
@nemild okay, thanks for the precision. I'll be here if you want to send a PR to update the docs ;-)

**Comment by nemild** [comment]
Done, submitted in [this pull request](https://github.com/adambard/learnxinyminutes-docs/pull/2650).

**Comment by vendethiel** [comment]
#2650
