### ISSUE TITLE
[Request][language/awk]

### ISSUE THREAD

**Issue by pubudu91** [adambard/learnxinyminutes-docs#2643]
Will it be possible to add a page for Awk? Awk is pretty useful when trying to process large text files efficiently and it would be great to have a quick reference for it

**Comment by sbdchd** [comment]
I highly recommend checking out the `man` page for awk. It is quite concise and thorough.

**Comment by Oire** [comment]
@pubudu91, now there is a page about Awk. Thanks for your request!
