### ISSUE TITLE
[asciidoc/en]

### ISSUE THREAD

**Issue by abelsromero** [adambard/learnxinyminutes-docs#2644]
Consider adding implementations reference for `asciidoctor` (http://asciidoctor.org/).
The current page offers a good intro into the language but does not offer any guide to users wanting to test it out.

Right now there are two options:
· AsciiDoc: original python lib. Not sure about it's current state. Github seems active (https://github.com/asciidoc/asciidoc), but the site does not list a release since 2013 (http://www.methods.co.nz/asciidoc/CHANGELOG.html).
· Asciidoctor: Ruby alternative. Pretty active a with integration with Java and JavaScript.

**Comment by Oire** [comment]
@abelsromero, could you please send us a pull request with these changes? Thanks!

**Comment by abelsromero** [comment]
If it's OK, I'll add a section at the end called "Further Reading". I see most articles use this structure.
