### ISSUE TITLE
[c++/en] Shouldn't be defining variables in h files

### ISSUE THREAD

**Issue by LoudDavion** [adambard/learnxinyminutes-docs#2647]
h files are for declarations.

Why not teach the extern keyword and have people define the variables inside a cpp file instead.

**Comment by vendethiel** [comment]
what are you talking about?

**Comment by LoudDavion** [comment]
When the guide talks about classes, it says that they are generally done inside h files.
`// Classes are usually declared in header (.h or .hpp) files.`

It then declares a variable and several function inside the class.

Then it proceeds to define the functions and it says
`// Class member functions are usually implemented in .cpp files.`

But you don't say that about variables. Why would you teach people to define functions inside cpp files but not do the same for variables.

**Comment by vendethiel** [comment]
Please don't post issues for trolling purposes

**Comment by LoudDavion** [comment]
I don't understand how this is trolling friend.
Do you have any actual arguments for why you don't want to teach the `extern`

**Comment by vendethiel** [comment]
there's no reason to use it, especially here. the only variables are instance/class variables.
