### ISSUE TITLE
Are React, React Native and Flow out of scope?

### ISSUE THREAD

**Issue by Dorian** [adambard/learnxinyminutes-docs#2665]
I love learnxinyminutes and I'm just wondering if those examples are in scope for inclusion?

**Comment by vendethiel** [comment]
I'd say so, yes. We aren't gonna beat the documentation for those libraries.

The only exceptions would be for documentations that thoroughly lack examples, I guess...

**Comment by Dorian** [comment]
@vendethiel Hmm I understand, I will try it on my own domain and see if there is a need for it (loving the learnxinyminutes format), then ideally merge it back here, but right, docs for those are actually already pretty good.
