### ISSUE TITLE
[go/en] Def description (before or after)

### ISSUE THREAD

**Issue by OPEOP** [adambard/learnxinyminutes-docs#2673]
```
func learnDefer() (ok bool) {
    // Deferred statements are executed just BEFORE the function returns.
    defer fmt.Println("deferred statements execute in reverse (LIFO) order.")
    defer fmt.Println("\nThis line is being printed first because")
    // Defer is commonly used to close a file, so the function closing the
    // file stays close to the function opening the file.
    return true
}
```

But:
A defer statement pushes a function call onto a list. The list of saved calls is executed **AFTER** the surrounding function returns. [(Official site)](https://blog.golang.org/defer-panic-and-recover)

And it is't only in [en]...

**Comment by vendethiel** [comment]
I think both mean the same, don't they? Is something inbetween?

**Comment by OPEOP** [comment]
Uh no. If the list of deferred function calls is executed after function return and you say that deferred statement is called before function return, how can these mean the same?

**Comment by vendethiel** [comment]
What is the difference?

**Comment by OPEOP** [comment]
Ok, I show you))

Here is the code: https://play.golang.org/p/01iLGAg9Hq

In your meaning, result of function 'do' must be 0 (_because def must run before_), but(!) how you can see result did't change. Because def function run **AFTER** the function returns.

**Comment by vendethiel** [comment]
"Before the function returns" doesn't mean before return's operand is evaluated.

**Comment by vendethiel** [comment]
I guess we should follow the doc's wordings nonetheless.
