### ISSUE TITLE
[Python3/English] Mistake in static method

### ISSUE THREAD

**Issue by andrewlee116** [adambard/learnxinyminutes-docs#2677]
` # A static method is called without a class or instance reference
@staticmethod`
   
```
def grunt():
return "*grunt*"

i = Human(name="Ian")

# Call the static method
 print(Human.grunt())            # => "*grunt*"
 print(i.grunt())            # => "*grunt*"
```

Though Human.grunt() is correct and would print out "*grunt*", I believe that i.grunt() should raise an error because that line would put itself as an argument (self) when a static method should have no argument. So only Human.grunt() should be possible.

**Comment by vendethiel** [comment]
yup, that's an error, nice catch! Would you mind sending a PR to fix it?

**Comment by andrewlee116** [comment]
yup
