### ISSUE TITLE
error in learnxml.xml file [xml/all]

### ISSUE THREAD

**Issue by ankitch** [adambard/learnxinyminutes-docs#2683]
XML Parsing Error 
There is an error in the learnxml.xml file there are multiple declarations of xml in the same file. Same error for all the translations.

**Comment by vendethiel** [comment]
Yup, that's on purpose. Each different code block, if identified as a document, should work, however.

**Comment by ankitch** [comment]
https://learnxinyminutes.com/docs/files/learnxml.xml
