### ISSUE TITLE
[bash/es] Some errors

### ISSUE THREAD

**Issue by SerSanGal** [adambard/learnxinyminutes-docs#2684]
Starting in line 61:
`If [ $ NAME -ne $ USER ]
Then
     Echo "Your name is your user."
Else
     Echo "Your name is not your user."
Fi `

The -ne is for non-equal. In this example -ne should be changed by -eq since if this expression returns true echo will return "Your name is your user".
But it's still incorrect since -ne or -eq expect to compare integers not strings, so I think this expression:
`[ $ NAME -ne $ USER ]`
Should be changed to:
`[ $ NAME == $ USER ]`

The next error I found is in line 134:
`While [true]`
It should be
`While [ true ]`

The last error I found is in line 158:
`Foo 'My name is:" $ NAME`
No foo function is found in the script. It should be changed to miFuncion which is in line 142 or miOtraFuncion which is in line 151.

Also I want to comment that the spanish version of LearnBash is much poor than the english version...

**Comment by vendethiel** [comment]
Hi ;

would you have some time to submit a PR to fix those ? And maybe add the missing parts to the -es document - they're not being kept up-to-date :).

**Comment by SerSanGal** [comment]
I'm working on it
