### ISSUE TITLE
[Groovy] Additional Resources

### ISSUE THREAD

**Issue by cfaddict** [adambard/learnxinyminutes-docs#2692]
I teach a course called "The Complete Apache Groovy Developer Course". This course is linked to within the main Groovy website and I would like to add a new section. The new section courses would simply have a link to the course. Is this ok? 

![image](https://cloud.githubusercontent.com/assets/349507/24559653/7b03d7ca-160d-11e7-83dd-3513154a2dda.png)

**Comment by vendethiel** [comment]
We try to avoid paid resources. I guess books are an exception.
