### ISSUE TITLE
[javascript/cs] some recommendation in czech language

### ISSUE THREAD

**Issue by martin-uda** [adambard/learnxinyminutes-docs#2707]
Hello,
first of all: email martinek@ludis.me   doesn't work.
// the rest is in czech lang.

Dobry den,
mel bych par navrhu jak upravit https://learnxinyminutes.com/docs/cs-cz/javascript/
original  je predpokladam zde: https://learnxinyminutes.com/docs/javascript/

1)
// Vyrazu můžou být spuštěny pomocí ;
delejNeco();

original:
// Statements can be terminated by ;
doStuff();

navrh:
// Příkazy mohou být ukončeny středníkem ;
doStuff();

2)
"Hello world"  bych neprekladal, je to priklad, ktery je vseobecne znamy. A vyhledavace ho najdou, coz prispeje k rozsireni clanku/stranky.

3)

// Existují také typy `null` a `undefined`.
null;       // značí, že žádnou hodnotu
undefined;  // značí, že hodnota nebyla definovaná (ikdyž
           // `undefined` je hodnota sama o sobě)

orig:
// There's also `null` and `undefined`.
null;       // used to indicate a deliberate non-value
undefined;  // used to indicate a value is not currently present (although
           // `undefined` is actually a value itself)

navrh:
// Existují také `null` a `undefined`.
null;       // obvykle označuje něco záměrně bez hodnoty       ###### slovo záměrně mi prijde dulezite
undefined;  //obvykle označuje, že hodnota není momentálně definovaná (ačkoli
           // `undefined` je hodnota sama o sobě)

4)
var  mojePole  =  ["Ahoj",  45,  true];

navrh:
var  myArray  =  ["Ahoj",  45,  true];        ##### viz dalsi radky, kde je ponechano myArray

5) nektere veci bych neprekladal

// `if` (když) funguje, jak byste čekali.

navrh:
// `if` funguje, jak byste čekali.

6) chybi
// Breaking out of labeled loops is similar to Java
outer:
for  (var  i  =  0;  i  <  10;  i++)  {
    for  (var  j  =  0;  j  <  10;  j++)  {
        if  (i  ==  5  &&  j  ==5)  {
            break  outer;
            // breaks out of outer loop instead of only the inner one
        }
    }
}

navrh:
// Opuštění cyklu s návěštím je podobné jako v Javě
outer:
for  (var  i  =  0;  i  <  10;  i++)  {
    for  (var  j  =  0;  j  <  10;  j++)  {
        if  (i  ==  5  &&  j  ==5)  {
            break  outer;
            // opustí vnější (outer) cyklus namísto pouze vnitřního (inner) cyklu
        }
    }
}

7) preklep
ma byt:  // 4. Funkce,

S pranim krasneho dne,
Martin

**Comment by vendethiel** [comment]
Hi,

feel free to send a pull request to fix those

**Comment by Oire** [comment]
@martin-uda, yes, please send a PR. I don't speak Czech, but I'm Ukrainian, and my common Slavic reading skills are enough to understand that your changes are reasonable :).
