### ISSUE TITLE
[racket/en] Incorrect name of mutable struct in setting and accessing examples.

### ISSUE THREAD

**Issue by stevechae** [adambard/learnxinyminutes-docs#2714]
In the current document, examples of setting and accessing a mutable struct called `rgba-color` are:
```rkt
(set-color-green! burgundy 10)
(color-green burgundy) ; => 10
```
This is incorrect and should be:
```rkt
(set-rgba-color-green! burgundy 10)
(rgba-color-green burgundy) ;=> 10
```

**Comment by vendethiel** [comment]
Would you mind sending a PR to fix it?

**Comment by stevechae** [comment]
@vendethiel sure, I'm at work now but I will submit a PR in a few hours.
