### ISSUE TITLE
[Kotlin] Remove whitespace in variable declaration with explicit type

### ISSUE THREAD

**Issue by BloodShura** [adambard/learnxinyminutes-docs#2729]
In [Kotlin section](https://learnxinyminutes.com/docs/kotlin/), at the start of the _main_ function, there is a line containing `val foo : Int = 7`.

Generally, as seen also in the [docs](https://kotlinlang.org/docs/reference/properties.html), the whitespace before the colon should be omitted. Actually, whitespace before colon is used when declaring the superclasses of a class, e.g. `class Child : Parent { }`, but not when specifying the type of something, e.g. `fun main(args: Array<String>)`, `val hey: String? = null`, etc.

**Comment by vendethiel** [comment]
We totally should follow the official style. Would you mind sending a PR?

**Comment by BloodShura** [comment]
Since the PR has been merged, I'll close it ^-^
