### ISSUE TITLE
[C/C] correction on printf

### ISSUE THREAD

**Issue by artur-pub** [adambard/learnxinyminutes-docs#2730]
https://learnxinyminutes.com/docs/c/, these lines are wrong:

    printf("%f\n", (float)100); // %f formats a float
    printf("%lf\n", (double)100); // %lf formats a double

Yes, `%f` formats a float, but that float is actually extended to double because of varargs type promotion before the call (printf(fmt, ...) arguments after fmt are varargs). Printf function never sees floats (nor chars, nor shorts). `%lf` has no effect according to [1], expectedly.

I'd suggest the following change:

    -printf("%f\n", (float)100); // %f formats a float
    -printf("%lf\n", (double)100); // %lf formats a double
    +printf("%f\n", (double)100); // %f formats a double
    +printf("%f\n", (float)100); // floats are promoted to doubles in varargs

But the varargs topic is not covered by the article at all, so I'm unsure. Anyway, the original statement is not true (it does no harm in this context, but educates wrong things).

  [1] http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html

>l (ell)
>Specifies that a following d, i, o, u, x, or X conversion specifier applies to a long or unsigned long argument; that a following n conversion specifier applies to a pointer to a long argument; that a following c conversion specifier applies to a wint_t argument; that a following s conversion specifier applies to a pointer to a wchar_t argument; or **has no effect** on a following a, A, e, E, f, F, g, or G conversion specifier.

**Comment by vendethiel** [comment]
Ah, that's not an easy one. I still feel like we should mention it, even if varargs are not (yet) explained

**Comment by ian-bertolacci** [comment]
I'll be honest, I don't know of a situation where I'm concerned that my floats are being printed as doubles, and I doubt that the most learn x in y readers, will be needing these kinds of details.

I think it's easiest to just say:
```
printf("%f\n", (double) 100); // %f always formats a double...
printf("%f\n", (float)  100); // ...even with a float.
```

The sufficiently curious will google the details

**Comment by vendethiel** [comment]
That's also fine by me. "even with a float" or "a float gets implicitly converted to a double".

**Comment by artur-pub** [comment]
>The sufficiently curious will google the details

@ian-bertolacci, as "printf double float" search leads to SO question explaining it, I think your suggestion is really good in that it is easy to understand both with and without going into details.
