### ISSUE TITLE
[shutit/en] 404'ing

### ISSUE THREAD

**Issue by ianmiell** [adambard/learnxinyminutes-docs#2748]
https://learnxinyminutes.com/docs/shutit/

The link above from the main page to ShutIt 404s.

Was there a mistake in my PR?

**Comment by vendethiel** [comment]
I can't seem to figure out what's wrong with it, so I'll ask the almighty @samcv who knows how everything works.

**Comment by samcv** [comment]
Sorry didn't see this notification. I'll put it on my todo list for tomorrow to try and figure it out!

**Comment by samcv** [comment]
@vendethiel page generates perfectly fine for me. Though there are many other pages that are having errors which I will open a bug for shortly. @adambard something is going on on your end, as no errors generating that page for me.

**Comment by adambard** [comment]
The usual, I changed \`\`\`shell to \`\`\`bash and it seems happy.
