### ISSUE TITLE
Many pages contain errors when building the site

### ISSUE THREAD

**Issue by samcv** [adambard/learnxinyminutes-docs#2753]
* error  build/docs/pt-br/markdown-pt/index.html
* error  build/docs/pt-br/common-lisp-pt/index.html
* error  build/docs/pt-br/visualbasic-pt/index.html
* error  build/docs/toml/index.html
* error  build/docs/ko-kr/markdown-kr/index.html
* ~~error  build/docs/CONTRIBUTING/index.html~~
* error  build/docs/nl-nl/markdown-nl/index.html
* error  build/docs/visualbasic/index.html
* error  build/docs/zh-cn/markdown-cn/index.html
* error  build/docs/zh-cn/visualbasic-cn/index.html
* ~~error  build/docs/ISSUE_TEMPLATE/index.html~~
* error  build/docs/LOLCODE/index.html
* error  build/docs/de-de/markdown-de/index.html
* ~~error  build/docs/README/index.html~~
* error  build/docs/cs-cz/markdown/index.html
* error  build/docs/common-lisp/index.html
* error  build/docs/ru-ru/markdown-ru/index.html
* error  build/docs/it-it/markdown/index.html
* error  build/docs/cypher/index.html
* error  build/docs/fr-fr/markdown/index.html
* error  build/docs/markdown/index.html
* error  build/docs/tr-tr/markdown-tr/index.html
* ~~error  build/docs/PULL_REQUEST_TEMPLATE/index.html~~
* error  build/docs/es-es/visualbasic-es/index.html
* error  build/docs/es-es/objective-c-es/index.html
* error  build/docs/es-es/markdown-es/index.html
* error  build/docs/fi-fi/markdown-fi/index.html
* error  build/docs/id-id/markdown/index.html

Most of the markdown entries errored because markdown is not the proper syntax highlighting name:

````
Incorrect
```markdown
```

Correct
```md
```
````

Full build log here: [buildlog2.txt](https://github.com/adambard/learnxinyminutes-docs/files/1062673/buildlog2.txt)

**Comment by samcv** [comment]
@vendethiel Almost all of them are due to the same markdown highlighter issue. The rest you'll have to check the logs 😃

**Comment by vendethiel** [comment]
Thanks, that's helpful.

**Comment by divayprakash** [comment]
Working on it!

**Comment by divayprakash** [comment]
PR #3187.
Also, can anyone guide me as to how I can test the site locally?
