### ISSUE TITLE
brainfuck

### ISSUE THREAD

**Issue by newShepard** [adambard/learnxinyminutes-docs#2758]
Make sure the issue title is prepended with '[language/lang-code]' if the language is
already on the site.
If it's a request for a new language, use: '[Request] [language/lang-code]'

Issues are always welcome. If you are able and willing, we welcome any pull requests
as this is a community powered project.

**Comment by ian-bertolacci** [comment]
Whats the issue? There is already a BF tutorial (https://learnxinyminutes.com/docs/bf/)

As for the naming, issue #2120 addresses the use of BF instead of brainfuck.
