### ISSUE TITLE
[Request] Jinja and other templating engines

### ISSUE THREAD

**Issue by tom-sherman** [adambard/learnxinyminutes-docs#2766]
Is there any interest in these languages? I was just getting started on a Jinja doc and realised this project doesn't have any template engine related content.

If this is within scope of the project, there are a few questions to be asked.

As the template engine's syntax and its API are both equally important when using it, should the doc cover both of these subjects? For example, in a Jinja doc should I explain both the Jinja syntax and how you would go about using it with the Python API?

**Comment by adambard** [comment]
As long as it's useful to someone somewhere, we have no relevance criteria whatsoever. I for one would happily merge in a Jinja doc (at such time as I got around to it).

I'd say it's enough to give a summary of how Jinja executes python and/or how Python can compile jinja templates, then link to one of the python docs.
