### ISSUE TITLE
[scala/en] Clairfy comment about foreach and Unit

### ISSUE THREAD

**Issue by cincodenada** [adambard/learnxinyminutes-docs#2767]
I went to try to edit this comment for readability, but I literally don't understand what it's trying to say:
```
// Scala a foreach method defined on certain collections that takes a type
// returning Unit (a void method)
val aListOfNumbers = List(1, 2, 3, 4, 10, 20, 100)
aListOfNumbers foreach (x => println(x))
aListOfNumbers foreach println
```

But judging by the code example, it seems to just be re-iterating what has now already been explained above in the Functional Programming section:

```
// If the anonymous block AND the function you are applying both take one
// argument, you can even omit the underscore
List("Dom", "Bob", "Natalia") foreach println
```

So perhaps that section can just be removed now?

**Comment by vendethiel** [comment]
The explanation is still interesting, comparing map vs foreach

**Comment by cincodenada** [comment]
Okay, in that case the comment still should be reworded, and I can't quite tell what it's trying to say. Perhaps this?

```
// Certain collections (such as List) in Scala have a `foreach` method,
// which takes as an argument a type returning Unit - that is, a void method
```

**Comment by vendethiel** [comment]
Sounds good to me.

**Comment by cincodenada** [comment]
Cool, now that I understand what it was going for, I've added this into #2768, so I'll close this out.
