### ISSUE TITLE
[lolcode/en] Link broken (404)

### ISSUE THREAD

**Issue by andys8** [adambard/learnxinyminutes-docs#2773]
The link to "LOLCODE" is currently dead. Could be related to #2753.

#### Reproduce
1. Open https://learnxinyminutes.com
2. Click on "LOLCODE"
3. https://learnxinyminutes.com/docs/LOLCODE/ is currently 404

**Comment by andys8** [comment]
Still dead. Anyone looking into it?
![image](https://user-images.githubusercontent.com/13085980/27840456-5d1bccea-60f9-11e7-9f2a-0b5339edb294.png)

**Comment by davelima** [comment]
@adambard maybe the filename must be lower case? Currently is the only .html.markdown file with upper case name
