### ISSUE TITLE
[Request] Categories Redesign or at least a column with the following info

### ISSUE THREAD

**Issue by nereusx** [adambard/learnxinyminutes-docs#2774]
I would like to see separated in those categories, the most are used for decades.

(A) Programming Languages: used to create applications, can be compiler or interpreter or both, but this it has to be noted.

(B) Script languages: generic-role interpreters that are used mostly as utilities or data processing (Shell scripting (posix shell, csh, bash, zsh), DOS/WIndows batch files, AWK, etc).

(C) Markup Languages: used for document formatting. They are so many that had 3 big families: *TeX, *roff, *ML. Especially the TeX family had a huge subcategories and subsubcategories tree, for example macro packages that are eTeX specific, or luaTeX or pstricks, etc. Add to this minor formats (markdown, bbcode, etc)

(D) Utilities/Tools: macro/script languages that are used for specific role applications, as script or as configuration files (make, m4, curl, bc, sed, gema, matlab, etc).

(E) Data formats: (JSON, CSV, vCard, ldiff, etc).

(F) Other: in case it does not fit somewhere ;-)

(*)
A new category or at least a useful information is also the languages that products output only in JavaScript/WebAssembly instead of binary code or bytecode/pcode (Java/UCSD Pascal style). I have no idea if they had to be noted as script languages...

Take a look on: [99bottles](http://99-bottles-of-beer.net/abc.html)

**Comment by divayprakash** [comment]
@nereusx Could you please explain your rationale behind this change? As far as I can understand, the link you referenced does not make any such distinction.

**Comment by divayprakash** [comment]
@adambard Thoughts?

**Comment by adambard** [comment]
I simply don't think this is important. The index page doesn't really get much traffic, since most people come via search engines to the page they care about in particular, or at least know what they're searching for and can use ctrl+f (because this site is for programmers)

**Comment by divayprakash** [comment]
Agreed. I'm closing this issue accordingly.
