### ISSUE TITLE
[python/it] Downloading file in italian

### ISSUE THREAD

**Issue by kevinseirey** [adambard/learnxinyminutes-docs#2784]
I'm a brazilian user and when I click in the "get code" link (https://learnxinyminutes.com/docs/files/learnpython.py) inside the python tutorial (https://learnxinyminutes.com/docs/python/), it downloads me the file in italian language.

e.g.:
```
# E' possibile importare il modulo "division" (vedi la sezione 6 di questa guida, Moduli)
# per effettuare la divisione normale usando solo '/'.
from __future__ import division
```

I wanted it in english, or at least, in portuguese.

**Comment by Oire** [comment]
@kevinseirey, could you please check if it is fixed now? BTW, there is a Brazilian Portuguese translation of the Python tutorial.
