### ISSUE TITLE
[perl/en] "Get the code" link downloads polish code

### ISSUE THREAD

**Issue by Grinnz** [adambard/learnxinyminutes-docs#2829]
The "Get the code" link on https://learnxinyminutes.com/docs/perl/ links to the polish version of the code, visible at https://learnxinyminutes.com/docs/pl-pl/perl-pl/. Maybe because it is not using a different filename?

**Comment by Grinnz** [comment]
Also I wanted to ask, what is the intention with "get the code". The code on the perl page doesn't currently compile for several reasons, I can fix most of them with a PR, but the examples of reading from an input file and putting code in a separate module file would be difficult to get to run.

**Comment by Oire** [comment]
Fixed via #2831.
