### ISSUE TITLE
[edn/en] Initial description is inaccurate

### ISSUE THREAD

**Issue by jdjohnston** [adambard/learnxinyminutes-docs#2843]
The sentence "The notation is used internally by Clojure to represent programs." should be deleted or completely rewritten. Per https://github.com/edn-format/edn, "edn is an extensible data notation." Data only, no code. It is intentionally a _subset_ of the full Clojure syntax, partly to ensure that it represents only data. Secondly, Clojure doesn't use any textual format for programs "internally". The Clojure reader (https://clojure.org/reference/reader) recognizes the full Clojure syntax and produces data structures, some of which happen to be code.

**Comment by Oire** [comment]
@jdjohnston, could you please send a pull-request as you know what needs to be changed? Thanks!

**Comment by jdjohnston** [comment]
@Oire, I can try. Git is not my best tool. If I understand correctly: fork, clone, change file, commit, submit PR. Sound about right?

**Comment by Oire** [comment]
@jdjohnston, yepp, but I'd suggest adding branch: fork (click that Fork button, you know), clone `https://github.com/jdjohnston/learnxinyminutes-docs`, then (from the repo folder): `git checkout -B fix-2843` (or any other branch name), change, commit, `git push --set-upstream origin fix-2843`, then submit a PR. If you need any help, please feel free to ask, me or other members will help you with pleasure.

**Comment by jdjohnston** [comment]
Well, here's my first GitHub pull request. Please, be kind. :)
https://github.com/adambard/learnxinyminutes-docs/pull/2844

**Comment by jdjohnston** [comment]
I see the PR was approved, so we can consider this issue closed

**Comment by jdjohnston** [comment]
Sorry, I prematurely thought the PR had been accepted. Hence the close and reopen. :(

**Comment by Oire** [comment]
Closed via #2844. Thanks @jdjohnston!
