### ISSUE TITLE
[c/en] Unnecessary growth of namespace with `typedef`

### ISSUE THREAD

**Issue by noncombatant** [adambard/learnxinyminutes-docs#2849]
```
typedef struct node
{
    int val;
    struct node *next;
} Node;
```

It's a little-known factoid :) that this is legal:

```
typedef struct Node
{
    int val;
    struct Node *next;
} Node;
```

That way, you don't have to have both `Node` and `struct node` in your namespace. It's a minor point — not an actual bug — but I prefer this kind of declaration.

**Comment by adambard** [comment]
👍
