### ISSUE TITLE
[awk/en] Local variable in "arithmetic_functions" is titled "localvar" not "d"

### ISSUE THREAD

**Issue by Throne3d** [adambard/learnxinyminutes-docs#2859]
In the comments near the start of the function:

```
function arithmetic_functions(a, b, c,     localvar) {
    …
    # between actual function parameters and local variables. In this example,
    # a, b, and c are actual parameters, while d is merely a local variable.
```

There's no `d` in the declaration – presumably it's referring to `localvar` and that was previously named `d` to fit with the sequence?

Mostly unrelatedly: it might be worth stating if division between integers is commonly treated as integer division? (It mentions it's like in C and friends, so I assume division between integers *is* commonly integer division, but it may be worth mentioning that in a comment after it, like how `%` and `^` are briefly explained. I'm not sure this is really a big enough issue to create a separate issue for it?)

**Comment by prertik** [comment]
Can you submit a pull request regarding this issue?

**Comment by Throne3d** [comment]
Oops, sorry – somehow I missed this comment.

Thank you for addressing it!
