### ISSUE TITLE
[Markdown/fr] Il manque les références des liens avec référence

### ISSUE THREAD

**Issue by boissonnfive** [adambard/learnxinyminutes-docs#2864]
Bonjour,
il manque les références en dessous des exemples de liens avec référence.
Précisément, il manque les lignes suivantes :

`[link1]: http://link1.org
[foobar]: http://www.foobar.com`

Idem pour les images avec référence.

**Comment by Oire** [comment]
@boissonnfive, merci pour le message. Pourriez-vous ouvrir un pull-request pour corriger ça? Merci!

**Comment by divayprakash** [comment]
Closed in #3302.
