### ISSUE TITLE
racket

### ISSUE THREAD

**Issue by jiangtaoQ** [adambard/learnxinyminutes-docs#2865]
Make sure the issue title is prepended with '[language/lang-code]' if the language is
already on the site.
If it's a request for a new language, use: '[Request] [language/lang-code]'

Issues are always welcome. If you are able and willing, we welcome any pull requests
as this is a community powered project.

**Comment by Oire** [comment]
@jiangtaoQ, sorry, what's the issue?

**Comment by Oire** [comment]
The issue is unclear, closing.
