### ISSUE TITLE
[solidity/en]

### ISSUE THREAD

**Issue by VanijaDev** [adambard/learnxinyminutes-docs#2873]
// Structs and enums
struct Bank {
    address owner;
    uint balance;
}
Bank b = Bank({
    owner: msg.sender,
    balance: 5
});
// or
Bank c = Bank(msg.sender, 5);

**c.amount = 5; // set to new value**

Did you mean: **c.balance = 5** ?

**Comment by Oire** [comment]
@VanijaDev, thanks!
