### ISSUE TITLE
[Forth/en] tuck definition

### ISSUE THREAD

**Issue by cameyo42** [adambard/learnxinyminutes-docs#2884]
current:
1 2 3 4 tuck   \ duplicate the top item **into** the second slot:      1 2 4 3 4 ok
suggested:
1 2 3 4 tuck   \ duplicate the top item **below** the second slot:      1 2 4 3 4 ok

**Comment by Oire** [comment]
@cameyo42, could you please send a pull request? Thanks!

**Comment by jgjadaoag** [comment]
@Oire would it be alright if I pick this up?

**Comment by prertik** [comment]
@jgjadaoag Sure. Go for it!

**Comment by cameyo42** [comment]
Thanks.

2017-10-15 14:38 GMT+02:00 Pratik Karki <notifications@github.com>:
