### ISSUE TITLE
[nix/en]  example of "a ? b "

### ISSUE THREAD

**Issue by teto** [adambard/learnxinyminutes-docs#2893]
I was given on nix channel this tip and when I looked for the a . b syntax, I could not find it
`  Y = if (super.pkgs ? X) then ... else null;`

I am not sure what it means, I would say `a ? b returns true if b in a`

**Comment by Oire** [comment]
@chris-martin, do you have any ideas on this? Thanks!

**Comment by chris-martin** [comment]
I just ran this through the REPL and it seems indeed that `a ? b` tests whether the key `b` is present in the set `a`.

```
nix-repl> let x = { a = 1; }; in (x ? a)
true

nix-repl> let x = { a = 1; }; in (x ? b)
false
```

**Comment by teto** [comment]
cool thanks !
