### ISSUE TITLE
[tcl/en] Syntax highlighting problem

### ISSUE THREAD

**Issue by loxaxs** [adambard/learnxinyminutes-docs#2912]
Page: https://learnxinyminutes.com/docs/tcl/

Syntax highlighting detects a string beginning on the line:
```
proc greet greeting\ name return\ \"\$greeting,\ \$name!\"
```
But it does not detect a string end.

Solution: add a comment containing a single `"`:
```
proc greet greeting\ name return\ \"\$greeting,\ \$name!\"
# "
```

**Comment by prertik** [comment]
Do you want to work on it?
