### ISSUE TITLE
[docs/asymptotic-notation] A slight error in little-o and little-omega

### ISSUE THREAD

**Issue by peey** [adambard/learnxinyminutes-docs#3006]
There's an inconsistency on this page [/docs/asymptotic-notation/](https://learnxinyminutes.com/docs/asymptotic-notation/)  in the sections on small-o and small-omega

>f(n) is o(g(n)), if for some real constants c (c > 0) and n0 (n0 > 0), f(n) is < c g(n) for every input size n (n > n0).

should be  "f(n) is o(g(n)), if for **all** real constants c (c > 0) and n0 (n0 > 0), f(n) is < c g(n) for every input size n (n > n0)."

and 

> f(n) is ω(g(n)), if for some real constants c (c > 0) and n0 (n0 > 0), f(n) is > c g(n) for every input size n (n > n0).

should be  "f(n) is ω(g(n)), if for **all** real constants c (c > 0) and n0 (n0 > 0), f(n) is > c g(n) for every input size n (n > n0)."

as both the paragraphs say in the next line itself.

**Comment by divayprakash** [comment]
@peey Thank you for reporting this! I wrote this page originally so I can check the content. Will fix as required.

**Comment by divayprakash** [comment]
@peey You're absolutely right. Thanks!

@prertik Fixed in #3188
