### ISSUE TITLE
[request] we want to learn human languages XD

### ISSUE THREAD

**Issue by zzz6519003** [adambard/learnxinyminutes-docs#3007]

**Comment by prertik** [comment]
What about this @adambard ?

**Comment by adambard** [comment]
A neat idea, but could probably be a separate website. I'll reserve judgement on whether or not it's a good idea until I see an example, but in any case, until someone actually bilingual contributes a LXIYM-style human language guide, there's not much I can do about it.

**Comment by wboka** [comment]
I like this idea. I'll work on a quick prototype today and send a link when I have something.

**Comment by wboka** [comment]
I think this project deserves its own repository. I have one started at https://github.com/wboka/learnxinyminutes-language-edition if anyone is interested. I think some linking between the projects would be a good idea 👍 . @adambard does this sound good to you? I don't want to steal this out from under you. 

If we want to separate the two projects, I suggest moving this discussion to the new project to avoid cluttering up this code related project.

Here's the link to a quick prototype site using Jekyll and GitHub: https://wboka.github.io/learnxinyminutes-language-edition/

**Comment by adambard** [comment]
Go right ahead! I think you might need to shore up those tutorials before there's a lot of value to be had cross-linking though ;)

**Comment by divayprakash** [comment]
Great work @wboka 

@adambard I'm removing this from hacktoberfest issues. Leaving it open now as a reminder for a possible cross-linking effort in the future.
