### ISSUE TITLE
[c++/en] possible correction.

### ISSUE THREAD

**Issue by JevinJ** [adambard/learnxinyminutes-docs#3009]
// C standard headers are available in C++,
// but are prefixed with "c" and have no .h suffix.
#include <cstdio>

From what I've read this is backwards, C standard headers have the .h suffix eg.(math.h,  stdio.h,  time.h, etc) and C++ headers are prefixed with c(cmath,  cstdio,  ctime).

**Comment by divayprakash** [comment]
@JevinJ Feel free to make a PR for the same.

**Comment by mbiondi17** [comment]
I've opened a [PR for this issue](https://github.com/adambard/learnxinyminutes-docs/pull/3305)

**Comment by divayprakash** [comment]
Closed in #3305.
