### ISSUE TITLE
[Java/ua] Punctuation issue.

### ISSUE THREAD

**Issue by StageClear** [adambard/learnxinyminutes-docs#3013]
![screenshot_12](https://user-images.githubusercontent.com/33164148/33313561-b4c2ce28-d433-11e7-81b9-dce804dd905a.png)

https://learnxinyminutes.com/docs/uk-ua/java-ua/
Missing a hyphen.

**Comment by prertik** [comment]
Can you send a pull request regarding this?

**Comment by divayprakash** [comment]
Issue has been fixed.
