### ISSUE TITLE
[Java/ua]  Mistake in the translated word.

### ISSUE THREAD

**Issue by StageClear** [adambard/learnxinyminutes-docs#3015]
![screenshot_15](https://user-images.githubusercontent.com/33164148/33314368-18b9428e-d436-11e7-9fe7-8e01c2ba89d2.png)

It must be "Понеділки" instead of "Понеділкі".
https://learnxinyminutes.com/docs/uk-ua/java-ua/
/*
Guys, i'm new to here & i'm just practicing. But i don't want to flood with such a simple issues. So can anyone tell me if i can merge it all in one issue? For example "[Java/ua] Punctuation issues" and list of all of them.
*/

**Comment by prertik** [comment]
Can you send a pull request regarding this?

**Comment by PerrySetGo** [comment]
Please see my [PR #3168](https://github.com/adambard/learnxinyminutes-docs/pull/3168)

**Comment by divayprakash** [comment]
Issue fixed in #3168.
