### ISSUE TITLE
[javascript/ua] Mistakes in text.

### ISSUE THREAD

**Issue by StageClear** [adambard/learnxinyminutes-docs#3016]
![screenshot_01](https://user-images.githubusercontent.com/33164148/33315553-a8c0bb84-d439-11e7-9b63-77ce98997c40.png)
Must be "працюють" instead of "працють"

![screenshot_02](https://user-images.githubusercontent.com/33164148/33315788-61c8c2c0-d43a-11e7-86fa-62a51aa7f231.png)
Must be "обов’язкові" instead of "обов’язкі"
https://learnxinyminutes.com/docs/uk-ua/javascript-ua/

**Comment by prertik** [comment]
Can you send a pull request regarding this?

**Comment by PerrySetGo** [comment]
pls see my PR [#3168](https://github.com/adambard/learnxinyminutes-docs/pull/3168)

**Comment by divayprakash** [comment]
Issue fixed in #3168.
