### ISSUE TITLE
[Ruby/en] Amendments to unclear instructions

### ISSUE THREAD

**Issue by shividhar** [adambard/learnxinyminutes-docs#3042]
The `Combined comparison operator` line can be confusing because it is not a well-known operator. The comments could be formatted this way.
```
1 <=> 10 #=> -1 => 1 < 10 
10 <=> 1 #=> 1 => 10 > 1
1 <=> 1 #=> 0 => 1 == 1
```

On the `Reverse an Array` line additional information can be given about the example `a.reverse! #=> [3,2,1]`. The `!` at the end of the reverse is a writeback, but that is not made clear.
An alternate approach.
```
# Reverse an Array
# Returns a new reversed array
[1,2,3].reverse #=> [3,2,1]
# Reverses self in place.
a=[1,2,3]
a.reverse! #=> [3,2,1]
```

**Comment by prertik** [comment]
Hi! Do you want to send a pull request on this?
