### ISSUE TITLE
[matlab/zh-cn]

### ISSUE THREAD

**Issue by magicalwz** [adambard/learnxinyminutes-docs#3054]
建议
char(a(1))  % ans = one - 返回一个字符串
->
a{1}  % ans = one - 返回一个字符串

可以对cell的两种索引方式进行对比

transpose(A)  % 矩阵转置，等价于 A'
should be
transpose(A)  % 矩阵转置，等价于 A.'

加点为不共轭转职

**Comment by prertik** [comment]
Hi! Do you want to send a pull request?

**Comment by inkydragon** [comment]
@perlilja 
@magicalwz suggest that 
- `char(a(1))` should be replace by `a{1}`, for the latter is more simple ([Line 128](https://github.com/adambard/learnxinyminutes-docs/blame/master/matlab.html.markdown#L128))
- `transpose(A)` is equivalent to `A.'`. They all represent "the nonconjugate transpose".
  and `ctranspose(A)` is equivalent to `A'` which "Complex conjugate transpose"
  So, In chinese version, there is an **error**.

I've fixed chinese version' issues in #3194 . 

for English and other version ([Line 224](https://github.com/adambard/learnxinyminutes-docs/blame/master/matlab.html.markdown#L224))
```
transpose(A) % Transpose the matrix, which is the same as:
A one
ctranspose(A) % Hermitian transpose the matrix
```
and the second line cause an error, I think it's maybe a part of the comment.
Maybe correct to
```
transpose(A) % Transpose the matrix, which is the same as: A.'
ctranspose(A) % Hermitian transpose the matrix
```

@prertik So, Should I fix the second one in one pr for all other version (en/it-it/pt-br)?

**Comment by prertik** [comment]
Sure, you can fix those in a single PR with of course different commits.

**Comment by divayprakash** [comment]
@prertik PR is #3199

**Comment by prertik** [comment]
@divayprakash, if it looks good to you. Go for it.
