### ISSUE TITLE
[Request][Reason]

### ISSUE THREAD

**Issue by tjfwalker** [adambard/learnxinyminutes-docs#3108]
I'd love to see [Reason](https://reasonml.github.io/) —aka ReasonML— on the site.

**Comment by ian-bertolacci** [comment]
If you have the ability to write the tutorial, feel free to do so and they'll pull it in.
Usually 'doing it yourself' is the best way to get things up here.

Even if you don't know the language, I find writing tutorials to be a good way to learn it.

**Comment by divayprakash** [comment]
Closed in #3576
