### ISSUE TITLE
[Lambda Calculus] Missed associativity of parentheses

### ISSUE THREAD

**Issue by elhaddadyacine** [adambard/learnxinyminutes-docs#3114]
Hi,
In [Lambda Calculus Doc](https://learnxinyminutes.com/docs/lambda-calculus/) inside **Evaluation** section the formula :

- (λx.λy.λz.xyz) is equivalent to f(x, y, z) = x(y(z)) 

should be 

- (λx.λy.λz.xyz) is equivalent to f(x, y, z) = ((x y) z)

because the associativity of parentheses is left in λ-calculus.

**Comment by sim642** [comment]
There's a similar problem below:

> Note: IF a b c is essentially saying: IF(a(b(c)))

Tbh, I'm not even sure what new that is trying to say or how it would be anyhow helpful to understanding IF.

**Comment by elhaddadyacine** [comment]
Thanks for your replay :+1: 
But it's not updated yet :disappointed:

**Comment by ian-bertolacci** [comment]
They prefer if you can make the changes and file a pull request.

**Comment by chriszimmerman** [comment]
I opened https://github.com/adambard/learnxinyminutes-docs/pull/3271 to address this issue.

**Comment by divayprakash** [comment]
Closed in #3271
