### ISSUE TITLE
[python3/en] Correction regarding example in Tuples in python3

### ISSUE THREAD

**Issue by ValentinaRodrigues** [adambard/learnxinyminutes-docs#3130]
There is the following comment and example in the Tuples section in Python3:

"#Tuples are created by default if you leave out the parentheses"
`d, e, f = 4, 5, 6`

Shouldn't the example be :
`d = 4, 5, 6`

which gives us output as intended:
`d = ( 4, 5, 6)`

Because if we do 
`d, e, f = 4, 5, 6`

we get 
```
d = 4
e = 5 
f = 6
```
which does not explain the statement: "Tuples are created by default if you leave out the parentheses" since the variables are treated as integers rather than a tuple.

**Comment by prertik** [comment]
You're right. Do you want to send a pull request?

**Comment by ValentinaRodrigues** [comment]
I have sent a pull request, however, I forgot to refer it to the issue. #3132

**Comment by divayprakash** [comment]
@prertik @ValentinaRodrigues I don't think this is correct. Please see the next lines in the file -

```
d, e, f = 4, 5, 6 
# Now look how easy it is to swap two values
e, d = d, e  # d is now 5 and e is now 4
```

The intent here was the creation of 3 tuples called d (value 4), e (value 5) and f (value 6) and then a swap is demonstrated. Also, the lines above this further clarify the situation -

```
# You can also do extended unpacking
a, *b, c = (1, 2, 3, 4)  # a is now 1, b is now [2, 3] and c is now 4
# Tuples are created by default if you leave out the parentheses
```

**Comment by divayprakash** [comment]
The section is meant to demonstrate unpacking tuples into values.

**Comment by divayprakash** [comment]
> Tuples are created by default if you leave out the parentheses

This refers to the tuple created by `4, 5, 6`.

The section is meant to demonstrate unpacking tuples into values. Thus the fact that `d, e, f` are integers is what is being demonstrated.

**Comment by divayprakash** [comment]
> I just felt that the example does not explain the statement above if you look at it independently. It is kind of misleading.

I agree. If you'd like to clarify that in the comment, please make a PR for the same.

Thank you for pointing this out!

**Comment by prertik** [comment]
@ValentinaRodrigues, I'll be reopening this issue. You can send a PR if you feel it is misleading. @divayprakash please, help @ValentinaRodrigues get a good PR to merge. This is a community driven project and whatever the community feels is wrong, is wrong here.
