### ISSUE TITLE
Site is not being updated..

### ISSUE THREAD

**Issue by prertik** [adambard/learnxinyminutes-docs#3136]
The website isn't being updated even after merging pull requests. The references are #3094 and #3133.

**Comment by prertik** [comment]
Great!

**Comment by prertik** [comment]
Hi @adambard, this problem still persists.

**Comment by adambard** [comment]
Yup, having some cron issues. I've been running it manually every so often, but I'll keep this open until I can actually get it automatically building again

**Comment by aloisdg** [comment]
@adambard Would it be possible to add CI/CD to this project?

**Comment by divayprakash** [comment]
@adambard Seems to be working fine now. I just merged a few PRs in and the changes are being reflected on the site.

**Comment by prertik** [comment]
yeah, it's working now @divayprakash. Looks like you're really clearing the PRs and Issues. Thanks and keep on keepin' on! :+1:

**Comment by divayprakash** [comment]
@prertik Just jump in whenever you can, in the meantime I'll try and hold the fort down!

**Comment by divayprakash** [comment]
Closing this issue for now. We can reopen this if the problem resurfaces.

**Comment by divayprakash** [comment]
@adambard Seems this issue is back. I merged PR #3218 to fix an issue introduced by #3139 in commit 9882d5f over 2 hours ago but the site has not been updated yet.

**Comment by adambard** [comment]
A hopefully transient permissionss issue, seems to be resolved for the meantime.
