### ISSUE TITLE
Change the shebang line in the bash tutorial

### ISSUE THREAD

**Issue by archatas** [adambard/learnxinyminutes-docs#3154]
Wouldn't it make sense to change the shebang line to:

```
#!/usr/bin/env bash
```

This way it should be working cross-platform.

**Comment by ian-bertolacci** [comment]
Not a bad idea.
Can you make the changes and make a pull request?

**Comment by dtkerns** [comment]
Half in jest, if your distro doesn't have a /bin/bash, you should choose a different distro.

**Comment by divayprakash** [comment]
Closed in 6f0aec0 under #3167.
