### ISSUE TITLE
[matlab/zh-cn] Two minor typo

### ISSUE THREAD

**Issue by jerrylususu** [adambard/learnxinyminutes-docs#3176]
\- profile **of**  % 关闭 profile 代码分析工具
\+ profile **off**  % 关闭 profile 代码分析工具

\- sqrtm(A)  % 对矩阵整体做**开放**运算（即试图求出一个矩阵，该矩阵与自身的乘积等于 A 矩阵）
\+ sqrtm(A)  % 对矩阵整体做**开方**运算（即试图求出一个矩阵，该矩阵与自身的乘积等于 A 矩阵）
（P.S. 开放-Open   开方-Taking square root）

**Comment by inkydragon** [comment]
其实你可以直接提 pr 的。
我把这个 issue 和另一个合并提 pr 了 #3194
