### ISSUE TITLE
Letsencrypt certificate has expired

### ISSUE THREAD

**Issue by pingiun** [adambard/learnxinyminutes-docs#3177]
## Is this a major issue that you cannot fix?
Yes, I cannot update the certificate for the site.

<img width="896" alt="screen shot 2018-08-05 at 11 39 49" src="https://user-images.githubusercontent.com/1576660/43684654-5a836810-98a4-11e8-8252-41e918659fe6.png">

**Comment by adambard** [comment]
Sorry, was away yesterday!

**Comment by pingiun** [comment]
Thanks for fixing this! Maybe you can set a cronjob for renewing? Something like `certbot renew --post-hook="systemctl reload nginx"`

**Comment by adambard** [comment]
In fact my cron job did run, I just forgot to reload nginx after. Thanks for the post hook tip, that should help!
