### ISSUE TITLE
YAML frontmatter errors

### ISSUE THREAD

**Issue by divayprakash** [adambard/learnxinyminutes-docs#3206]
I was reading #2120 looking for bugs to fix and came across #2832. As @prertik pointed out there, there are still many bugs that pop up on running `frontmatter_checker.py` -

```
Checking ../source/docs/es-es\csharp-es.html.markdown
ERROR: Error in frontmatter

Checking ../source/docs/fr-fr\java-fr.html.markdown
ERROR: Filename lacks language code suffix

Checking ../source/docs/pt-br\solidity-pt.html.markdown
ERROR: Filename lacks language code suffix

Checking ../source/docs/README.markdown
WARN: Could not read frontmatter.

Checking ../source/docs/tr-tr\c++-tr.html.markdown
ERROR: Filename lacks language code suffix

Checking ../source/docs/tr-tr\git-tr.html.markdown
ERROR: Filename lacks language code suffix
```

**Comment by divayprakash** [comment]
@adambard I'd love to be a collaborator on this project. I've been working on it for some time now and know it quite well. If possible, I'd love to have commit access to the repo to be able to fix bugs such as this one. Cheers!

**Comment by divayprakash** [comment]
Anyways, I'll be making a PR fixing this issue soon.

**Comment by divayprakash** [comment]
PR #3207

**Comment by adambard** [comment]
@divayprakash Great idea! You now have the power.
