### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by divayprakash** [adambard/learnxinyminutes-docs#3278]
![image](https://user-images.githubusercontent.com/11337492/46762002-91cc3a80-ccf3-11e8-8dfb-bcace88dca47.png)

@adambard As can be seen in the image above, the project currently has 10 branches, out of which 8 can be deleted without any issue, leaving out `es2015` as it is currently open in PR #2858 and of course `master`. Would it be ok to delete these?

**Comment by adambard** [comment]
Go right ahead!

**Comment by divayprakash** [comment]
Done!
