### ISSUE TITLE
[sql/en] SQL mode pretty messy

### ISSUE THREAD

**Issue by bobdc** [adambard/learnxinyminutes-docs#3386]
I was very happy to see (as I tweeted at https://twitter.com/bobdc/status/1058000527169077249) the SQL page on learnxinyminutes.com, but https://learnxinyminutes.com/docs/sql/ reminds me of why I originally started the code part with \`\`\` instead of \`\`\`sql. It looked great in github after you had me add the "sql" to that, but in bitbucket and on https://learnxinyminutes.com/docs/sql/ the keywords in comments are bolded and it shows any text between pairs of apostrophes (typically, contractions in comments) in red, sometimes treating code as comments and comments as code. I tried changing the apostrophes to "\\\'" in the comments (in my bitbucket copy) but that didn't help. (Apparently, it does in these comments!) 

Do you know another way to escape apostrophes for the markdown interpreter on learnxinyminutes.com? Otherwise I think we'd be better off removing the sql from \`\`\`sql and giving up on keyword highlighting, which it was doing to the comments as well when the sentences just happened to have words that are SQL keywords.

**Comment by divayprakash** [comment]
@bobdc I agree with you. The code formatting on the site looks pretty terrible right now. I'll look for a solution for escaping apostrophes, failing which we can just remove sql from ```sql.

**Comment by divayprakash** [comment]
@adambard There seems to be some issue here that I just can't figure out. The [SQL](https://github.com/adambard/learnxinyminutes-docs/blob/master/sql.html.markdown) doc looks like this on GitHub -

![screencapture-github-adambard-learnxinyminutes-docs-blob-master-sql-html-markdown](https://user-images.githubusercontent.com/11337492/47965157-9fae7a80-e069-11e8-91f8-391a84278ded.png)

It's properly formatted and code highlighting works perfectly. However, on the [site](https://learnxinyminutes.com/docs/sql/), this is what it looks like -

![screencapture-learnxinyminutes-docs-sql](https://user-images.githubusercontent.com/11337492/47965184-ef8d4180-e069-11e8-99d7-24b491929e34.png)

Code highlighting is completely broken. And this is while using `` ```sql `` at the beginning of the code block to specify the document language. Any ideas on how we could fix this? Also see @bobdc's comment above on the issue.

**Comment by bobdc** [comment]
I agree that while the github highlighting looks great, on the site the \`\`\` version without "sql" following it seems like the best option for now.

**Comment by adambard** [comment]
Seems to be sorted. I swapped out the double quotes for single quotes too, since those suffer from a similar issue.
