### ISSUE TITLE
[ansible] Link broken (404)

### ISSUE THREAD

**Issue by reinefjord** [adambard/learnxinyminutes-docs#3388]
The link to the Ansible docs is broken and returns a 404 Not Found. To reproduce, visit https://learnxinyminutes.com/docs/ansible/.

**Comment by PatMyron** [comment]
latest commit to that file: https://github.com/adambard/learnxinyminutes-docs/commit/70a2200201f4d3d91ca9f08902dd16d653b10cd2

**Comment by divayprakash** [comment]
@adambard Please take a look at what's happening here. I can't figure out why the page isn't being built.

**Comment by divayprakash** [comment]
Same issue with the [Processing](https://learnxinyminutes.com/docs/processing) page also.
