### ISSUE TITLE
[general] - how to build

### ISSUE THREAD

**Issue by z3ugma** [adambard/learnxinyminutes-docs#3396]
When creating a pull request, is there a way to run a local dev version of the site with its custom scripting and 80 character requirements?

I'm especially interested in knowing if there's a syntax highlight for my language (M/MUMPS) or if I have to write one

**Comment by z3ugma** [comment]
Alternatively can we add instructions to CONTRIBUTING.md on how to build locally?

**Comment by z3ugma** [comment]
Great, thank you! In the meantime I'll keep working on the language tutorial page.

**Comment by divayprakash** [comment]
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by divayprakash** [comment]
This is the link where you can check syntax highlighting support for any language. According to this, Mumps or M is supported.

**Comment by divayprakash** [comment]
PR #3397.
