### ISSUE TITLE
 [Stylus/pt-br] Stylus is not listed at https://learnxinyminutes.com/

### ISSUE THREAD

**Issue by salomaosnff** [adambard/learnxinyminutes-docs#3444]
I recently did a pull request with the new stylus language. the pull request was accepted but has not yet appeared on the website.

**Comment by divayprakash** [comment]
@adambard Please check.

**Comment by adambard** [comment]
The site uses the english-language articles as its index, so for now I've added a stub for the english version to allow the pt-br one to be discovered .I also changed the highlighting to scss, stylus support isn't present yet it seems.

After doing those two things the page is available on the site!
