### ISSUE TITLE
[c++/fr] sizeof(char) == sizeof(int)

### ISSUE THREAD

**Issue by wantra2** [adambard/learnxinyminutes-docs#3457]
hello,
it is said in the c++ french tutorial that, **in c**, sizeof(char) == sizeof(int). According to me it is rather sizeof(char) = 1 and sizeof(int) = 4 (most of the time).

**Comment by Menelion** [comment]
@wantra2 Thanks for your report. What about other languages? It seems, English tutorial states the same. I'm not a C++ guy, so, @geoffliu, could you please investigate?

**Comment by geoffliu** [comment]
@wantra2 The doc is correct, and so are you. :)

Your confusion is exactly what those two lines are trying to clear up. So in C:
```
sizeof(char) == 1
sizeof(int) == ?? // architecture dependent
sizeof('a') == sizeof(int) // type of 'a' is actually int!
```

This is there for historical reasons, and people decided to fix it when C++ came around, so that type of `'a'` went back to `char`
