### ISSUE TITLE
typo in lambda calculus/Boolean Logic

### ISSUE THREAD

**Issue by Lixinyi-DUT** [adambard/learnxinyminutes-docs#3487]
Does `a NOT b` mean `NOT a`? The later makes more sense.

**Comment by divayprakash** [comment]
Effectively yes, but the explanation given says the same -
> a NOT b is equivalent to: λa.IF a F T

`λa.IF a F T` equates to saying

```
if (a)
	return False
else
	return True
```

**Comment by Lixinyi-DUT** [comment]
> Effectively yes, but the explanation given says the same -
> 
> > a NOT b is equivalent to: λa.IF a F T
> 
> `λa.IF a F T` equates to saying
> 
> ```
> if (a)
> 	return False
> else
> 	return True
> ```

I mean `NOT` is traditionally an unary operator, so `a NOT b` could be misunderstood as `a != b`, which is confusing and ambiguous.

I completely agree on the explanation that `NOT a` can be expressed with such an if statement.

**Comment by divayprakash** [comment]
@maxsun @yanhh0 Could you please weigh in on this?

**Comment by maxsun** [comment]
@divayprakash @Lixinyi-DUT Sorry, you are correct - I think it should be `NOT a`
