### ISSUE TITLE
[Request] Ada

### ISSUE THREAD

**Issue by aloisdg** [adambard/learnxinyminutes-docs#3493]

**Comment by perseoGI** [comment]
How is it going?

**Comment by Zireael07** [comment]
Thirding the request

**Comment by Lucretia** [comment]
Added #4821

**Comment by Lucretia** [comment]
I have completed the PR and there is a branch, can this issue be updated to reflect this please?

**Comment by Lucretia** [comment]
The PR has been merged, I think this can be closed.
