### ISSUE TITLE
Where can I get source file for each language?

### ISSUE THREAD

**Issue by 4goodapp** [adambard/learnxinyminutes-docs#3500]
Currently I when I clone the repository, all language are in markdown file. and downloading source code one by one through the web site, well I think there must be an easier way.

**Comment by adambard** [comment]
The source code download is constructed by parsing the markdown files, extracting the source code bits, and concatenating them together.

If you set the learnxinyminutes-site project and run the build script, it will generate the source files, and all you'll need to do is retrieve them from the built site.
