### ISSUE TITLE
[awk/en] Title is Wrong

### ISSUE THREAD

**Issue by oemmerson** [adambard/learnxinyminutes-docs#3514]
This isn't very important but I noticed it:

Page titles for the other languages are specialised e.g. 'Learn c in Y minutes.' However the page title for AWK is 'Learn X in Y Minutes: Scenic Programming Language Tours.'

That title doesn't show up in a search of this repository so I couldn't fix it myself.

Thanks for the site.

**Comment by MikaelKemstedt** [comment]
It is like this for almost all the docs under the "Tools" section. 

Only Qt Framework is different, it shows "Learn c++ in Y Minutes"

**Comment by kevinnls** [comment]
all page titles have now been reformatted to display `X=[language]` as the subtitle  
so close #3514 can be~

**Comment by digimeas** [comment]
Hi!  Except for (at least) qt still says c++. Its "language: c++".

**Comment by kevinnls** [comment]
my sincere apologies @ode79 and @MikaelK98
i had earlier misunderstood what you were pointing out
(confused between <title> and heading)

thank you @digimeas for bringing this back up! 😃

#4298 should fix this when merged

**Comment by mribeirodantas** [comment]
This should close this issue: https://github.com/adambard/learnxinyminutes-site/pull/107

**Comment by verhovsky** [comment]
It's right now.
