### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by jonasknobloch** [adambard/learnxinyminutes-docs#3523]
```
echo | openssl s_client -servername learnxinyminutes.com -connect learnxinyminutes.com:443 2>/dev/null | openssl x509 -noout -dates
```
```
notBefore=Jan 27 23:00:12 2019 GMT
notAfter=Apr 27 23:00:12 2019 GMT
```
Seems like the SSL certificate expired yesterday.

**Comment by stefan2904** [comment]
I guess the ACME/certbot renew cronjob is broken ...

**Comment by Lisiadito** [comment]
Not 100% related but I was not sure if I should open a new issue for that. But maybe consider using the `https` instead of the `http` version of the link to learnxinyminutes in the repository description.

**Comment by celtic-coder** [comment]
The certificate now looks OK: https://www.ssllabs.com/ssltest/analyze.html?d=learnxinyminutes.com. 

However, there is an issue with the server on which it is installed. A sysadmin would need to look at the "nginx" solution mentioned here: https://weakdh.org/sysadmin.html

**Comment by divayprakash** [comment]
> The certificate now looks OK: [ssllabs.com/ssltest/analyze.html?d=learnxinyminutes.com](https://www.ssllabs.com/ssltest/analyze.html?d=learnxinyminutes.com).
> 
> However, there is an issue with the server on which it is installed. A sysadmin would need to look at the "nginx" solution mentioned here: [weakdh.org/sysadmin.html](https://weakdh.org/sysadmin.html)

@adambard Could you take a look at this? Just check the SSL Labs link and it'll show the issue.

**Comment by adambard** [comment]
Status of the cronjob is that the cert is renewed correctly, but nginx reload is failing for some reason. Will address, hopefully before August.

I'm not *too* worried about logjam on this completely static reference site, especially given the demonstrable alertness of our kind users to potential issues, but now that it's been pointed out I guess I'll update the DH params while I'm in there :P

**Comment by ratatoeey** [comment]
doesn't show as expired in firefox.

does it support browsers that have been set to using tls 1.3 as minimum tls version allowed.
----

regards ratatoeey

**Comment by adambard** [comment]
I've just upgraded the server -- TLS 1.3 is now supported.

**Comment by divayprakash** [comment]
@adambard I believe this can be closed now?

**Comment by adambard** [comment]
@divayprakash At least until the next time my cron job fails
