### ISSUE TITLE
[Request] COBOL

### ISSUE THREAD

**Issue by XVilka** [adambard/learnxinyminutes-docs#3529]
Don't laugh, sometimes life makes you do worse things.

**Comment by MikaelKemstedt** [comment]
I'm almost done with this one. 

Need to format it a bit better, 
Add some file statement information,
As well as add some info about intrinsic functions.

**Comment by XVilka** [comment]
Linked PR: https://github.com/adambard/learnxinyminutes-docs/pull/3859

**Comment by verhovsky** [comment]
#3900
