### ISSUE TITLE
[swift/en] returning functions example doesn't use named arguments

### ISSUE THREAD

**Issue by lukepighetti** [adambard/learnxinyminutes-docs#3565]
```swift
// Passing and returning functions
func makeIncrementer() -> ((Int) -> Int) {
    func addOne(number: Int) -> Int {
        return 1 + number
    }
    return addOne
}
var increment = makeIncrementer()
increment(7)
```

I believe the correct syntax for calling the returned function is `increment(number: 7)`. Can someone please confirm?

**Comment by Samasaur1** [comment]
Nope, what's there is correct. `makeIncrementer()` returns a closure, and closures don't have or allow argument labels.

**Comment by Samasaur1** [comment]
(I tested this on Swift 5.3.2, 5.1.3, 5.0.3, 4.2.4, and 4.0.3)

**Comment by lukepighetti** [comment]
Let's close this then.
