### ISSUE TITLE
creating dropdown box and filtering items using yml

### ISSUE THREAD

**Issue by MohammadRahaman** [adambard/learnxinyminutes-docs#3573]
## Is this a major issue that you cannot fix?

YES, I can't apply anything due to this issue!!!!

I am trying to create dropdown box where it display all of the items  but I couldn't find any yml syntax which  supports to filtering items and create a dropdown from where I will select item to build job!! 

**Being a commusnity driven documents of languages and tools,"YOUR" contributions
are also important.
If the issue you're reporting is trivial to report to maintainers why not contribute
to fix it. In that way, you will have contributed to an awesome open-source project.
The changes can be typo fix, fixing of data in examples or grammar fix. If you found it,
why not do it and take full credit for it?**

Make sure the issue title is prepended with '[language/lang-code]' if the language is
already on the site.
If it's a request for a new language, use: '[Request] [language/lang-code]'

Issues are always welcome. If you are able and willing, we welcome any pull requests
as this is a community powered project.

**Comment by divayprakash** [comment]
@MohammadRahaman Could you please explain what exactly you are looking for here?

**Comment by divayprakash** [comment]
Closed due to inadequate information.
