### ISSUE TITLE
[C/en] describing the possibility of implementing object orientation

### ISSUE THREAD

**Issue by LamdaLamdaLamda** [adambard/learnxinyminutes-docs#3583]
Generally its possible to implement the object oriented abstractions in C. For instants **inheritance** or **overloading**. This is widely used in the Linux kernel.
An introducing example would be sufficient.

**Comment by ysads** [comment]
I think I'm aware of the feature you're talking about, but I'm not sure this can be described as "object-oriented abstractions". You mean the structs nesting and so?
Anyways, I think I'll work on some examples for these behaviours.

**Comment by verhovsky** [comment]
I don't think this is necessary.
