### ISSUE TITLE
Nested lists are missing

### ISSUE THREAD

**Issue by KamranAzeem** [adambard/learnxinyminutes-docs#3584]
Your article is missing nested lists. Here is what I suggest adding:

## Code:
```
* list item 1
* list item 2
  * sub-list item 1
  * sub-list item 2
* list item 3
```

## Generates:
* list item 1
* list item 2
  * sub-list item 1
  * sub-list item 2
* list item 3

**Comment by divayprakash** [comment]
Closed due to inadequate information.
