### ISSUE TITLE
[C/de] adding german language

### ISSUE THREAD

**Issue by LamdaLamdaLamda** [adambard/learnxinyminutes-docs#3592]
Translating the english c version to german.

**Comment by caminsha** [comment]
Started to translate C to German.
You can see progress [here](https://github.com/caminsha/learnxinyminutes-docs/blob/de-de/c/de-de/c-de.html.markdown).

Maybe I will need some days for it as it is a quite long article.

**Comment by divayprakash** [comment]
WIP #3839

**Comment by mxschumacher** [comment]
The translation has been merged, thanks @caminsha !
