### ISSUE TITLE
[c/en] link to http://c.learncodethehardway.org/book/ is broken

### ISSUE THREAD

**Issue by paravz** [adambard/learnxinyminutes-docs#3611]
Link at the bottom of C doc is broken: http://c.learncodethehardway.org/book/
The correct location seems to be https://learncodethehardway.org/c/, but there is no free access to the book at that URL, only a link to purchase it.

**Comment by heitorPB** [comment]
in the `make` tutorial there are links for exercises from this book:
- http://c.learncodethehardway.org/book/ex2.html
- http://c.learncodethehardway.org/book/ex28.html

I can't access those links, do you know if they still exist somewhere?

**Comment by divayprakash** [comment]
Fixed in #3683
