### ISSUE TITLE
[Request] Docker

### ISSUE THREAD

**Issue by heitorPB** [adambard/learnxinyminutes-docs#3631]
[Docker](https://www.docker.com/) is a very useful tool. It would be great to have it in Learn X in Y minutes.

**Comment by Atemu** [comment]
Do you mean the docker CLI tool or `Dockerfile`s?

**Comment by heitorPB** [comment]
IMHO it would be nice to start with the CLI, then go to Dockerfiles and
finally cover docker compose. What do you think?

**Comment by divayprakash** [comment]
Closed by #3805
