### ISSUE TITLE
[erlang/en] is_pet(A) when is_dog(A); is_cat(A) -> true; is not possible in erlang

### ISSUE THREAD

**Issue by vfxGer** [adambard/learnxinyminutes-docs#366]
is_pet(A) when is_dog(A); is_cat(A) -> true;
is_pet(A) -> false.

call to local/imported function is_cat/1 is illegal in guard
call to local/imported function is_dog/1 is illegal in guard

The reason for restricting the set of valid expressions is that evaluation of a guard expression must be guaranteed to be free of side effects. http://www.erlang.org/doc/reference_manual/expressions.html (section 7.24)

http://stackoverflow.com/questions/6505213/is-there-a-way-to-use-local-function-in-guard

**Comment by edholland** [comment]
This bug is resolved in master. Please close
