### ISSUE TITLE
[Request] [language/dart-2.x] Current Dart page is the v1.x, add v2.x or replace?

### ISSUE THREAD

**Issue by megatux** [adambard/learnxinyminutes-docs#3674]
I'm not sure how to proceed, I'm almost new here.
The current Dart lang. page is for the old 1.x specification. The 2.x specification is _very_ different, e.g. the type system changed completely. It was a major revamp of the language to be used in the Flutter framework.
I want to update/add the Dart docs. How do I proceed?

**Comment by ram231** [comment]
While the documentation is preferable in the [official docs](https://flutter.dev).
Some people really want to skim/scan the dart syntax.
I would like to participate in updating the documentation.

**Comment by megatux** [comment]
Where/who currently use Dart v1.x? Are still real active users/apps of this version?

**Comment by ram231** [comment]
I don't know that much. Most users have migrated from v1.x to v2.
refer to PR #3820 . I have not yet  included **extension methods**. It's still not ready for stable release according to the Dart Team.

**Comment by ram231** [comment]
UPDATE: I don't know if the author really want to merge my pull request to add additional features to the dart language. It's up to the Dart's documentation found in http://dart.dev

Bye.

**Comment by divayprakash** [comment]
Fix in #3820
