### ISSUE TITLE
[latex/en] Possible misplacement of $ character.

### ISSUE THREAD

**Issue by anakimluke** [adambard/learnxinyminutes-docs#3732]
Line 126 goes
```latex
Here's how you state all x that belong to X, $\forall$ x $\in$ X.
```
where I think it should go as
```latex
Here's how you state all x that belong to X, $\forall x \in X$.
```

See the difference between the original(first) and the modified version(second line):
![image](https://user-images.githubusercontent.com/22756345/67626726-094d0900-f826-11e9-9c38-7485c0d45a32.png)

The proposed modified version looks prettier/*more right* to me, but as I'm new to latex I wanted for someone else to confirm this.

**Comment by AcProIL** [comment]
You are definitely right, $$ have to surround the entire formula.
To be even cleaner, one could use \( and \) as delimiters instead of dollar signs.

**Comment by OrangeNeutron** [comment]
You are definitely right, $$ have to surround the entire formula.
To be even cleaner, one could use ( and ) as delimiters instead of dollar signs.
