### ISSUE TITLE
[language/coq] Coq support was merged, but is not shown on the site

### ISSUE THREAD

**Issue by XVilka** [adambard/learnxinyminutes-docs#3779]
Coq support was merged in the master: https://github.com/adambard/learnxinyminutes-docs/commit/4653df70c36456bd995d846027706641a156683e (PR [#3759](https://github.com/adambard/learnxinyminutes-docs/pull/3759))

But it is not available on the site:

![image](https://user-images.githubusercontent.com/203261/69303410-dc8ae680-0c57-11ea-8ef0-a62230ffe689.png)

**Comment by divayprakash** [comment]
@adambard There is some error in the build on the server. The page builds locally without errors but is not showing up on https://learnxinyminutes.com/

**Comment by adambard** [comment]
Got it, some ruby/bundler version issues. It's up there now!
