### ISSUE TITLE
Information regarding Node?

### ISSUE THREAD

**Issue by flanagansteve** [adambard/learnxinyminutes-docs#3785]
It seems like there's a great JS tutorial. I've done a good bit of JS / React but am totally in the dark on Node, and haven't found a good tutorial.

Does the JS tutorial cover everything you need to know about Node fundamentally, and I just need to invest time in learning the setup / devops of a Node application?

Or would it be worthwhile to do a standalone Node tutorial?

**Comment by verhovsky** [comment]
Dupe of #433
