### ISSUE TITLE
[markdown] Missing content on the website but existing in the source code

### ISSUE THREAD

**Issue by imba-tjd** [adambard/learnxinyminutes-docs#3811]
There are some content exist in source code, and exist after GitHub's rendering, but missing on the website.

![图片](https://user-images.githubusercontent.com/24759802/72214131-32348e80-3537-11ea-9b96-8ac912190b76.png)
https://learnxinyminutes.com/docs/zh-cn/markdown-cn/

![图片](https://user-images.githubusercontent.com/24759802/72214137-48dae580-3537-11ea-89b2-33707a49d747.png)
https://github.com/adambard/learnxinyminutes-docs/blob/master/zh-cn/markdown-cn.html.markdown

The same issue in:
* https://learnxinyminutes.com/docs/it-it/markdown/
* https://learnxinyminutes.com/docs/fr-fr/markdown-fr/

But some others are correct.

**Comment by kevinnls** [comment]
hi @imba-tjd 
has this issue been resolved?
if not, could you please provide line numbers of the source code that are not being rendered

**Comment by imba-tjd** [comment]
Still exists.
https://github.com/adambard/learnxinyminutes-docs/blob/master/zh-cn/markdown-cn.html.markdown#L268

**Comment by kevinnls** [comment]
could you please provide line numbers?
i can only read French of the three languages you have pointed out.

editing the source files on your fork on GH web or opening a local copy of the file in any text editor should give you line numbers

**Comment by imba-tjd** [comment]
L268. See the anchor of the above link

**Comment by imba-tjd** [comment]
or you can search "link1". There should be more than 1 appearance

**Comment by kevinnls** [comment]
thanks. i'll look into it

**Comment by imba-tjd** [comment]
Not at all. I just realized by default there **isn't** a "Display the source blob" button and the anchor I gave won't auto-scroll to the position. It's because I installed a browser extension (Refined GitHub).

![图片](https://user-images.githubusercontent.com/24759802/89730919-a60b2b00-da75-11ea-89b1-83cf7361ae95.png)

**Comment by kevinnls** [comment]
ooo fancy. 
_adds it to list of things i've swiped from you along with [stats card](//github.com/anuraghazra/github-readme-stats)_
***
anyway, i made the changes on `fr-fr` but i'm not able to figure out how to do it for `zh-cn` i tried making the changes, but it breaks other portions of the page. i feel i may be missing some portion of the code because i'm unfamiliar with the script

so here's the fix i did. could you check it for `zh-cn`

```
<div class="highlight"><code><pre>

<!--insert link syntaxes 
formatting text portions
with span and associated class--> 

</pre></code></div>
```

the `<span>` classes are as follows
- [**link text**] 
   - "nv"
- [link][**link ref**] 
   - "ss"
- \[link\](**url**)` 
   - "sx"
- [link](url **"tooltip"**) 
   - "nn"

**Comment by imba-tjd** [comment]
Unfortunately I'm not able to give you a review because I have little knowledge about frontend. But  I don't think the source file needs changing unless there is indeed a markdown issue. So I won't choose your way to fix this. 😢

**Comment by kevinnls** [comment]
i copied the 'formula' from the English version

**Comment by imba-tjd** [comment]
Oh well then I think it's acceptable.

**Comment by kevinnls** [comment]
there seems to be something wrong with the backend, which is in ruby, which i don't know

i have no idea. but i think it'd be in the [site repo](//github.com/adambard/learnxinyminutes-site) and something to do with how 

    ```md 
    ```


is rendered

`it-it` also started breaking when i tried the fix
