### ISSUE TITLE
Poor formatting of text in Learn Smalltalk in Y Minutes

### ISSUE THREAD

**Issue by horrido** [adambard/learnxinyminutes-docs#3829]
Visit https://learnxinyminutes.com/docs/smalltalk/.

Under "Simple syntax", the following paragraph is difficult to read because all the points run together. They should be formatted into an unordered list, at least.

**There are three sorts of messages - unary - a single symbol that may be several words conjoined in what we call camelcase form, with no arguments. For example ‘size’, ‘reverseBytes’, ‘convertToLargerFormatPixels’ - binary - a small set of symbols of the sort often used for arithmetic operations in most languages, requiring a single argument. For example ‘+’, ‘//’, ‘@’. We do not use traditional arithmetic precedence, something to keep an eye on. - keyword - the general form where multiple arguments can be passed. As with the unary form we use camelcase to join words together but arguments are inserted in the midst of the message with colons used to separate them lexically. For example ‘setTemperature:’, ‘at:put:’, ‘drawFrom:to:lineWidth:fillColor:’**

**Comment by mxschumacher** [comment]
Hey @horrido - readability is important, feel free to submit a PR that makes this paragraph easier to read and understand. Have a nice day!

**Comment by divayprakash** [comment]
Fix in PR #3832

**Comment by mxschumacher** [comment]
Okay, fix is merged. I'm closing this issue!
