### ISSUE TITLE
[C/en] - Variable Declaration is misleading

### ISSUE THREAD

**Issue by KoenigKrote** [adambard/learnxinyminutes-docs#3863]
The comment block explaining variable declarations is a bit misleading.
To a new user of C, it implies that all variables must be declared at the top of the current scope.
It clarifies this immediately after, stating that C99-compliant compilers do not require this, but it is still a misleading way to introduce the concept.
I have reworded this and made a pull request that more explicitly states how variable declarations work.

**Comment by divayprakash** [comment]
Closed in #3864
