### ISSUE TITLE
[javascript/fr] Example with for..of on a object literal => TypeError: ... not iterable !

### ISSUE THREAD

**Issue by Carl20cent** [adambard/learnxinyminutes-docs#3894]
Hey !
There is a little problem on the French version of the JavaScript page (this part is okay on the English version)
The problematic part is : 
```
// *ES6:* La boucle for...of permet d'itérer sur les propriétés d'un objet
var description = "";
var person = {fname:"Paul", lname:"Ken", age:18};
for (var x of person){
    description += x + " ";
}
description; // = "Paul Ken 18 "
```
When you try this, you will have an error :  **Uncaught TypeError: person is not iterable**
And it is normal because a object literal is not iterable !

To fix, it could be possible to just translate the english part like this (and sorry but i'm not sure how to fix it myself) : 
```
// La boucle for...of permet de parcourir un objet itérable
// (ce qui inclut les objets Array, Map, Set, String, ... Mais pas un objet littéral !)
var myPets = "";
var pets = ["cat", "dog", "hamster", "hedgehog"];
for (var pet of pets){
    myPets += pet + " ";
} // myPets = 'cat dog hamster hedgehog '
```

In any case, thanks for the site and all of this ! =)

/Carl

**Comment by mxschumacher** [comment]
Hey Carl,

thanks for pointing this problem out.

Your solution is fine, maybe we can also transition to ES6. e.g. const/let instead of var 

Making a contribution is not difficult, I encourage you to try it out. :) It's a good skill to have.

Here are the required steps: https://gist.github.com/MarcDiethelm/7303312

With git clone, commit, add and push you should already get quite far !

**Comment by kevinnls** [comment]
hi @mxschumacher 
it seems like @Carl20cent hasn't been active for quite a while. is it okay if i make the change?
@Carl20cent i hope you won't mind

**Comment by mxschumacher** [comment]
hey @kevinnls - sure feel free to create a PR. if you ping me in it, I can take a look

**Comment by kevinnls** [comment]
hey @Carl20cent good to see you're back! \
would you like to make the contribution? 😃 \
les nouveaux contributeurs sont toujours bienvenu !
