### ISSUE TITLE
Text error in string delimiter.

### ISSUE THREAD

**Issue by VamshidharReddyVemula** [adambard/learnxinyminutes-docs#3915]
In the output the value of aDouble is not displayed. It is missing a backslash in front the paranthesis.

let explanationString = #"The string I used was "The value of aDouble is \(aDouble)" and the result was \#(descriptionString)"#

solution:
let explanationString = #"The string I used was "The value of aDouble is \#(aDouble)" and the result was \#(descriptionString)"#

**Comment by divayprakash** [comment]
@VamshidharReddyVemula Could you please specify which document this is in regards to?

**Comment by verhovsky** [comment]
It's confusingly worded but it's intentional. `explanationString` is saying we wrote "`The value of aDouble is \(aDouble)`" in the code above and after compiling/executing it became "`The value of aDouble is 0.0`".
