### ISSUE TITLE
Site was blocked in China

### ISSUE THREAD

**Issue by galanoblcu** [adambard/learnxinyminutes-docs#3938]
As the title goes, the site has been blocked in China for quite a while.
I know it's due to the GFW...

I'm publishing this via vpn, however, most of my students cannot access to the site. Of course they can visit github at least for now.

**Comment by imba-tjd** [comment]
It's simply slow from China, but definitely not blocked. It's similar to github's release, using Amazon S3. Or you can try to use 数据流量 instead.

**Comment by galanoblcu** [comment]
[Image.jpeg]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by galanoblcu** [comment]
[Image.jpeg]

With VPN activated, access to learnxinyminutes was restored.

Regards,
Galano
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by verhovsky** [comment]
https://www.comparitech.com/privacy-security-tools/blockedinchina/ says it "appears to be accessible from mainland China".
