### ISSUE TITLE
[sql/en] SQL, really important language missing from the list

### ISSUE THREAD

**Issue by mp19uy** [adambard/learnxinyminutes-docs#400]
It would be great to have something about SQL.
I'm learning the language at the moment and it would be more than useful to have a "learn SQL in Y minutes" to use it as a reference.

**Comment by srirams6** [comment]
+1

**Comment by srirams6** [comment]
Started off. #1052

**Comment by haneefmubarak** [comment]
+1

**Comment by andysaini** [comment]
+1

**Comment by categulario** [comment]
Is someone working on this right now?

**Comment by vendethiel** [comment]
I don't think so! Go ahead.

**Comment by JoaoGFarias** [comment]
@categulario I'd suggest you to send a PR WIP ASAP (God, three acronyms) so you can get feedback if it's too complex or DBMS-specific.

**Comment by AlinaWithAFace** [comment]
+`

**Comment by evbarnett** [comment]
+1.

If no one is working on it right now, I'll do it next weekend.

**Comment by AlinaWithAFace** [comment]
Yes please!

**Comment by categulario** [comment]
@evbarnett I started this branch two years ago, maybe you can use it as starting point: https://github.com/categulario/learnxinyminutes-docs/tree/newlang/sql

**Comment by jdwalker519** [comment]
I'm a SQL Server database engineer, and very confused about what it is that's actually needed here, but I would like to contribute.  I'm new to GitHub.

**Comment by divayprakash** [comment]
@evbarnett Go ahead!

**Comment by categulario** [comment]
@jdwalker519 the idea is to write a basic guide to SQL with example queries as content, like the rest of the guides in this project (please take a look if you havent https://learnxinyminutes.com/). It shouln't be specific to any RDBMS but istead showcase general SQL language. Contact me if you need guidance with git/github/writing the guide.

**Comment by mbiondi17** [comment]
@jdwalker519 -- If you'd like help on the doc, I'm happy to provide some assistance. I'm not a database engineer specifically, but I've worked with SQL quite a lot. This comment history is kind of amusing, but I'd definitely like to see the page get finished.

**Comment by divayprakash** [comment]
Closed in #3349.
