### ISSUE TITLE
[C/english] a typo maybe in the do {}while 

### ISSUE THREAD

**Issue by m2cci-mohammed-djerida** [adambard/learnxinyminutes-docs#4182]
in C, it says : 
```int kk = 0;
  do {
    printf("%d, ", kk);
  } while (++kk < 10); // ++kk increments kk BEFORE using its current value.
  // => prints "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "
```
I think it should say "uses the current value of kk before incrementing" instead.

**Comment by imba-tjd** [comment]
Hi. Why. I don't think so.

**Comment by m2cci-mohammed-djerida** [comment]
@imba-tjd hello, 
because it is a "do while" loop, and the print is before the ++k so it uses kk before incrementing,
say we initiate kk to 0, 0 will be printed and then incremented.

while the comment says " Increments kk BEFORE using its current value", so it is not before, I think it should say AFTER.

**Comment by imba-tjd** [comment]
Well, it's indeed a bit confusing.
It's correct that ++kk firstly increse k then use k.
The print starts from 0 is because printf is before ++k.

**Comment by m2cci-mohammed-djerida** [comment]
oh I see, I just noticed that the comment meant the "++k" specifically and not the do-while loop 🙊
my bad 
thank you

**Comment by awschult002** [comment]
should this issue be closed then? Or would some added clarity be recommended. As it stands, there is nothing wrong with the statement in the code. However, I could see some added clarity that a `do while{}` loop executes one time before evaluating the condition.

**Comment by m2cci-mohammed-djerida** [comment]
Yes sorry… thank you
