### ISSUE TITLE
Split listing into "Active" and "Archive"

### ISSUE THREAD

**Issue by ad-si** [adambard/learnxinyminutes-docs#4184]
I was just browsing through the languages and a few of them are basically dead and I think this should be communicated. E.g. whip hasn't seen any development in 8 years. My suggestion would be to split the landing page in 2 sections "Active" and "Archive", where only the languages with changes in the last year (2 years ?) or are known to be still actively maintained are listed under Active.

What do you think?

**Comment by verhovsky** [comment]
I've deleted all the dead languages I've found except for CoffeeScript. If there's more let me know.
