### ISSUE TITLE
Include French translations on the homepage

### ISSUE THREAD

**Issue by kieutrang1729** [adambard/learnxinyminutes-docs#4189]
I recently added a French translation to the set theory article, but a link to it does not appear on the homepage like it should. There is also a French translation of the Rust page (4 years old) which also does not appear. Is there a page where we need to add the links manually?

**Comment by roptat** [comment]
rust has `Rust` as its English title but `rust` as its French title; set-theory has the same title in both languages, but a different category. Could that be the issue?
