### ISSUE TITLE
[BUG] [vim/en] Greek download .txt file instead of english

### ISSUE THREAD

**Issue by darigovresearch** [adambard/learnxinyminutes-docs#4211]
When clicking the LearnVim.txt file at the top of the page it links to a .txt file which is in Greek. Couldn't find the source file and now sure how this file is generated to make the relevant corrections from the current version of the file.

Happy to make a pull request if given advice on how this file is generated and where to make the pull request

![image](https://user-images.githubusercontent.com/30328618/128645282-3911b96a-e6d8-42af-ba71-bc428d16dfc5.png)

Source page - https://learnxinyminutes.com/docs/vim/
LearnVim.txt - https://learnxinyminutes.com/docs/files/LearnVim.txt

**Comment by Menelion** [comment]
@darigovresearch Thanks for reporting this! I tried to fix it in #4220. If that's enough, I'll merge it as soon as possible.

**Comment by darigovresearch** [comment]
@Menelion & @adambard thanks for taking a look at this, it appears that the download link above is still in Greek, the expectation is to download the English version of the file when on the English page

Is there a reason why this is still the case after the merge of the pull request?
