### ISSUE TITLE
[Correction] -  Gitguys link on Git page redirects to a site called GoGoPdf

### ISSUE THREAD

**Issue by sambarvadai** [adambard/learnxinyminutes-docs#4314]
Hello all,

I was checking the page for learning more about Git.  I clicked on one of the "Further information" links and found out that the link for "GitGuys" redirected to a site called GoGoPDF. Can this link be checked or removed from the page?

**Comment by mribeirodantas** [comment]
Thanks for reporting this, @sambarvadai. I'll remove it.
