### ISSUE TITLE
OCaml page listed twice

### ISSUE THREAD

**Issue by apfeltee** [adambard/learnxinyminutes-docs#4328]
The greek translation of the OCaml page is errornously displayed twice, but I think it's meant to be displayed as a language tag.   
It links to [/docs/el-gr/ocaml-gr/](https://learnxinyminutes.com/docs/el-gr/ocaml-gr/).

This is really minor, and I'm sorry to say that I'm not sure where it would be 'correctly' filed.

**Comment by imba-tjd** [comment]
I have added the `lang` header in https://github.com/adambard/learnxinyminutes-docs/commit/ad760a7adf9460ba1b6e4514d7fdabe743e5943e. Though this issue still exists.

**Comment by avelican** [comment]
Yeah, there's two links and the first one is in Greek! At first I thought something had gone wrong with the character encoding :)

**Comment by superherointj** [comment]
I also stumbled upon this problem. Any idea on how to solve this?

**Comment by verhovsky** [comment]
<img width="788" alt="solvd" src="https://github.com/adambard/learnxinyminutes-docs/assets/5687998/04b2c6d2-fcfe-47bb-9101-ff4a04c46db4">

looks solved to me
