### ISSUE TITLE
[Request] [Ballerina/en-us]

### ISSUE THREAD

**Issue by pavinduLakshan** [adambard/learnxinyminutes-docs#4345]
website: [ballerina.io](https://ballerina.io/)
documentation: [ballerina.io/learn](https://ballerina.io/learn/)
repository: [ballerina-platform/ballerina-lang](https://github.com/ballerina-platform/ballerina-lang)

**Comment by Kaamkiya** [comment]
This has now been added! You can see it [here](https://learnxinyminutes.com/docs/ballerina).

I'm sorry your issue wasn't closed.

**Comment by pavinduLakshan** [comment]
Ah great! Thanks for letting me know. We can close this issue now.
