### ISSUE TITLE
[css/es] CSS web page broke 

### ISSUE THREAD

**Issue by Jonatandb** [adambard/learnxinyminutes-docs#4375]
1 - CSS/es home page link duplicated.
2 - CSS/es page is not working properly.

----

![image](https://user-images.githubusercontent.com/8082172/162558812-96c910de-01d3-4169-8219-f569fdeeb4c0.png)

---

![image](https://user-images.githubusercontent.com/8082172/162558769-4fc33827-77ef-478b-a7c4-4bc6ff0a53a3.png)

**Comment by andrewkibet** [comment]
Ensure that you have the curly brackets
