### ISSUE TITLE
[scala/en] #4193 is in master but not on website

### ISSUE THREAD

**Issue by martineizayaga** [adambard/learnxinyminutes-docs#4398]
The change (5e1e2a0a15e0e3005d29baebf43db84175991deb) is in master.
https://github.com/adambard/learnxinyminutes-docs/blob/835d077573fea060406ca6e5096779526ae96760/scala.html.markdown?plain=1#L484-L485

But the website doesn't show the change.

<img width="1008" alt="Screen Shot 2022-05-26 at 12 15 15 PM" src="https://user-images.githubusercontent.com/28035767/170529538-fd578655-da02-4ed7-8665-d16a38f006de.png">

**Comment by mribeirodantas** [comment]
The website had not been updated in a while, but I talked to Adam and this is now fixed. Every hour the website will be updated based on changes in the master branch. Thanks for reporting!
