### ISSUE TITLE
[Request] Improve/update Docker documentation

### ISSUE THREAD

**Issue by mribeirodantas** [adambard/learnxinyminutes-docs#4447]
Docker documentation is currently very superficial and could really benefit from contributions (maybe even a new document from scratch). It's a very important tool and I think LXIYM could really benefit from a nice document on Docker.

**Comment by akshitadixit** [comment]
Hey I'd love to work on this!

**Comment by mribeirodantas** [comment]
This is great to hear, @akshitadixit ! Let me know if you need help 😄

**Comment by akshitadixit** [comment]
Hi @mribeirodantas I'm revamping the docs for this, and dividing it into a brief intro, the docker CLI (bunch of basic commands one needs to get started with) and the dockerfile. Is there anything particular you want me to keep in mind or add in the docs?

**Comment by akshitadixit** [comment]
Also if you could please provide me a bit of clarity on this statement in the [CONTRIBUTING.markdown](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown) file

https://github.com/adambard/learnxinyminutes-docs/blob/ab877e93eb7dfc8536683d5862477fb62f3b224b/CONTRIBUTING.markdown?plain=1#L79-L82

* What does billing mean here?
* What do we mean by first contributor?
* Will my PR be a substantial contribution? Do I add myself in the header where contributors are required to be mentioned?

**Comment by mribeirodantas** [comment]
It's just to say that people shouldn't be playing with the order of names in the contributors section of the article. The first name is the person who started working on the document, the second is the second to, and so on. Also, that small fixes (removing one extra space, for example) isn't really worth putting someone as a contributor, but it's up to the person. In my opinion, any content contribution is a substantial contribution, so yes, you are a contributor to me.

Currently, we have a docker article [in Spanish](https://github.com/adambard/learnxinyminutes-docs/blame/master/es-es/docker-es.html.markdown) written by Ruslan with later contributions by Michael Chan, and [a translation to Chinese](https://github.com/adambard/learnxinyminutes-docs/blame/master/zh-cn/docker-cn.html.markdown) by imba-tjd. It's an uncommon situation, as the articles usually start with a version in English, but it is not the case for Docker here.

The spanish article is pretty small, so I would say it's fine if you want to start from scratch (it would be good if it kind included a similar version of what the Spanish is providing, just look at the docker commands). In this case, I would also add Ruslan and Michael as the first two authors as they've written the original article, and then you as third author. It's a bit of a tricky situation, but the git history always shows who did the largest work, so it's fine, as I see.

Feel free to ask more questions if you run into issues.

Best,

**Comment by mribeirodantas** [comment]
Fixed by https://github.com/adambard/learnxinyminutes-docs/pull/4541
