### ISSUE TITLE
[hack/en] page doesn't reflect code contents

### ISSUE THREAD

**Issue by AndrewDiMola** [adambard/learnxinyminutes-docs#4455]
Just merged in new changes for the Hack page, but I don't see the page reflecting those changes. 

Unfortunately I don't have the ability to test locally at the moment -- my work machine won't allow the necessary dependencies to be installed. 

https://learnxinyminutes.com/docs/hack/

Wondering if it has anything to do with the markdown header: I changed it from `php` to `hack`: https://github.com/adambard/learnxinyminutes-docs/blob/master/hack.html.markdown#L14

Note: the linked `learnhack.hh` file is correct, just not the rendered page.

**Comment by mribeirodantas** [comment]
The server is updated once an hour, if I recall correctly, so the changes are not immediate. Could you please check if your changes are there now? It seems to me they are.

**Comment by AndrewDiMola** [comment]
Hello @mribeirodantas, thanks for responding! Confirming that the code embed and the page descriptions have not updated. Assuming that the entire page renders from the source, though I may be wrong.

**Comment by mribeirodantas** [comment]
I had a quick look into it and it's weird that your changes didn't appear in the website but mine, in commits after yours, appear. Nothing obvious in the file parameters seemed to have changed. It's too hot now 🥵, later when I get home I will look into it again hehe

**Comment by AndrewDiMola** [comment]
No rush! Get to cooler ground!

**Comment by mribeirodantas** [comment]
Honestly, it's not clear to me what's going on. I can ask @adambard to have a look in the server but before, I would suggest you to try to revert the change on this line:
https://github.com/adambard/learnxinyminutes-docs/blob/master/hack.html.markdown#L14

Let's make sure it's not that, and then I ask him.

**Comment by mribeirodantas** [comment]
Merged. Now let's wait ~1 hour to see if it updates 😅

**Comment by AndrewDiMola** [comment]
![image](https://user-images.githubusercontent.com/5179225/179827652-32e260e5-c437-44ea-be97-b35db99b22aa.png)

**Comment by mribeirodantas** [comment]
It worked 😄

**Comment by AndrewDiMola** [comment]
Woo!! Thank you!
