### ISSUE TITLE
[Request] [GDScript2.0/en]

### ISSUE THREAD

**Issue by Wichamir** [adambard/learnxinyminutes-docs#4470]
There's already a GDScript guide here, but Godot 4.0 is close to beta and it introduces GDScript 2.0, which has many compatibility breaking features. Maybe a new guide should be added (like with Python2 and Python3) or at least parts of the old one should be rewritten. Anyway here are some resources:
- https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html
- https://gamefromscratch.com/gdscript-2-in-godot-4/
- https://godotengine.org/article/gdscript-progress-report-feature-complete-40
- https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged

**Comment by Wichamir** [comment]
Btw there are two pull request related to GDScript, which haven't been reviewed, although they seem ok be merged:
- #4327
- #4326

**Comment by mribeirodantas** [comment]
Thanks for the issue, @Wichamir. I just merged the two PRs.
