### ISSUE TITLE
[Request] Update C, C++ and C# language name in translations

### ISSUE THREAD

**Issue by mribeirodantas** [adambard/learnxinyminutes-docs#4473]
A recent pull request (https://github.com/adambard/learnxinyminutes-docs/pull/4472) updated the name of the programming language C in the original document (English) from **c** to **C**. This must be done in the translated documents also:

https://github.com/adambard/learnxinyminutes-docs/commit/fad63f0f6ab23a83bb923f45ff6cc6d1ec70757b
- [x] https://github.com/adambard/learnxinyminutes-docs/blob/master/de-de/c-de.html.markdown
- [x] https://github.com/adambard/learnxinyminutes-docs/blob/master/es-es/c-es.html.markdown
- [x] https://github.com/adambard/learnxinyminutes-docs/blob/master/pt-br/c-pt.html.markdown
- [x] https://github.com/adambard/learnxinyminutes-docs/blob/master/tr-tr/c-tr.html.markdown
- [x] https://github.com/adambard/learnxinyminutes-docs/blob/master/uk-ua/c-ua.html.markdown
- [x] https://github.com/adambard/learnxinyminutes-docs/blob/master/zh-cn/c-cn.html.markdown

And the same for C#:
https://github.com/adambard/learnxinyminutes-docs/pull/4475/commits/3e0a35ad372b6637ab4ab24a0e05c5c8f9d39230
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/de-de/csharp-de.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/fr-fr/csharp-fr.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/pt-br/csharp-pt.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/tr-tr/csharp-tr.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/zh-cn/csharp-cn.html.markdown

and C++:
https://github.com/adambard/learnxinyminutes-docs/pull/4475/commits/7f60e471fc7b703804da333d94ec941bd6fed2e9
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/de-de/c++-de.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/es-es/c++-es.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/fr-fr/c++-fr.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/it-it/c++-it.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/pt-br/c++-pt.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/ru-ru/c++-ru.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/tr-tr/c++-tr.html.markdown
- [X] https://github.com/adambard/learnxinyminutes-docs/blob/master/zh-cn/c++-cn.html.markdown

**Comment by greenbigfrog** [comment]
On the index page, some of the capitalization is wrong as well.

**Comment by mribeirodantas** [comment]
Thank you, @greenbigfrog. I was sure I had renamed all instances but the versions in English were left behind with the old capitalization. I just fixed this (https://github.com/adambard/learnxinyminutes-docs/pull/4477)
