### ISSUE TITLE
[zig/en] the page currently is 404

### ISSUE THREAD

**Issue by KaneRoot** [adambard/learnxinyminutes-docs#4507]
Hello, the page for the Zig programming language currently is 404.

I did the PR for Zig in December last year and it just has been merged a few days ago, but apparently the link is broken and I don't know if the problem comes from my PR #4293 or from somewhere else.

Please advice.
Thanks!

**Comment by romanthekat** [comment]
<img width="161" alt="image" src="https://user-images.githubusercontent.com/6695292/193472127-47fcdb06-15a2-4d46-a432-65d930a4879a.png">
seems like locally it builds fine, nothing special at first glance

**Comment by KaneRoot** [comment]
3-month update: still doesn't work. Is there something I can do?

**Comment by mribeirodantas** [comment]
Adam explained how to solve it [here](https://github.com/adambard/learnxinyminutes-docs/issues/4536#issuecomment-1312513059), @KaneRoot . Do you want to do it?

**Comment by mribeirodantas** [comment]
fixed by https://github.com/adambard/learnxinyminutes-docs/commit/fbaa905e23f26d20b37a3886dd8e07cd6edb8680
