### ISSUE TITLE
[zig/en] Zig page does not work

### ISSUE THREAD

**Issue by razetime** [adambard/learnxinyminutes-docs#4536]
Page for zig at https://learnxinyminutes.com/docs/zig/ returns a 404.

**Comment by mribeirodantas** [comment]
@adambard do you have any idea what's going on here?

**Comment by adambard** [comment]
Usually this means the page failed the build because the language could not be parsed. Solution is either to pick different language to highlight as (if the syntax has close neighbors and the comments are the same), implement a language parser for pygments, or else remove the highlighting

**Comment by sz47** [comment]
but zig is already supported for pygments [see here](https://pygments.org/docs/lexers/#pygments.lexers.zig.ZigLexer)

**Comment by verhovsky** [comment]
Is the issue that the site is using pygments.rb 1.2.1

https://github.com/adambard/learnxinyminutes-site/blob/4674373b1f2824860007486cdcc5641bbe8a8035/Gemfile.lock#L93

which was released on December 07, 2017

https://rubygems.org/gems/pygments.rb/versions

**Comment by mribeirodantas** [comment]
fixed by https://github.com/adambard/learnxinyminutes-docs/commit/fbaa905e23f26d20b37a3886dd8e07cd6edb8680

**Comment by verhovsky** [comment]
@mribeirodantas why not fix it with https://github.com/adambard/learnxinyminutes-site/pull/108 instead?

**Comment by mribeirodantas** [comment]
It should be fixed when your PR is merged. In the meantime, it's fixed some other way. Let's hope your PR is merged some day.
