### ISSUE TITLE
suggestion: add an explicit license tag and license file

### ISSUE THREAD

**Issue by nbehrnd** [adambard/learnxinyminutes-docs#4544]
The end of the landing page (https://learnxinyminutes.com/) (already) states

```
All articles © the original author and contributors, and licensed under a CC BY-SA 3.0 license.
```

Contrasting to many other projects on GitHub, the repository *on [GitHub](https://github.com/adambard/learnxinyminutes-docs)* lacks an explicit tag in right hand column «About», as well as the then corresponding license file.  Once a project is assigned a license, GitHub sets the tag and automatically adds the file in question; the process is assisted by the platform's [documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

Because this addition exceeds the scope of a simple PR, I suggest the owner/the maintainers of the project add them.

**Comment by mribeirodantas** [comment]
Mentioning @adambard, the owner of the repo.

**Comment by nbehrnd** [comment]
@mribeirodantas  @adambard As a gentle reminder, the suggestion still awaits a decision by you.

**Comment by mribeirodantas** [comment]
I don't have admin power so we have to wait for @adambard 😞

**Comment by adambard** [comment]
I have added a LICENSE.txt, but since the CC-3.0-SA license used by this project is not supported by github's tooling, not much else has changed.

**Comment by nbehrnd** [comment]
As soon as a fork is synchronized to the principal branch of the project .and. the web page is updated (e.g. `F5` for firefox), the legal symbol is shown. In addition, the bar symbolizing the part of [community standards](https://github.com/adambard/learnxinyminutes-docs/community) which are machine readable became a little greener, too.  So thank you for both.

![license](https://user-images.githubusercontent.com/19709084/215556117-ade3f179-cc03-4523-9993-9b73b3898fdf.png)

![community_standards](https://user-images.githubusercontent.com/19709084/215556217-c3dacf56-3743-4865-bc32-6a111803fc08.png)
