### ISSUE TITLE
[en/bash] Wrong title (Learn X in Y Minutes: Scenic Programming Language Tours)

### ISSUE THREAD

**Issue by Psyhackological** [adambard/learnxinyminutes-docs#4565]
*I could not find where I can change it and submit a Pull Request, so I created this issue.*

## The title problem
It should have a `Learn Bash in Y Minutes` instead of `Learn X in Y Minutes: Scenic Programming Language Tours`.

Source: https://learnxinyminutes.com/docs/bash/

## Example — Lua
Title: `Learn Lua in Y Minutes`

Source: https://learnxinyminutes.com/docs/lua/

I hope that's a good enough explanation.

**Comment by Psyhackological** [comment]
Same for the Vim it seems: https://learnxinyminutes.com/docs/vim/

**Comment by mribeirodantas** [comment]
It's the same for all articles under Tools. This has been a problem in the past, but it's not clear to me how they solved.

**Comment by mribeirodantas** [comment]
Ok, found it. [It's in the site app](https://github.com/adambard/learnxinyminutes-site/blob/15d8e77e806513bff680f16749d0d7b02dace359/source/layouts/layout.erb#L14)

**Comment by Psyhackological** [comment]
> It's the same for all articles under Tools. This has been a problem in the past, but it's not clear to me how they solved.

Ah I see. Thanks for explaining.

**Comment by Psyhackological** [comment]
> Ok, found it. [It's in the site app](https://github.com/adambard/learnxinyminutes-site/blob/15d8e77e806513bff680f16749d0d7b02dace359/source/layouts/layout.erb#L14)
> 
> I just created a PR over there https://github.com/adambard/learnxinyminutes-site/pull/107

Oh, that's in the another repo, good find! Thanks!
