### ISSUE TITLE
[Request] [ruby/en]

### ISSUE THREAD

**Issue by akshitadixit** [adambard/learnxinyminutes-docs#4583]
Hi, I'd love to modify and/or revamp the Ruby language tutorial in a much more simplified yet complete way. 

I want the tutorial to be divided into headings, that introduce concepts one by one rather than a unified singular doc version that is currently up there.

Additionally, I'd want to include meta programming concepts in as well since they're Ruby's highlights and might come handy for someone wanting an overview of the language.

**Comment by nbehrnd** [comment]
> Hi, I'd love to modify and/or revamp the Ruby language tutorial in a much more simplified yet complete way. 

Go ahead, i.e. prepare a new version and submit your work as a PR.

> I want the tutorial to be divided into headings, that introduce concepts one by one rather than a unified singular doc version that is currently up there.

The suggested division into individual blocks (similar to e.g., the
presentation of `markdown`) and maintaining them in groups potentially renders
the compilation easier to digest on learningxinyminutes.com, too.

 
> Additionally, I'd want to include meta programming concepts in as well since they're Ruby's highlights and might come handy for someone wanting an overview of the language.

So far, my perception of the project is to provide you all necessary tools to
solid start (a beginners/101 instruction) into a language.  For this reason, I
would like to suggest to focus on the first two points now, and submit these
improvements as a PR/multiple consecutive PRs.  These would then provide a
stronger foundation to present the meta programming concepts in an additional
increment of improvement.

**Comment by akshitadixit** [comment]
Sure thing, on it!

**Comment by akshitadixit** [comment]
Hi @nbehrnd  I'm not in the best mental state to pull this task off to completion now. I will resume it in the near future, but until then I'd politely request a break from this. Meanwhile if any other contributor would want to take this forward please feel free to assign it to them.
