### ISSUE TITLE
[Request] Terraform/HCL

### ISSUE THREAD

**Issue by heitorPB** [adambard/learnxinyminutes-docs#4608]
[Terraform](https://www.terraform.io/) is an awesome tool to manage infrastructure. It would be nice to have a page here. 

Terraform is a tool that uses HCL (a configuration language). There are other tools from HashiCorp that also use HCL, so maybe a page for HCL and one for Terraform?

**Comment by verhovsky** [comment]
Added in #3949

It would be good if you could review/proofread it. It was missing a lot of articles (a/the) and had just general grammar issues that I fixed, but since I'm not familiar with Terraform I could've made mistakes.
