### ISSUE TITLE
cannot build site locally

### ISSUE THREAD

**Issue by yuxi-liu-wired** [adambard/learnxinyminutes-docs#4683]
Following https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown I got up to 
* Build the site or run a development server to test your changes (NOTE: run these commands at learnxinyminutes-site/).
* Build - bundle exec middleman build

at which point I got a screenful of error that looks like `fatal: no such path 'th-th.markdown' in HEAD`.

**Comment by verhovsky** [comment]
A bunch of `git blame:` errors is expected, although `th-th.markdown` specifically is weird.

Do you still get these errors? It would be helpful if you posted the entire command line session and also what operating system and Ruby version you're using.

**Comment by verhovsky** [comment]
Sounds like you figured out the issue in #4682
