### ISSUE TITLE
[language/lang-code]: `fish_add_path` is invalid

### ISSUE THREAD

**Issue by onkoe** [adambard/learnxinyminutes-docs#4745]
## Is this a major issue that you cannot fix?

No, it's trivial! However, I'd like to document it quickly so I can take a look a bit later! :)

## The Problem

Under the main `Guide` section, the following text appears:

```
Adding something to your fish PATH Variable is easy:

    fishpathadd ~/cowsay
```

Not only is `fish_add_path` backwards, but `_add_` now becomes italic because of the un-escaped underscores.

There may be similar issues throughout the article.

**Comment by verhovsky** [comment]
Fixed in #4305
