### ISSUE TITLE
[asciidoc/en] AsciiDoc file extension is incorrect

### ISSUE THREAD

**Issue by Kaamkiya** [adambard/learnxinyminutes-docs#4833]
## Is this a major issue that you cannot fix?
No. This is a tiny issue. I didn't make a PR because it would be pointless, when any maintainer can fix this in seconds. If you want me to, I can.

The correct file extension for AsciiDoc is `.adoc`, but the extension on the page is `.md`. 

### To Reproduce
1. Go to the [page](https://learnxinyminutes.com/docs/asciidoc/)
2. See "Get the code: asciidoc.md". 

It should really say "Get the code: asciidoc.adoc"

Thanks!

**Comment by vendethiel** [comment]
> when any maintainer can fix this in seconds

Certainly a few seconds since I don't have a local copy, I just fixed it through github anyway.
Thanks for the report.
