### ISSUE TITLE
[Ada/en] Add a github action to regenerate the website

### ISSUE THREAD

**Issue by Lucretia** [adambard/learnxinyminutes-docs#4835]
I added Ada 3 weeks ago and the website still hasn't been regenerated to update it, this should be automatic on merging a PR.

I want to be able to point to the website, but because it's not been generated, I have to point to github instead.

**Comment by Lucretia** [comment]
Is there any particular reason why the website still has NOT been regenerated to add in changes?

**Comment by verhovsky** [comment]
Fixed in https://github.com/adambard/learnxinyminutes-docs/commit/a2c3935a9bca81410d325e26762aa93dbb5f8707 and a bunch of other related commits.
