### ISSUE TITLE
[C/ja-jp] Add Japanese Translation for C

### ISSUE THREAD

**Issue by kenryuS** [adambard/learnxinyminutes-docs#4879]
So the classmates of NIT won't suffer learning C.

**Comment by verhovsky** [comment]
@kenryuS could you please proofread #4534

**Comment by verhovsky** [comment]
Thanks. Mind doing these https://github.com/adambard/learnxinyminutes-site/blob/master/data/i18n.yaml ?

**Comment by kenryuS** [comment]
ok
