### ISSUE TITLE
[gleam/en] [golfscript/en] Page not found

### ISSUE THREAD

**Issue by dbohdan** [adambard/learnxinyminutes-docs#4961]
While a link for Gleam and for GolfScript is present on the front page, those links lead to a 404:

- <https://learnxinyminutes.com/docs/gleam/> ([archived](https://web.archive.org/web/20240513230059/https://learnxinyminutes.com/docs/gleam/) May 13)
- <https://learnxinyminutes.com/docs/golfscript/> ([archived](https://web.archive.org/web/20240514235410/https://learnxinyminutes.com/docs/golfscript/) May 14)

**Comment by verhovsky** [comment]
https://learnxinyminutes.com/docs/gleam/ still 404's but https://learnxinyminutes.com/docs/gleam/index.html works and there's no errors in the [build](https://github.com/adambard/learnxinyminutes-site/actions/runs/9259007013/job/25480750858#step:6:5156) and both URLs work for me locally.
