### ISSUE TITLE
[BUG] Perl page returns 404

### ISSUE THREAD

**Issue by 1ycx** [adambard/learnxinyminutes-docs#5160]
## Is this a major issue that you cannot fix?
Yes

The default (probably en or en-us) doesn't work for, other language pages are accessible. 
![image](https://github.com/user-attachments/assets/db6db9d5-f44c-45c6-8bbf-8f3e173518e5)

**Comment by verhovsky** [comment]
thank you

**Comment by 1ycx** [comment]
Excellent, thanks!
