### ISSUE TITLE
Incorrect comment: 'foo == "I am bar"' should be 'foo = "I am bar"'

### ISSUE THREAD

**Issue by WilliamColton** [adambard/learnxinyminutes-docs#5197]
[link](https://learnxinyminutes.com/docs/zh-cn/c++-cn/)

The comment in the following code is misleading. It incorrectly uses == to describe an assignment operation. The correct expression should be foo = "I am bar" instead of foo == "I am bar".

`// 这句话的并不会改变fooRef的指向，其效果与“foo = bar”相同。
// 也就是说，在执行这条语句之后，foo == "I am bar"。
fooRef = bar;`

**Comment by vendethiel** [comment]
It is demonstrating the equality that holds at point, which looks fine to me.
