### ISSUE TITLE
/docs/raku footer update

### ISSUE THREAD

**Issue by frainfreeze** [adambard/learnxinyminutes-docs#5203]
Text in footer:

Read the [Raku Advent Calendar](https://rakuadventcalendar.wordpress.com/). This is a great source of Raku snippets and explanations. If the docs don’t describe something well enough, you may find more detailed information here. This information may be a bit older but there are many great examples and explanations. **Posts stopped at the end of 2015** when the language was declared stable and Raku v6.c was released.

- this is no longer true, the Raku Advent Calendar is still updated.

**Comment by verhovsky** [comment]
https://github.com/adambard/learnxinyminutes-docs/commit/8b7089d66773ee4f017553b48c34b32709213298
