### ISSUE TITLE
The color background is not dark in dark mode

### ISSUE THREAD

**Issue by lulin** [adambard/learnxinyminutes-docs#5205]
![learnxinyminutes-dark-mode-code-blocks](https://github.com/user-attachments/assets/25df44ac-9017-4ed3-964f-8bf1e9ceb86b)

**Comment by lulin** [comment]
If I change system theme to dark mode, most parts of learnxinyminutes except code blocks are in dark and are rendered nicely. This makes braces hard to read

**Comment by verhovsky** [comment]
What browser/operating system?
