### ISSUE TITLE
[HTML] Request/Suggest: HTML

### ISSUE THREAD

**Issue by mp19uy** [adambard/learnxinyminutes-docs#621]
I think there should be a doc about html here.  
I use learnxinyminutes as a quick reference guide and I was surprised when I didn't find html in the list.

I'm going to start writing the guide/doc based in personal knowledge and main references like W3C Wiki, W3Schools, Wikipedia and Codeacademy.  
I don't have a lot of experience but I know the basics, so I think I can write at least the essentials about html and then someone can improve it.

**Comment by JoaoGFarias** [comment]
This section was already merged: https://learnxinyminutes.com/docs/html/
This issue can be closed
