### ISSUE TITLE
[bug] Broken contributors link in translated pages

### ISSUE THREAD

**Issue by AndreyAkinshin** [adambard/learnxinyminutes-docs#791]
An example.
Page: http://learnxinyminutes.com/docs/ru-ru/julia-ru/
Link at the bottom of the page: Originally contributed by Leah Hanson, and updated by [-1 contributors](https://github.com/adambard/learnxinyminutes-docs/blame/master/ru-ru.markdown)

The link is broken, it gives 404 page.

**Comment by matiasgarciaisaia** [comment]
Seems to have been fixed with dbf5367fe4a0a7b2accfa0b0c30a26e24979b96b - [this line](https://github.com/adambard/learnxinyminutes-site/commit/dbf5367fe4a0a7b2accfa0b0c30a26e24979b96b#diff-11d59b3b0e7b20a5fda7d543e3e88496R23) specifically.

**Comment by Oire** [comment]
@adambard, is it fixed?

**Comment by adambard** [comment]
Haven't noticed it lately :)
