### ISSUE TITLE
[haskell/en] Currying explanation in 'Where X=haskell'

### ISSUE THREAD

**Issue by hobozo** [adambard/learnxinyminutes-docs#80]
A niggling point...

The comment:

-- currying: if you don't pass in all the arguments to a function,
-- it gets "curried". That means it returns a function that takes the 
-- rest of the arguments.

is not strictly true. What you are describing is 'partial application'. Currying is a method of converting a function that takes multiple arguments into a series of n functions that take one argument each. Refer to the curry and uncurry functions in Haskell Data.Tuple module for a clearer explanation.

**Comment by bharrisau** [comment]
Closed by #816
