### ISSUE TITLE
[request] LaTex

### ISSUE THREAD

**Issue by konfiot** [adambard/learnxinyminutes-docs#815]
Would be really nice to have a LaTex tutorial there !

**Comment by yurrriq** [comment]
:+1:

**Comment by iamrahil** [comment]
:+1:
I learnt Latex a long time ago and I thought that a page over here would be the best way to revisit it. If someone is already working on it, or is interested, please let me know. I might be able to help

**Comment by ramananbalakrishnan** [comment]
duplicated in #1119 , might as well close both issues, since PRs #1412 and #1821 solve them.

**Comment by JoaoGFarias** [comment]
[There is a article on LaTeX](https://github.com/adambard/learnxinyminutes-docs/blob/master/latex.html.markdown)
