### ISSUE TITLE
learnxinyminutes.com/docs/forth/ results in a 404

### ISSUE THREAD

**Issue by HorseMD** [adambard/learnxinyminutes-docs#909]
Seems the Forth section isn't being generated properly?

**Comment by levibostian** [comment]
Thanks for finding this. This happens every now and then and @adambard is pretty good at getting it back up and running.

**Comment by adambard** [comment]
The problem was that there's no forth highlighting in rouge. I've switched it to use factor's for now, although it's a bit wonky -- especially, the comments are not highlighted. I wonder if it's even any better than no highlighting?

**Comment by levibostian** [comment]
My vote is no highlighting because it is just simply taking keywords from the comments and highlighting it making it not very useful at all. Highlighting is great except when it is kinda broken like that.

**Comment by adambard** [comment]
Agreed, I removed that.
