### ISSUE TITLE
duplicate link

### ISSUE THREAD

**Issue by miguelarauj1o** [adambard/learnxinyminutes-docs#925]
Hi, link to Common Lisp is duplicated on the home page.

__print screen:__
![dup](https://cloud.githubusercontent.com/assets/7546651/5721806/abbcb006-9b14-11e4-878f-cf6ac6748b92.png)

**Comment by iirelu** [comment]
I believe it's because the metadata table for pt-br/common-lisp-pt.html.markdown is missing the `lang` field.

**Comment by adambard** [comment]
That sure sounds like a thing that always happens. One moment.

**Comment by adambard** [comment]
Should be fixed next build. Thanks!

**Comment by miguelarauj1o** [comment]
:+1: see you later, peace!
