### ISSUE TITLE
Mobile rendering is unuseable on iOS. 

### ISSUE THREAD

**Issue by joshuaunderwood7** [adambard/learnxinyminutes-docs#929]
The current rendering on iPhone makes it so you can see about 23 characters of the code. And have to scroll back and forth every line. Can we get a better page layout for mobile?

**Comment by divayprakash** [comment]
This needs to be tested to determine the current situation.

**Comment by divayprakash** [comment]
Seems to be fixed. I've tested this and it doesn't seem to be an issue now.
