### ISSUE TITLE
Would Gherkin be suitable for enter into the Tools list?

### ISSUE THREAD

**Issue by JoaoGFarias** [adambard/learnxinyminutes-docs#952]
Hi folks,

I observed [Gherkin](https://github.com/cucumber/cucumber/wiki/Gherkin) is cited in the [Ruby Ecosystem](http://learnxinyminutes.com/docs/ruby-ecosystem/), but I see it as a very important tool both for use case specification and testing, given that it is used for a variety of framework in a manifold of programming languages. I want to know if you guys find it suitable for be a entering in the Tools list.

I can write it the article :)
I'd use the [Cucumber documentation](https://github.com/cucumber/cucumber/wiki/A-Table-Of-Content) for reference, but observing just the Gherkin language, which is framework independent.

[]s
João

**Comment by levibostian** [comment]
If there is enough information to write about Gherkin that it deserves its own doc and there is not already a doc out there that is written pretty well on Gherkin then YES**! 

** If there is not a lot to say about it, then you can just write more about it in the Ruby ecosystem doc. If there is already a doc out there for it then you can link to it in the bottom of the Ruby ecosystem doc.

**Comment by vendethiel** [comment]
The docs should usually be enough.
