### ISSUE TITLE
Formatting issues with asymptotic notation

### ISSUE THREAD

**Issue by Jakehp** [adambard/learnxinyminutes-docs#953]
Look here:
https://github.com/adambard/learnxinyminutes-docs/blob/master/asymptotic-notation.html.markdown
Then:
http://learnxinyminutes.com/docs/asymptotic-notation/

Formatting isn't correct.

**Comment by adambard** [comment]
Does this bug refer to the stuff I unfucked already or something new?

**Comment by Jakehp** [comment]
If you click the first link, you'll notice at "Example 1" and "Example 2" there's a lot of code blocked stuff. Then on http://learnxinyminutes.com/docs/asymptotic-notation/ it's not there. Not sure what the issue is.

**Comment by adambard** [comment]
Ah, I see. The \`\`\` code blocks should have blank lines before and after for whatever markdown library we use to parse them correctly. I've gone in and fixed all the obvious ones, I think that's all of them.

**Comment by Jakehp** [comment]
Looks better!
