### ISSUE TITLE
Perl6, when flattening happens

### ISSUE THREAD

**Issue by brxfork** [adambard/learnxinyminutes-docs#983]
The paragraph "# You need to be aware of when flattening happens exactly." seems incorrect.

> `((1,2), 3, (4,5)).map({...});`  # iterates over three elements (method call)
> `> map {...}, ((1,2),3,(4,5));`   # iterates over five elements (argument list is flattened)

Tested with perl6 version 2014.12 built on parrot 6.10.0 revision 0 and version 2015.02/MoarVM, it iterates over five elements. I find that: http://doc.perl6.org/language/containers#What_flattens%2C_what_doesn%27t%3F

> `(@a, @b, @c).pick(1);`         # picks one of three arrays (method call)
> `> pick 1, @a, @b, @c;`           # flattens argument list and pick one element

With version 2014.12/parrot, those two lines gives same result (flatten):

> `> @a`
> `1 2`
> `> @b`
> `3 4`
> `@c`
> `5 6`
> `> (@a,@b,@c).pick(1);`
> `4`
> `> pick 1,@a,@b,@c;`
> `1`

**Comment by vendethiel** [comment]
Yes, this is a "future-ish" vision. The GLR is expected to be completed by @pmichaud around this month.
