### ISSUE TITLE
Request Permission to Copy and Adapt

### ISSUE THREAD

**Issue by bucaran** [adambard/learnxinyminutes-docs#994]
Do you folks mind if I use and adapt (with proper attribution) your _learn go in Y minutes_ commented source code / tutorial and included as is on my own repo [here](https://github.com/bucaran/getgo).

By adaptation I mean basically simpliying the document wherever possible and / or perhaps leaving out some parts.

Cheers!

**Comment by levibostian** [comment]
I cannot speak on behalf of @adambard but looking at the README license, I think you are free to do whatever you feel. All work is licensed under [this](https://creativecommons.org/licenses/by-sa/3.0/deed.en_US) creative commons license so as long as you follow that license rules, you are good.

**Comment by bucaran** [comment]
:smile: Thank you!

**Comment by adambard** [comment]
Yup, CC has the details, go right ahead. Thanks for asking though!
