### ISSUE TITLE
Translations of the page headers

### ISSUE THREAD

**Issue by geoffliu** [adambard/learnxinyminutes-docs#996]
... and footers too.

Even in the translated pages, the top of each page up to "Get the code" are still all in English. We should have translated version of those alongside, for user-friendliness, and probably SEO.

I'm thinking of either having one top-level config file that has the translated headers for every locale, or a special file in each of the locale specific directories. @adambard what do you think?

**Comment by adambard** [comment]
That's definitely a great idea. It'll probably be a little while before I get to it, but I'll make sure it's next on my list.
